// Package declaration for this file
package net.minestom.server.game;

/**
 * This class contains all the generated constants for {@link GameEvent}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface GameEvents permits GameEvent {
    // Calls a method
    GameEvent BLOCK_ACTIVATE = GameEventImpl.get("block_activate");

    // Calls a method
    GameEvent BLOCK_ATTACH = GameEventImpl.get("block_attach");

    // Calls a method
    GameEvent BLOCK_CHANGE = GameEventImpl.get("block_change");

    // Calls a method
    GameEvent BLOCK_CLOSE = GameEventImpl.get("block_close");

    // Calls a method
    GameEvent BLOCK_DEACTIVATE = GameEventImpl.get("block_deactivate");

    // Calls a method
    GameEvent BLOCK_DESTROY = GameEventImpl.get("block_destroy");

    // Calls a method
    GameEvent BLOCK_DETACH = GameEventImpl.get("block_detach");

    // Calls a method
    GameEvent BLOCK_OPEN = GameEventImpl.get("block_open");

    // Calls a method
    GameEvent BLOCK_PLACE = GameEventImpl.get("block_place");

    // Calls a method
    GameEvent CONTAINER_CLOSE = GameEventImpl.get("container_close");

    // Calls a method
    GameEvent CONTAINER_OPEN = GameEventImpl.get("container_open");

    // Calls a method
    GameEvent DRINK = GameEventImpl.get("drink");

    // Calls a method
    GameEvent EAT = GameEventImpl.get("eat");

    // Calls a method
    GameEvent ELYTRA_GLIDE = GameEventImpl.get("elytra_glide");

    // Calls a method
    GameEvent ENTITY_DAMAGE = GameEventImpl.get("entity_damage");

    // Calls a method
    GameEvent ENTITY_DIE = GameEventImpl.get("entity_die");

    // Calls a method
    GameEvent ENTITY_DISMOUNT = GameEventImpl.get("entity_dismount");

    // Calls a method
    GameEvent ENTITY_INTERACT = GameEventImpl.get("entity_interact");

    // Calls a method
    GameEvent ENTITY_MOUNT = GameEventImpl.get("entity_mount");

    // Calls a method
    GameEvent ENTITY_PLACE = GameEventImpl.get("entity_place");

    // Calls a method
    GameEvent ENTITY_ACTION = GameEventImpl.get("entity_action");

    // Calls a method
    GameEvent EQUIP = GameEventImpl.get("equip");

    // Calls a method
    GameEvent EXPLODE = GameEventImpl.get("explode");

    // Calls a method
    GameEvent FLAP = GameEventImpl.get("flap");

    // Calls a method
    GameEvent FLUID_PICKUP = GameEventImpl.get("fluid_pickup");

    // Calls a method
    GameEvent FLUID_PLACE = GameEventImpl.get("fluid_place");

    // Calls a method
    GameEvent HIT_GROUND = GameEventImpl.get("hit_ground");

    // Calls a method
    GameEvent INSTRUMENT_PLAY = GameEventImpl.get("instrument_play");

    // Calls a method
    GameEvent ITEM_INTERACT_FINISH = GameEventImpl.get("item_interact_finish");

    // Calls a method
    GameEvent ITEM_INTERACT_START = GameEventImpl.get("item_interact_start");

    // Calls a method
    GameEvent JUKEBOX_PLAY = GameEventImpl.get("jukebox_play");

    // Calls a method
    GameEvent JUKEBOX_STOP_PLAY = GameEventImpl.get("jukebox_stop_play");

    // Calls a method
    GameEvent LIGHTNING_STRIKE = GameEventImpl.get("lightning_strike");

    // Calls a method
    GameEvent NOTE_BLOCK_PLAY = GameEventImpl.get("note_block_play");

    // Calls a method
    GameEvent PRIME_FUSE = GameEventImpl.get("prime_fuse");

    // Calls a method
    GameEvent PROJECTILE_LAND = GameEventImpl.get("projectile_land");

    // Calls a method
    GameEvent PROJECTILE_SHOOT = GameEventImpl.get("projectile_shoot");

    // Calls a method
    GameEvent SCULK_SENSOR_TENDRILS_CLICKING = GameEventImpl.get("sculk_sensor_tendrils_clicking");

    // Calls a method
    GameEvent SHEAR = GameEventImpl.get("shear");

    // Calls a method
    GameEvent SHRIEK = GameEventImpl.get("shriek");

    // Calls a method
    GameEvent SPLASH = GameEventImpl.get("splash");

    // Calls a method
    GameEvent STEP = GameEventImpl.get("step");

    // Calls a method
    GameEvent SWIM = GameEventImpl.get("swim");

    // Calls a method
    GameEvent TELEPORT = GameEventImpl.get("teleport");

    // Calls a method
    GameEvent UNEQUIP = GameEventImpl.get("unequip");

    // Calls a method
    GameEvent RESONATE_1 = GameEventImpl.get("resonate_1");

    // Calls a method
    GameEvent RESONATE_2 = GameEventImpl.get("resonate_2");

    // Calls a method
    GameEvent RESONATE_3 = GameEventImpl.get("resonate_3");

    // Calls a method
    GameEvent RESONATE_4 = GameEventImpl.get("resonate_4");

    // Calls a method
    GameEvent RESONATE_5 = GameEventImpl.get("resonate_5");

    // Calls a method
    GameEvent RESONATE_6 = GameEventImpl.get("resonate_6");

    // Calls a method
    GameEvent RESONATE_7 = GameEventImpl.get("resonate_7");

    // Calls a method
    GameEvent RESONATE_8 = GameEventImpl.get("resonate_8");

    // Calls a method
    GameEvent RESONATE_9 = GameEventImpl.get("resonate_9");

    // Calls a method
    GameEvent RESONATE_10 = GameEventImpl.get("resonate_10");

    // Calls a method
    GameEvent RESONATE_11 = GameEventImpl.get("resonate_11");

    // Calls a method
    GameEvent RESONATE_12 = GameEventImpl.get("resonate_12");

    // Calls a method
    GameEvent RESONATE_13 = GameEventImpl.get("resonate_13");

    // Calls a method
    GameEvent RESONATE_14 = GameEventImpl.get("resonate_14");

    // Calls a method
    GameEvent RESONATE_15 = GameEventImpl.get("resonate_15");
// End of a block/expression
}
