// Package declaration for this file
package net.minestom.server.item.enchant;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link Enchantment}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface Enchantments permits Enchantment {
    // Calls a method
    RegistryKey<Enchantment> VANISHING_CURSE = RegistryKey.unsafeOf("vanishing_curse");

    // Calls a method
    RegistryKey<Enchantment> DEPTH_STRIDER = RegistryKey.unsafeOf("depth_strider");

    // Calls a method
    RegistryKey<Enchantment> EFFICIENCY = RegistryKey.unsafeOf("efficiency");

    // Calls a method
    RegistryKey<Enchantment> IMPALING = RegistryKey.unsafeOf("impaling");

    // Calls a method
    RegistryKey<Enchantment> WIND_BURST = RegistryKey.unsafeOf("wind_burst");

    // Calls a method
    RegistryKey<Enchantment> BANE_OF_ARTHROPODS = RegistryKey.unsafeOf("bane_of_arthropods");

    // Calls a method
    RegistryKey<Enchantment> BINDING_CURSE = RegistryKey.unsafeOf("binding_curse");

    // Calls a method
    RegistryKey<Enchantment> PUNCH = RegistryKey.unsafeOf("punch");

    // Calls a method
    RegistryKey<Enchantment> RIPTIDE = RegistryKey.unsafeOf("riptide");

    // Calls a method
    RegistryKey<Enchantment> FLAME = RegistryKey.unsafeOf("flame");

    // Calls a method
    RegistryKey<Enchantment> BLAST_PROTECTION = RegistryKey.unsafeOf("blast_protection");

    // Calls a method
    RegistryKey<Enchantment> PROTECTION = RegistryKey.unsafeOf("protection");

    // Calls a method
    RegistryKey<Enchantment> FROST_WALKER = RegistryKey.unsafeOf("frost_walker");

    // Calls a method
    RegistryKey<Enchantment> FIRE_ASPECT = RegistryKey.unsafeOf("fire_aspect");

    // Calls a method
    RegistryKey<Enchantment> SWEEPING_EDGE = RegistryKey.unsafeOf("sweeping_edge");

    // Calls a method
    RegistryKey<Enchantment> LOYALTY = RegistryKey.unsafeOf("loyalty");

    // Calls a method
    RegistryKey<Enchantment> RESPIRATION = RegistryKey.unsafeOf("respiration");

    // Calls a method
    RegistryKey<Enchantment> QUICK_CHARGE = RegistryKey.unsafeOf("quick_charge");

    // Calls a method
    RegistryKey<Enchantment> FIRE_PROTECTION = RegistryKey.unsafeOf("fire_protection");

    // Calls a method
    RegistryKey<Enchantment> LUCK_OF_THE_SEA = RegistryKey.unsafeOf("luck_of_the_sea");

    // Calls a method
    RegistryKey<Enchantment> SOUL_SPEED = RegistryKey.unsafeOf("soul_speed");

    // Calls a method
    RegistryKey<Enchantment> POWER = RegistryKey.unsafeOf("power");

    // Calls a method
    RegistryKey<Enchantment> DENSITY = RegistryKey.unsafeOf("density");

    // Calls a method
    RegistryKey<Enchantment> SILK_TOUCH = RegistryKey.unsafeOf("silk_touch");

    // Calls a method
    RegistryKey<Enchantment> CHANNELING = RegistryKey.unsafeOf("channeling");

    // Calls a method
    RegistryKey<Enchantment> LOOTING = RegistryKey.unsafeOf("looting");

    // Calls a method
    RegistryKey<Enchantment> FORTUNE = RegistryKey.unsafeOf("fortune");

    // Calls a method
    RegistryKey<Enchantment> BREACH = RegistryKey.unsafeOf("breach");

    // Calls a method
    RegistryKey<Enchantment> PIERCING = RegistryKey.unsafeOf("piercing");

    // Calls a method
    RegistryKey<Enchantment> LUNGE = RegistryKey.unsafeOf("lunge");

    // Calls a method
    RegistryKey<Enchantment> MENDING = RegistryKey.unsafeOf("mending");

    // Calls a method
    RegistryKey<Enchantment> SHARPNESS = RegistryKey.unsafeOf("sharpness");

    // Calls a method
    RegistryKey<Enchantment> FEATHER_FALLING = RegistryKey.unsafeOf("feather_falling");

    // Calls a method
    RegistryKey<Enchantment> KNOCKBACK = RegistryKey.unsafeOf("knockback");

    // Calls a method
    RegistryKey<Enchantment> SMITE = RegistryKey.unsafeOf("smite");

    // Calls a method
    RegistryKey<Enchantment> PROJECTILE_PROTECTION = RegistryKey.unsafeOf("projectile_protection");

    // Calls a method
    RegistryKey<Enchantment> INFINITY = RegistryKey.unsafeOf("infinity");

    // Calls a method
    RegistryKey<Enchantment> THORNS = RegistryKey.unsafeOf("thorns");

    // Calls a method
    RegistryKey<Enchantment> MULTISHOT = RegistryKey.unsafeOf("multishot");

    // Calls a method
    RegistryKey<Enchantment> LURE = RegistryKey.unsafeOf("lure");

    // Calls a method
    RegistryKey<Enchantment> AQUA_AFFINITY = RegistryKey.unsafeOf("aqua_affinity");

    // Calls a method
    RegistryKey<Enchantment> SWIFT_SNEAK = RegistryKey.unsafeOf("swift_sneak");

    // Calls a method
    RegistryKey<Enchantment> UNBREAKING = RegistryKey.unsafeOf("unbreaking");
// End of a block/expression
}
