// Package declaration for this file
package net.minestom.server.instance.fluid;

/**
 * This class contains all the generated constants for {@link Fluid}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface Fluids permits Fluid {
    // Calls a method
    Fluid EMPTY = FluidImpl.get("empty");

    // Calls a method
    Fluid FLOWING_WATER = FluidImpl.get("flowing_water");

    // Calls a method
    Fluid WATER = FluidImpl.get("water");

    // Calls a method
    Fluid FLOWING_LAVA = FluidImpl.get("flowing_lava");

    // Calls a method
    Fluid LAVA = FluidImpl.get("lava");
// End of a block/expression
}
