// Déclaration du paquet de ce fichier
package net.minestom.server.instance.fluid;

/**
 * This class contains all the generated constants for {@link Fluid}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface Fluids permits Fluid {
    // Appelle une méthode
    Fluid EMPTY = FluidImpl.get("empty");

    // Appelle une méthode
    Fluid FLOWING_WATER = FluidImpl.get("flowing_water");

    // Appelle une méthode
    Fluid WATER = FluidImpl.get("water");

    // Appelle une méthode
    Fluid FLOWING_LAVA = FluidImpl.get("flowing_lava");

    // Appelle une méthode
    Fluid LAVA = FluidImpl.get("lava");
// Fin d'un bloc/d'une expression
}
