// Déclaration du paquet de ce fichier
package net.minestom.server.world.timeline;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link Timeline}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface Timelines permits Timeline {
    // Appelle une méthode
    RegistryKey<Timeline> VILLAGER_SCHEDULE = RegistryKey.unsafeOf("villager_schedule");

    // Appelle une méthode
    RegistryKey<Timeline> EARLY_GAME = RegistryKey.unsafeOf("early_game");

    // Appelle une méthode
    RegistryKey<Timeline> DAY = RegistryKey.unsafeOf("day");

    // Appelle une méthode
    RegistryKey<Timeline> MOON = RegistryKey.unsafeOf("moon");
// Fin d'un bloc/d'une expression
}
