// Package declaration for this file
package net.minestom.server.world.timeline;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link Timeline}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface Timelines permits Timeline {
    // Calls a method
    RegistryKey<Timeline> VILLAGER_SCHEDULE = RegistryKey.unsafeOf("villager_schedule");

    // Calls a method
    RegistryKey<Timeline> EARLY_GAME = RegistryKey.unsafeOf("early_game");

    // Calls a method
    RegistryKey<Timeline> DAY = RegistryKey.unsafeOf("day");

    // Calls a method
    RegistryKey<Timeline> MOON = RegistryKey.unsafeOf("moon");
// End of a block/expression
}
