// Déclaration du paquet de ce fichier
package net.minestom.server.message;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link ChatType}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface ChatTypes permits ChatType {
    // Appelle une méthode
    RegistryKey<ChatType> EMOTE_COMMAND = RegistryKey.unsafeOf("emote_command");

    // Appelle une méthode
    RegistryKey<ChatType> TEAM_MSG_COMMAND_INCOMING = RegistryKey.unsafeOf("team_msg_command_incoming");

    // Appelle une méthode
    RegistryKey<ChatType> TEAM_MSG_COMMAND_OUTGOING = RegistryKey.unsafeOf("team_msg_command_outgoing");

    // Appelle une méthode
    RegistryKey<ChatType> CHAT = RegistryKey.unsafeOf("chat");

    // Appelle une méthode
    RegistryKey<ChatType> MSG_COMMAND_INCOMING = RegistryKey.unsafeOf("msg_command_incoming");

    // Appelle une méthode
    RegistryKey<ChatType> MSG_COMMAND_OUTGOING = RegistryKey.unsafeOf("msg_command_outgoing");

    // Appelle une méthode
    RegistryKey<ChatType> SAY_COMMAND = RegistryKey.unsafeOf("say_command");
// Fin d'un bloc/d'une expression
}
