// Package declaration for this file
package net.minestom.server.message;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link ChatType}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface ChatTypes permits ChatType {
    // Calls a method
    RegistryKey<ChatType> EMOTE_COMMAND = RegistryKey.unsafeOf("emote_command");

    // Calls a method
    RegistryKey<ChatType> TEAM_MSG_COMMAND_INCOMING = RegistryKey.unsafeOf("team_msg_command_incoming");

    // Calls a method
    RegistryKey<ChatType> TEAM_MSG_COMMAND_OUTGOING = RegistryKey.unsafeOf("team_msg_command_outgoing");

    // Calls a method
    RegistryKey<ChatType> CHAT = RegistryKey.unsafeOf("chat");

    // Calls a method
    RegistryKey<ChatType> MSG_COMMAND_INCOMING = RegistryKey.unsafeOf("msg_command_incoming");

    // Calls a method
    RegistryKey<ChatType> MSG_COMMAND_OUTGOING = RegistryKey.unsafeOf("msg_command_outgoing");

    // Calls a method
    RegistryKey<ChatType> SAY_COMMAND = RegistryKey.unsafeOf("say_command");
// End of a block/expression
}
