// Déclaration du paquet de ce fichier
package net.minestom.server.worldevent;

// Import d'une classe nécessaire
import net.minestom.server.network.NetworkBuffer;
// Import d'une classe nécessaire
import org.jetbrains.annotations.Nullable;

/**
 * AUTOGENERATED by WorldEventGenerator
 */
// Déclaration de type (classe/interface/enum/record)
public enum WorldEvent {
    // Instruction de code
    SOUND_DISPENSER_DISPENSE(1000),

    // Instruction de code
    SOUND_DISPENSER_FAIL(1001),

    // Instruction de code
    SOUND_DISPENSER_PROJECTILE_LAUNCH(1002),

    // Instruction de code
    SOUND_FIREWORK_SHOOT(1004),

    // Instruction de code
    SOUND_EXTINGUISH_FIRE(1009),

    // Instruction de code
    SOUND_PLAY_JUKEBOX_SONG(1010),

    // Instruction de code
    SOUND_STOP_JUKEBOX_SONG(1011),

    // Instruction de code
    SOUND_GHAST_WARNING(1015),

    // Instruction de code
    SOUND_GHAST_FIREBALL(1016),

    // Instruction de code
    SOUND_DRAGON_FIREBALL(1017),

    // Instruction de code
    SOUND_BLAZE_FIREBALL(1018),

    // Instruction de code
    SOUND_ZOMBIE_WOODEN_DOOR(1019),

    // Instruction de code
    SOUND_ZOMBIE_IRON_DOOR(1020),

    // Instruction de code
    SOUND_ZOMBIE_DOOR_CRASH(1021),

    // Instruction de code
    SOUND_WITHER_BLOCK_BREAK(1022),

    // Instruction de code
    SOUND_WITHER_BOSS_SPAWN(1023),

    // Instruction de code
    SOUND_WITHER_BOSS_SHOOT(1024),

    // Instruction de code
    SOUND_BAT_LIFTOFF(1025),

    // Instruction de code
    SOUND_ZOMBIE_INFECTED(1026),

    // Instruction de code
    SOUND_ZOMBIE_CONVERTED(1027),

    // Instruction de code
    SOUND_DRAGON_DEATH(1028),

    // Instruction de code
    SOUND_ANVIL_BROKEN(1029),

    // Instruction de code
    SOUND_ANVIL_USED(1030),

    // Instruction de code
    SOUND_ANVIL_LAND(1031),

    // Instruction de code
    SOUND_PORTAL_TRAVEL(1032),

    // Instruction de code
    SOUND_CHORUS_GROW(1033),

    // Instruction de code
    SOUND_CHORUS_DEATH(1034),

    // Instruction de code
    SOUND_BREWING_STAND_BREW(1035),

    // Instruction de code
    SOUND_END_PORTAL_SPAWN(1038),

    // Instruction de code
    SOUND_PHANTOM_BITE(1039),

    // Instruction de code
    SOUND_ZOMBIE_TO_DROWNED(1040),

    // Instruction de code
    SOUND_HUSK_TO_ZOMBIE(1041),

    // Instruction de code
    SOUND_GRINDSTONE_USED(1042),

    // Instruction de code
    SOUND_PAGE_TURN(1043),

    // Instruction de code
    SOUND_SMITHING_TABLE_USED(1044),

    // Instruction de code
    SOUND_POINTED_DRIPSTONE_LAND(1045),

    // Instruction de code
    SOUND_DRIP_LAVA_INTO_CAULDRON(1046),

    // Instruction de code
    SOUND_DRIP_WATER_INTO_CAULDRON(1047),

    // Instruction de code
    SOUND_SKELETON_TO_STRAY(1048),

    // Instruction de code
    SOUND_CRAFTER_CRAFT(1049),

    // Instruction de code
    SOUND_CRAFTER_FAIL(1050),

    // Instruction de code
    SOUND_WIND_CHARGE_SHOOT(1051),

    // Instruction de code
    COMPOSTER_FILL(1500),

    // Instruction de code
    LAVA_FIZZ(1501),

    // Instruction de code
    REDSTONE_TORCH_BURNOUT(1502),

    // Instruction de code
    END_PORTAL_FRAME_FILL(1503),

    // Instruction de code
    DRIPSTONE_DRIP(1504),

    // Instruction de code
    PARTICLES_AND_SOUND_PLANT_GROWTH(1505),

    // Instruction de code
    PARTICLES_SHOOT_SMOKE(2000),

    // Instruction de code
    PARTICLES_DESTROY_BLOCK(2001),

    // Instruction de code
    PARTICLES_SPELL_POTION_SPLASH(2002),

    // Instruction de code
    PARTICLES_EYE_OF_ENDER_DEATH(2003),

    // Instruction de code
    PARTICLES_MOBBLOCK_SPAWN(2004),

    // Instruction de code
    PARTICLES_DRAGON_FIREBALL_SPLASH(2006),

    // Instruction de code
    PARTICLES_INSTANT_POTION_SPLASH(2007),

    // Instruction de code
    PARTICLES_DRAGON_BLOCK_BREAK(2008),

    // Instruction de code
    PARTICLES_WATER_EVAPORATING(2009),

    // Instruction de code
    PARTICLES_SHOOT_WHITE_SMOKE(2010),

    // Instruction de code
    PARTICLES_BEE_GROWTH(2011),

    // Instruction de code
    PARTICLES_TURTLE_EGG_PLACEMENT(2012),

    // Instruction de code
    PARTICLES_SMASH_ATTACK(2013),

    // Instruction de code
    ANIMATION_END_GATEWAY_SPAWN(3000),

    // Instruction de code
    ANIMATION_DRAGON_SUMMON_ROAR(3001),

    // Instruction de code
    PARTICLES_ELECTRIC_SPARK(3002),

    // Instruction de code
    PARTICLES_AND_SOUND_WAX_ON(3003),

    // Instruction de code
    PARTICLES_WAX_OFF(3004),

    // Instruction de code
    PARTICLES_SCRAPE(3005),

    // Instruction de code
    PARTICLES_SCULK_CHARGE(3006),

    // Instruction de code
    PARTICLES_SCULK_SHRIEK(3007),

    // Instruction de code
    PARTICLES_AND_SOUND_BRUSH_BLOCK_COMPLETE(3008),

    // Instruction de code
    PARTICLES_EGG_CRACK(3009),

    // Instruction de code
    PARTICLES_TRIAL_SPAWNER_SPAWN(3011),

    // Instruction de code
    PARTICLES_TRIAL_SPAWNER_SPAWN_MOB_AT(3012),

    // Instruction de code
    PARTICLES_TRIAL_SPAWNER_DETECT_PLAYER(3013),

    // Instruction de code
    ANIMATION_TRIAL_SPAWNER_EJECT_ITEM(3014),

    // Instruction de code
    ANIMATION_VAULT_ACTIVATE(3015),

    // Instruction de code
    ANIMATION_VAULT_DEACTIVATE(3016),

    // Instruction de code
    ANIMATION_VAULT_EJECT_ITEM(3017),

    // Instruction de code
    ANIMATION_SPAWN_COBWEB(3018),

    // Instruction de code
    PARTICLES_TRIAL_SPAWNER_DETECT_PLAYER_OMINOUS(3019),

    // Instruction de code
    PARTICLES_TRIAL_SPAWNER_BECOME_OMINOUS(3020),

    // Appelle une méthode
    PARTICLES_TRIAL_SPAWNER_SPAWN_ITEM(3021);

    // Appelle une méthode
    public static final NetworkBuffer.Type<WorldEvent> NETWORK_TYPE = NetworkBuffer.VAR_INT.transform(WorldEvent::fromId, WorldEvent::id);

    // Appelle une méthode
    private static final WorldEvent[] VALUES = values();

    // Instruction de code
    private final int eventId;

    // Début d'une méthode/d'un bloc
    WorldEvent(int eventId) {
        // Accès à l'objet courant/parent
        this.eventId = eventId;
    // Fin d'un bloc/d'une expression
    }

    // Début d'une méthode/d'un bloc
    public int id() {
        // Renvoie une valeur à l'appelant
        return this.eventId;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Nullable
    // Début d'une méthode/d'un bloc
    public static WorldEvent fromId(int id) {
        // Boucle : répète un bloc
        for (WorldEvent event : VALUES) {
            // Embranchement : vérifie une condition
            if (event.id() == id) {
                // Renvoie une valeur à l'appelant
                return event;
            // Fin d'un bloc/d'une expression
            }
        // Fin d'un bloc/d'une expression
        }
        // Renvoie une valeur à l'appelant
        return null;
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
