// Déclaration du paquet de ce fichier
package net.minestom.server.item.component;

// Import d'une classe nécessaire
import java.util.Arrays;
// Import d'une classe nécessaire
import java.util.Map;
// Import d'une classe nécessaire
import java.util.function.Function;
// Import d'une classe nécessaire
import java.util.stream.Collectors;
// Import d'une classe nécessaire
import net.kyori.adventure.key.Key;
// Import d'une classe nécessaire
import net.minestom.server.codec.Codec;
// Import d'une classe nécessaire
import net.minestom.server.network.NetworkBuffer;
// Import d'une classe nécessaire
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Déclaration de type (classe/interface/enum/record)
enum ConsumeEffectType implements StaticProtocolObject<ConsumeEffectType> {
    // Instruction de code
    APPLY_EFFECTS("apply_effects"),

    // Instruction de code
    REMOVE_EFFECTS("remove_effects"),

    // Instruction de code
    CLEAR_ALL_EFFECTS("clear_all_effects"),

    // Instruction de code
    TELEPORT_RANDOMLY("teleport_randomly"),

    // Appelle une méthode
    PLAY_SOUND("play_sound");

    // Appelle une méthode
    private static final Map<Key, ConsumeEffectType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(ConsumeEffectType::key, Function.identity()));

    // Appelle une méthode
    public static final NetworkBuffer.Type<ConsumeEffectType> NETWORK_TYPE = NetworkBuffer.Enum(ConsumeEffectType.class);

    // Appelle une méthode
    public static final Codec<ConsumeEffectType> CODEC = Codec.KEY.transform(BY_KEY::get, ConsumeEffectType::key);

    // Instruction de code
    private final Key key;

    // Début d'une méthode/d'un bloc
    ConsumeEffectType(String key) {
        // Accès à l'objet courant/parent
        this.key = Key.key(key);
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public Key key() {
        // Renvoie une valeur à l'appelant
        return this.key;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public int id() {
        // Renvoie une valeur à l'appelant
        return this.ordinal();
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
