// Package declaration for this file
package net.minestom.server.item.component;

// Import of a required class
import java.util.Arrays;
// Import of a required class
import java.util.Map;
// Import of a required class
import java.util.function.Function;
// Import of a required class
import java.util.stream.Collectors;
// Import of a required class
import net.kyori.adventure.key.Key;
// Import of a required class
import net.minestom.server.codec.Codec;
// Import of a required class
import net.minestom.server.network.NetworkBuffer;
// Import of a required class
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Type declaration (class/interface/enum/record)
enum ConsumeEffectType implements StaticProtocolObject<ConsumeEffectType> {
    // Code statement
    APPLY_EFFECTS("apply_effects"),

    // Code statement
    REMOVE_EFFECTS("remove_effects"),

    // Code statement
    CLEAR_ALL_EFFECTS("clear_all_effects"),

    // Code statement
    TELEPORT_RANDOMLY("teleport_randomly"),

    // Calls a method
    PLAY_SOUND("play_sound");

    // Calls a method
    private static final Map<Key, ConsumeEffectType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(ConsumeEffectType::key, Function.identity()));

    // Calls a method
    public static final NetworkBuffer.Type<ConsumeEffectType> NETWORK_TYPE = NetworkBuffer.Enum(ConsumeEffectType.class);

    // Calls a method
    public static final Codec<ConsumeEffectType> CODEC = Codec.KEY.transform(BY_KEY::get, ConsumeEffectType::key);

    // Code statement
    private final Key key;

    // Start of a method/block
    ConsumeEffectType(String key) {
        // Access to the current/parent object
        this.key = Key.key(key);
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public Key key() {
        // Returns a value to the caller
        return this.key;
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public int id() {
        // Returns a value to the caller
        return this.ordinal();
    // End of a block/expression
    }
// End of a block/expression
}
