// Déclaration du paquet de ce fichier
package net.minestom.server.potion;

/**
 * This class contains all the generated constants for {@link PotionType}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface PotionTypes permits PotionType {
    // Appelle une méthode
    PotionType WATER = PotionTypeImpl.get("water");

    // Appelle une méthode
    PotionType MUNDANE = PotionTypeImpl.get("mundane");

    // Appelle une méthode
    PotionType THICK = PotionTypeImpl.get("thick");

    // Appelle une méthode
    PotionType AWKWARD = PotionTypeImpl.get("awkward");

    // Appelle une méthode
    PotionType NIGHT_VISION = PotionTypeImpl.get("night_vision");

    // Appelle une méthode
    PotionType LONG_NIGHT_VISION = PotionTypeImpl.get("long_night_vision");

    // Appelle une méthode
    PotionType INVISIBILITY = PotionTypeImpl.get("invisibility");

    // Appelle une méthode
    PotionType LONG_INVISIBILITY = PotionTypeImpl.get("long_invisibility");

    // Appelle une méthode
    PotionType LEAPING = PotionTypeImpl.get("leaping");

    // Appelle une méthode
    PotionType LONG_LEAPING = PotionTypeImpl.get("long_leaping");

    // Appelle une méthode
    PotionType STRONG_LEAPING = PotionTypeImpl.get("strong_leaping");

    // Appelle une méthode
    PotionType FIRE_RESISTANCE = PotionTypeImpl.get("fire_resistance");

    // Appelle une méthode
    PotionType LONG_FIRE_RESISTANCE = PotionTypeImpl.get("long_fire_resistance");

    // Appelle une méthode
    PotionType SWIFTNESS = PotionTypeImpl.get("swiftness");

    // Appelle une méthode
    PotionType LONG_SWIFTNESS = PotionTypeImpl.get("long_swiftness");

    // Appelle une méthode
    PotionType STRONG_SWIFTNESS = PotionTypeImpl.get("strong_swiftness");

    // Appelle une méthode
    PotionType SLOWNESS = PotionTypeImpl.get("slowness");

    // Appelle une méthode
    PotionType LONG_SLOWNESS = PotionTypeImpl.get("long_slowness");

    // Appelle une méthode
    PotionType STRONG_SLOWNESS = PotionTypeImpl.get("strong_slowness");

    // Appelle une méthode
    PotionType TURTLE_MASTER = PotionTypeImpl.get("turtle_master");

    // Appelle une méthode
    PotionType LONG_TURTLE_MASTER = PotionTypeImpl.get("long_turtle_master");

    // Appelle une méthode
    PotionType STRONG_TURTLE_MASTER = PotionTypeImpl.get("strong_turtle_master");

    // Appelle une méthode
    PotionType WATER_BREATHING = PotionTypeImpl.get("water_breathing");

    // Appelle une méthode
    PotionType LONG_WATER_BREATHING = PotionTypeImpl.get("long_water_breathing");

    // Appelle une méthode
    PotionType HEALING = PotionTypeImpl.get("healing");

    // Appelle une méthode
    PotionType STRONG_HEALING = PotionTypeImpl.get("strong_healing");

    // Appelle une méthode
    PotionType HARMING = PotionTypeImpl.get("harming");

    // Appelle une méthode
    PotionType STRONG_HARMING = PotionTypeImpl.get("strong_harming");

    // Appelle une méthode
    PotionType POISON = PotionTypeImpl.get("poison");

    // Appelle une méthode
    PotionType LONG_POISON = PotionTypeImpl.get("long_poison");

    // Appelle une méthode
    PotionType STRONG_POISON = PotionTypeImpl.get("strong_poison");

    // Appelle une méthode
    PotionType REGENERATION = PotionTypeImpl.get("regeneration");

    // Appelle une méthode
    PotionType LONG_REGENERATION = PotionTypeImpl.get("long_regeneration");

    // Appelle une méthode
    PotionType STRONG_REGENERATION = PotionTypeImpl.get("strong_regeneration");

    // Appelle une méthode
    PotionType STRENGTH = PotionTypeImpl.get("strength");

    // Appelle une méthode
    PotionType LONG_STRENGTH = PotionTypeImpl.get("long_strength");

    // Appelle une méthode
    PotionType STRONG_STRENGTH = PotionTypeImpl.get("strong_strength");

    // Appelle une méthode
    PotionType WEAKNESS = PotionTypeImpl.get("weakness");

    // Appelle une méthode
    PotionType LONG_WEAKNESS = PotionTypeImpl.get("long_weakness");

    // Appelle une méthode
    PotionType LUCK = PotionTypeImpl.get("luck");

    // Appelle une méthode
    PotionType SLOW_FALLING = PotionTypeImpl.get("slow_falling");

    // Appelle une méthode
    PotionType LONG_SLOW_FALLING = PotionTypeImpl.get("long_slow_falling");

    // Appelle une méthode
    PotionType WIND_CHARGED = PotionTypeImpl.get("wind_charged");

    // Appelle une méthode
    PotionType WEAVING = PotionTypeImpl.get("weaving");

    // Appelle une méthode
    PotionType OOZING = PotionTypeImpl.get("oozing");

    // Appelle une méthode
    PotionType INFESTED = PotionTypeImpl.get("infested");
// Fin d'un bloc/d'une expression
}
