// Déclaration du paquet de ce fichier
package net.minestom.server.potion;

/**
 * This class contains all the generated constants for {@link PotionEffect}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface PotionEffects permits PotionEffect {
    // Appelle une méthode
    PotionEffect SPEED = PotionEffectImpl.get("speed");

    // Appelle une méthode
    PotionEffect SLOWNESS = PotionEffectImpl.get("slowness");

    // Appelle une méthode
    PotionEffect HASTE = PotionEffectImpl.get("haste");

    // Appelle une méthode
    PotionEffect MINING_FATIGUE = PotionEffectImpl.get("mining_fatigue");

    // Appelle une méthode
    PotionEffect STRENGTH = PotionEffectImpl.get("strength");

    // Appelle une méthode
    PotionEffect INSTANT_HEALTH = PotionEffectImpl.get("instant_health");

    // Appelle une méthode
    PotionEffect INSTANT_DAMAGE = PotionEffectImpl.get("instant_damage");

    // Appelle une méthode
    PotionEffect JUMP_BOOST = PotionEffectImpl.get("jump_boost");

    // Appelle une méthode
    PotionEffect NAUSEA = PotionEffectImpl.get("nausea");

    // Appelle une méthode
    PotionEffect REGENERATION = PotionEffectImpl.get("regeneration");

    // Appelle une méthode
    PotionEffect RESISTANCE = PotionEffectImpl.get("resistance");

    // Appelle une méthode
    PotionEffect FIRE_RESISTANCE = PotionEffectImpl.get("fire_resistance");

    // Appelle une méthode
    PotionEffect WATER_BREATHING = PotionEffectImpl.get("water_breathing");

    // Appelle une méthode
    PotionEffect INVISIBILITY = PotionEffectImpl.get("invisibility");

    // Appelle une méthode
    PotionEffect BLINDNESS = PotionEffectImpl.get("blindness");

    // Appelle une méthode
    PotionEffect NIGHT_VISION = PotionEffectImpl.get("night_vision");

    // Appelle une méthode
    PotionEffect HUNGER = PotionEffectImpl.get("hunger");

    // Appelle une méthode
    PotionEffect WEAKNESS = PotionEffectImpl.get("weakness");

    // Appelle une méthode
    PotionEffect POISON = PotionEffectImpl.get("poison");

    // Appelle une méthode
    PotionEffect WITHER = PotionEffectImpl.get("wither");

    // Appelle une méthode
    PotionEffect HEALTH_BOOST = PotionEffectImpl.get("health_boost");

    // Appelle une méthode
    PotionEffect ABSORPTION = PotionEffectImpl.get("absorption");

    // Appelle une méthode
    PotionEffect SATURATION = PotionEffectImpl.get("saturation");

    // Appelle une méthode
    PotionEffect GLOWING = PotionEffectImpl.get("glowing");

    // Appelle une méthode
    PotionEffect LEVITATION = PotionEffectImpl.get("levitation");

    // Appelle une méthode
    PotionEffect LUCK = PotionEffectImpl.get("luck");

    // Appelle une méthode
    PotionEffect UNLUCK = PotionEffectImpl.get("unluck");

    // Appelle une méthode
    PotionEffect SLOW_FALLING = PotionEffectImpl.get("slow_falling");

    // Appelle une méthode
    PotionEffect CONDUIT_POWER = PotionEffectImpl.get("conduit_power");

    // Appelle une méthode
    PotionEffect DOLPHINS_GRACE = PotionEffectImpl.get("dolphins_grace");

    // Appelle une méthode
    PotionEffect BAD_OMEN = PotionEffectImpl.get("bad_omen");

    // Appelle une méthode
    PotionEffect HERO_OF_THE_VILLAGE = PotionEffectImpl.get("hero_of_the_village");

    // Appelle une méthode
    PotionEffect DARKNESS = PotionEffectImpl.get("darkness");

    // Appelle une méthode
    PotionEffect TRIAL_OMEN = PotionEffectImpl.get("trial_omen");

    // Appelle une méthode
    PotionEffect RAID_OMEN = PotionEffectImpl.get("raid_omen");

    // Appelle une méthode
    PotionEffect WIND_CHARGED = PotionEffectImpl.get("wind_charged");

    // Appelle une méthode
    PotionEffect WEAVING = PotionEffectImpl.get("weaving");

    // Appelle une méthode
    PotionEffect OOZING = PotionEffectImpl.get("oozing");

    // Appelle une méthode
    PotionEffect INFESTED = PotionEffectImpl.get("infested");

    // Appelle une méthode
    PotionEffect BREATH_OF_THE_NAUTILUS = PotionEffectImpl.get("breath_of_the_nautilus");
// Fin d'un bloc/d'une expression
}
