// Package declaration for this file
package net.minestom.server.potion;

/**
 * This class contains all the generated constants for {@link PotionEffect}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface PotionEffects permits PotionEffect {
    // Calls a method
    PotionEffect SPEED = PotionEffectImpl.get("speed");

    // Calls a method
    PotionEffect SLOWNESS = PotionEffectImpl.get("slowness");

    // Calls a method
    PotionEffect HASTE = PotionEffectImpl.get("haste");

    // Calls a method
    PotionEffect MINING_FATIGUE = PotionEffectImpl.get("mining_fatigue");

    // Calls a method
    PotionEffect STRENGTH = PotionEffectImpl.get("strength");

    // Calls a method
    PotionEffect INSTANT_HEALTH = PotionEffectImpl.get("instant_health");

    // Calls a method
    PotionEffect INSTANT_DAMAGE = PotionEffectImpl.get("instant_damage");

    // Calls a method
    PotionEffect JUMP_BOOST = PotionEffectImpl.get("jump_boost");

    // Calls a method
    PotionEffect NAUSEA = PotionEffectImpl.get("nausea");

    // Calls a method
    PotionEffect REGENERATION = PotionEffectImpl.get("regeneration");

    // Calls a method
    PotionEffect RESISTANCE = PotionEffectImpl.get("resistance");

    // Calls a method
    PotionEffect FIRE_RESISTANCE = PotionEffectImpl.get("fire_resistance");

    // Calls a method
    PotionEffect WATER_BREATHING = PotionEffectImpl.get("water_breathing");

    // Calls a method
    PotionEffect INVISIBILITY = PotionEffectImpl.get("invisibility");

    // Calls a method
    PotionEffect BLINDNESS = PotionEffectImpl.get("blindness");

    // Calls a method
    PotionEffect NIGHT_VISION = PotionEffectImpl.get("night_vision");

    // Calls a method
    PotionEffect HUNGER = PotionEffectImpl.get("hunger");

    // Calls a method
    PotionEffect WEAKNESS = PotionEffectImpl.get("weakness");

    // Calls a method
    PotionEffect POISON = PotionEffectImpl.get("poison");

    // Calls a method
    PotionEffect WITHER = PotionEffectImpl.get("wither");

    // Calls a method
    PotionEffect HEALTH_BOOST = PotionEffectImpl.get("health_boost");

    // Calls a method
    PotionEffect ABSORPTION = PotionEffectImpl.get("absorption");

    // Calls a method
    PotionEffect SATURATION = PotionEffectImpl.get("saturation");

    // Calls a method
    PotionEffect GLOWING = PotionEffectImpl.get("glowing");

    // Calls a method
    PotionEffect LEVITATION = PotionEffectImpl.get("levitation");

    // Calls a method
    PotionEffect LUCK = PotionEffectImpl.get("luck");

    // Calls a method
    PotionEffect UNLUCK = PotionEffectImpl.get("unluck");

    // Calls a method
    PotionEffect SLOW_FALLING = PotionEffectImpl.get("slow_falling");

    // Calls a method
    PotionEffect CONDUIT_POWER = PotionEffectImpl.get("conduit_power");

    // Calls a method
    PotionEffect DOLPHINS_GRACE = PotionEffectImpl.get("dolphins_grace");

    // Calls a method
    PotionEffect BAD_OMEN = PotionEffectImpl.get("bad_omen");

    // Calls a method
    PotionEffect HERO_OF_THE_VILLAGE = PotionEffectImpl.get("hero_of_the_village");

    // Calls a method
    PotionEffect DARKNESS = PotionEffectImpl.get("darkness");

    // Calls a method
    PotionEffect TRIAL_OMEN = PotionEffectImpl.get("trial_omen");

    // Calls a method
    PotionEffect RAID_OMEN = PotionEffectImpl.get("raid_omen");

    // Calls a method
    PotionEffect WIND_CHARGED = PotionEffectImpl.get("wind_charged");

    // Calls a method
    PotionEffect WEAVING = PotionEffectImpl.get("weaving");

    // Calls a method
    PotionEffect OOZING = PotionEffectImpl.get("oozing");

    // Calls a method
    PotionEffect INFESTED = PotionEffectImpl.get("infested");

    // Calls a method
    PotionEffect BREATH_OF_THE_NAUTILUS = PotionEffectImpl.get("breath_of_the_nautilus");
// End of a block/expression
}
