// Déclaration du paquet de ce fichier
package net.minestom.server.entity.attribute;

/**
 * This class contains all the generated constants for {@link Attribute}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface Attributes permits Attribute {
    // Appelle une méthode
    Attribute ARMOR = AttributeImpl.get("armor");

    // Appelle une méthode
    Attribute ARMOR_TOUGHNESS = AttributeImpl.get("armor_toughness");

    // Appelle une méthode
    Attribute ATTACK_DAMAGE = AttributeImpl.get("attack_damage");

    // Appelle une méthode
    Attribute ATTACK_KNOCKBACK = AttributeImpl.get("attack_knockback");

    // Appelle une méthode
    Attribute ATTACK_SPEED = AttributeImpl.get("attack_speed");

    // Appelle une méthode
    Attribute BLOCK_BREAK_SPEED = AttributeImpl.get("block_break_speed");

    // Appelle une méthode
    Attribute BLOCK_INTERACTION_RANGE = AttributeImpl.get("block_interaction_range");

    // Appelle une méthode
    Attribute BURNING_TIME = AttributeImpl.get("burning_time");

    // Appelle une méthode
    Attribute CAMERA_DISTANCE = AttributeImpl.get("camera_distance");

    // Appelle une méthode
    Attribute EXPLOSION_KNOCKBACK_RESISTANCE = AttributeImpl.get("explosion_knockback_resistance");

    // Appelle une méthode
    Attribute ENTITY_INTERACTION_RANGE = AttributeImpl.get("entity_interaction_range");

    // Appelle une méthode
    Attribute FALL_DAMAGE_MULTIPLIER = AttributeImpl.get("fall_damage_multiplier");

    // Appelle une méthode
    Attribute FLYING_SPEED = AttributeImpl.get("flying_speed");

    // Appelle une méthode
    Attribute FOLLOW_RANGE = AttributeImpl.get("follow_range");

    // Appelle une méthode
    Attribute GRAVITY = AttributeImpl.get("gravity");

    // Appelle une méthode
    Attribute JUMP_STRENGTH = AttributeImpl.get("jump_strength");

    // Appelle une méthode
    Attribute KNOCKBACK_RESISTANCE = AttributeImpl.get("knockback_resistance");

    // Appelle une méthode
    Attribute LUCK = AttributeImpl.get("luck");

    // Appelle une méthode
    Attribute MAX_ABSORPTION = AttributeImpl.get("max_absorption");

    // Appelle une méthode
    Attribute MAX_HEALTH = AttributeImpl.get("max_health");

    // Appelle une méthode
    Attribute MINING_EFFICIENCY = AttributeImpl.get("mining_efficiency");

    // Appelle une méthode
    Attribute MOVEMENT_EFFICIENCY = AttributeImpl.get("movement_efficiency");

    // Appelle une méthode
    Attribute MOVEMENT_SPEED = AttributeImpl.get("movement_speed");

    // Appelle une méthode
    Attribute OXYGEN_BONUS = AttributeImpl.get("oxygen_bonus");

    // Appelle une méthode
    Attribute SAFE_FALL_DISTANCE = AttributeImpl.get("safe_fall_distance");

    // Appelle une méthode
    Attribute SCALE = AttributeImpl.get("scale");

    // Appelle une méthode
    Attribute SNEAKING_SPEED = AttributeImpl.get("sneaking_speed");

    // Appelle une méthode
    Attribute SPAWN_REINFORCEMENTS = AttributeImpl.get("spawn_reinforcements");

    // Appelle une méthode
    Attribute STEP_HEIGHT = AttributeImpl.get("step_height");

    // Appelle une méthode
    Attribute SUBMERGED_MINING_SPEED = AttributeImpl.get("submerged_mining_speed");

    // Appelle une méthode
    Attribute SWEEPING_DAMAGE_RATIO = AttributeImpl.get("sweeping_damage_ratio");

    // Appelle une méthode
    Attribute TEMPT_RANGE = AttributeImpl.get("tempt_range");

    // Appelle une méthode
    Attribute WATER_MOVEMENT_EFFICIENCY = AttributeImpl.get("water_movement_efficiency");

    // Appelle une méthode
    Attribute WAYPOINT_TRANSMIT_RANGE = AttributeImpl.get("waypoint_transmit_range");

    // Appelle une méthode
    Attribute WAYPOINT_RECEIVE_RANGE = AttributeImpl.get("waypoint_receive_range");
// Fin d'un bloc/d'une expression
}
