// Package declaration for this file
package net.minestom.server.entity.attribute;

/**
 * This class contains all the generated constants for {@link Attribute}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface Attributes permits Attribute {
    // Calls a method
    Attribute ARMOR = AttributeImpl.get("armor");

    // Calls a method
    Attribute ARMOR_TOUGHNESS = AttributeImpl.get("armor_toughness");

    // Calls a method
    Attribute ATTACK_DAMAGE = AttributeImpl.get("attack_damage");

    // Calls a method
    Attribute ATTACK_KNOCKBACK = AttributeImpl.get("attack_knockback");

    // Calls a method
    Attribute ATTACK_SPEED = AttributeImpl.get("attack_speed");

    // Calls a method
    Attribute BLOCK_BREAK_SPEED = AttributeImpl.get("block_break_speed");

    // Calls a method
    Attribute BLOCK_INTERACTION_RANGE = AttributeImpl.get("block_interaction_range");

    // Calls a method
    Attribute BURNING_TIME = AttributeImpl.get("burning_time");

    // Calls a method
    Attribute CAMERA_DISTANCE = AttributeImpl.get("camera_distance");

    // Calls a method
    Attribute EXPLOSION_KNOCKBACK_RESISTANCE = AttributeImpl.get("explosion_knockback_resistance");

    // Calls a method
    Attribute ENTITY_INTERACTION_RANGE = AttributeImpl.get("entity_interaction_range");

    // Calls a method
    Attribute FALL_DAMAGE_MULTIPLIER = AttributeImpl.get("fall_damage_multiplier");

    // Calls a method
    Attribute FLYING_SPEED = AttributeImpl.get("flying_speed");

    // Calls a method
    Attribute FOLLOW_RANGE = AttributeImpl.get("follow_range");

    // Calls a method
    Attribute GRAVITY = AttributeImpl.get("gravity");

    // Calls a method
    Attribute JUMP_STRENGTH = AttributeImpl.get("jump_strength");

    // Calls a method
    Attribute KNOCKBACK_RESISTANCE = AttributeImpl.get("knockback_resistance");

    // Calls a method
    Attribute LUCK = AttributeImpl.get("luck");

    // Calls a method
    Attribute MAX_ABSORPTION = AttributeImpl.get("max_absorption");

    // Calls a method
    Attribute MAX_HEALTH = AttributeImpl.get("max_health");

    // Calls a method
    Attribute MINING_EFFICIENCY = AttributeImpl.get("mining_efficiency");

    // Calls a method
    Attribute MOVEMENT_EFFICIENCY = AttributeImpl.get("movement_efficiency");

    // Calls a method
    Attribute MOVEMENT_SPEED = AttributeImpl.get("movement_speed");

    // Calls a method
    Attribute OXYGEN_BONUS = AttributeImpl.get("oxygen_bonus");

    // Calls a method
    Attribute SAFE_FALL_DISTANCE = AttributeImpl.get("safe_fall_distance");

    // Calls a method
    Attribute SCALE = AttributeImpl.get("scale");

    // Calls a method
    Attribute SNEAKING_SPEED = AttributeImpl.get("sneaking_speed");

    // Calls a method
    Attribute SPAWN_REINFORCEMENTS = AttributeImpl.get("spawn_reinforcements");

    // Calls a method
    Attribute STEP_HEIGHT = AttributeImpl.get("step_height");

    // Calls a method
    Attribute SUBMERGED_MINING_SPEED = AttributeImpl.get("submerged_mining_speed");

    // Calls a method
    Attribute SWEEPING_DAMAGE_RATIO = AttributeImpl.get("sweeping_damage_ratio");

    // Calls a method
    Attribute TEMPT_RANGE = AttributeImpl.get("tempt_range");

    // Calls a method
    Attribute WATER_MOVEMENT_EFFICIENCY = AttributeImpl.get("water_movement_efficiency");

    // Calls a method
    Attribute WAYPOINT_TRANSMIT_RANGE = AttributeImpl.get("waypoint_transmit_range");

    // Calls a method
    Attribute WAYPOINT_RECEIVE_RANGE = AttributeImpl.get("waypoint_receive_range");
// End of a block/expression
}
