// Déclaration du paquet de ce fichier
package net.minestom.server;

/**
 * This class contains all the generated constants for {@link FeatureFlag}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface FeatureFlags permits FeatureFlag {
    // Appelle une méthode
    FeatureFlag REDSTONE_EXPERIMENTS = FeatureFlagImpl.get("redstone_experiments");

    // Appelle une méthode
    FeatureFlag VANILLA = FeatureFlagImpl.get("vanilla");

    // Appelle une méthode
    FeatureFlag TRADE_REBALANCE = FeatureFlagImpl.get("trade_rebalance");

    // Appelle une méthode
    FeatureFlag MINECART_IMPROVEMENTS = FeatureFlagImpl.get("minecart_improvements");
// Fin d'un bloc/d'une expression
}
