// Package declaration for this file
package net.minestom.server;

/**
 * This class contains all the generated constants for {@link FeatureFlag}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface FeatureFlags permits FeatureFlag {
    // Calls a method
    FeatureFlag REDSTONE_EXPERIMENTS = FeatureFlagImpl.get("redstone_experiments");

    // Calls a method
    FeatureFlag VANILLA = FeatureFlagImpl.get("vanilla");

    // Calls a method
    FeatureFlag TRADE_REBALANCE = FeatureFlagImpl.get("trade_rebalance");

    // Calls a method
    FeatureFlag MINECART_IMPROVEMENTS = FeatureFlagImpl.get("minecart_improvements");
// End of a block/expression
}
