// Déclaration du paquet de ce fichier
package net.minestom.server;

// Import d'une classe nécessaire
import net.minestom.server.utils.MajorMinorVersion;

/**
 * This class contains all the generated constants for {@link MinecraftServer}
 * <br>
 * Code autogenerated, do not edit!
 */
// Déclaration de type (classe/interface/enum/record)
sealed interface MinecraftConstants permits MinecraftServer {
    // Affecte une valeur
    String VERSION_NAME = "26.1.2";

    // Affecte une valeur
    int PROTOCOL_VERSION = 775;

    // Affecte une valeur
    int DATA_VERSION = 4790;

    // Appelle une méthode
    MajorMinorVersion RESOURCE_PACK_VERSION = new MajorMinorVersion(84, 0);

    // Appelle une méthode
    MajorMinorVersion DATA_PACK_VERSION = new MajorMinorVersion(101, 1);
// Fin d'un bloc/d'une expression
}
