// Package declaration for this file
package net.minestom.server;

// Import of a required class
import net.minestom.server.utils.MajorMinorVersion;

/**
 * This class contains all the generated constants for {@link MinecraftServer}
 * <br>
 * Code autogenerated, do not edit!
 */
// Type declaration (class/interface/enum/record)
sealed interface MinecraftConstants permits MinecraftServer {
    // Assigns a value
    String VERSION_NAME = "26.1.2";

    // Assigns a value
    int PROTOCOL_VERSION = 775;

    // Assigns a value
    int DATA_VERSION = 4790;

    // Calls a method
    MajorMinorVersion RESOURCE_PACK_VERSION = new MajorMinorVersion(84, 0);

    // Calls a method
    MajorMinorVersion DATA_PACK_VERSION = new MajorMinorVersion(101, 1);
// End of a block/expression
}
