// Déclaration du paquet de ce fichier
package net.minestom.server.item.armor;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link TrimPattern}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface TrimPatterns permits TrimPattern {
    // Appelle une méthode
    RegistryKey<TrimPattern> TIDE = RegistryKey.unsafeOf("tide");

    // Appelle une méthode
    RegistryKey<TrimPattern> RIB = RegistryKey.unsafeOf("rib");

    // Appelle une méthode
    RegistryKey<TrimPattern> BOLT = RegistryKey.unsafeOf("bolt");

    // Appelle une méthode
    RegistryKey<TrimPattern> HOST = RegistryKey.unsafeOf("host");

    // Appelle une méthode
    RegistryKey<TrimPattern> SILENCE = RegistryKey.unsafeOf("silence");

    // Appelle une méthode
    RegistryKey<TrimPattern> WILD = RegistryKey.unsafeOf("wild");

    // Appelle une méthode
    RegistryKey<TrimPattern> WAYFINDER = RegistryKey.unsafeOf("wayfinder");

    // Appelle une méthode
    RegistryKey<TrimPattern> FLOW = RegistryKey.unsafeOf("flow");

    // Appelle une méthode
    RegistryKey<TrimPattern> DUNE = RegistryKey.unsafeOf("dune");

    // Appelle une méthode
    RegistryKey<TrimPattern> RAISER = RegistryKey.unsafeOf("raiser");

    // Appelle une méthode
    RegistryKey<TrimPattern> SNOUT = RegistryKey.unsafeOf("snout");

    // Appelle une méthode
    RegistryKey<TrimPattern> VEX = RegistryKey.unsafeOf("vex");

    // Appelle une méthode
    RegistryKey<TrimPattern> SPIRE = RegistryKey.unsafeOf("spire");

    // Appelle une méthode
    RegistryKey<TrimPattern> SENTRY = RegistryKey.unsafeOf("sentry");

    // Appelle une méthode
    RegistryKey<TrimPattern> EYE = RegistryKey.unsafeOf("eye");

    // Appelle une méthode
    RegistryKey<TrimPattern> WARD = RegistryKey.unsafeOf("ward");

    // Appelle une méthode
    RegistryKey<TrimPattern> COAST = RegistryKey.unsafeOf("coast");

    // Appelle une méthode
    RegistryKey<TrimPattern> SHAPER = RegistryKey.unsafeOf("shaper");
// Fin d'un bloc/d'une expression
}
