// Déclaration du paquet de ce fichier
package net.minestom.server.item.armor;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link TrimMaterial}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface TrimMaterials permits TrimMaterial {
    // Appelle une méthode
    RegistryKey<TrimMaterial> LAPIS = RegistryKey.unsafeOf("lapis");

    // Appelle une méthode
    RegistryKey<TrimMaterial> IRON = RegistryKey.unsafeOf("iron");

    // Appelle une méthode
    RegistryKey<TrimMaterial> DIAMOND = RegistryKey.unsafeOf("diamond");

    // Appelle une méthode
    RegistryKey<TrimMaterial> AMETHYST = RegistryKey.unsafeOf("amethyst");

    // Appelle une méthode
    RegistryKey<TrimMaterial> COPPER = RegistryKey.unsafeOf("copper");

    // Appelle une méthode
    RegistryKey<TrimMaterial> QUARTZ = RegistryKey.unsafeOf("quartz");

    // Appelle une méthode
    RegistryKey<TrimMaterial> EMERALD = RegistryKey.unsafeOf("emerald");

    // Appelle une méthode
    RegistryKey<TrimMaterial> RESIN = RegistryKey.unsafeOf("resin");

    // Appelle une méthode
    RegistryKey<TrimMaterial> REDSTONE = RegistryKey.unsafeOf("redstone");

    // Appelle une méthode
    RegistryKey<TrimMaterial> GOLD = RegistryKey.unsafeOf("gold");

    // Appelle une méthode
    RegistryKey<TrimMaterial> NETHERITE = RegistryKey.unsafeOf("netherite");
// Fin d'un bloc/d'une expression
}
