// Package declaration for this file
package net.minestom.server.item.armor;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link TrimMaterial}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface TrimMaterials permits TrimMaterial {
    // Calls a method
    RegistryKey<TrimMaterial> LAPIS = RegistryKey.unsafeOf("lapis");

    // Calls a method
    RegistryKey<TrimMaterial> IRON = RegistryKey.unsafeOf("iron");

    // Calls a method
    RegistryKey<TrimMaterial> DIAMOND = RegistryKey.unsafeOf("diamond");

    // Calls a method
    RegistryKey<TrimMaterial> AMETHYST = RegistryKey.unsafeOf("amethyst");

    // Calls a method
    RegistryKey<TrimMaterial> QUARTZ = RegistryKey.unsafeOf("quartz");

    // Calls a method
    RegistryKey<TrimMaterial> COPPER = RegistryKey.unsafeOf("copper");

    // Calls a method
    RegistryKey<TrimMaterial> RESIN = RegistryKey.unsafeOf("resin");

    // Calls a method
    RegistryKey<TrimMaterial> EMERALD = RegistryKey.unsafeOf("emerald");

    // Calls a method
    RegistryKey<TrimMaterial> REDSTONE = RegistryKey.unsafeOf("redstone");

    // Calls a method
    RegistryKey<TrimMaterial> GOLD = RegistryKey.unsafeOf("gold");

    // Calls a method
    RegistryKey<TrimMaterial> NETHERITE = RegistryKey.unsafeOf("netherite");
// End of a block/expression
}
