// Package declaration for this file
package net.minestom.server.entity.damage;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link DamageType}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface DamageTypes permits DamageType {
    // Calls a method
    RegistryKey<DamageType> WITHER = RegistryKey.unsafeOf("wither");

    // Calls a method
    RegistryKey<DamageType> WITHER_SKULL = RegistryKey.unsafeOf("wither_skull");

    // Calls a method
    RegistryKey<DamageType> MACE_SMASH = RegistryKey.unsafeOf("mace_smash");

    // Calls a method
    RegistryKey<DamageType> TRIDENT = RegistryKey.unsafeOf("trident");

    // Calls a method
    RegistryKey<DamageType> ON_FIRE = RegistryKey.unsafeOf("on_fire");

    // Calls a method
    RegistryKey<DamageType> CAMPFIRE = RegistryKey.unsafeOf("campfire");

    // Calls a method
    RegistryKey<DamageType> FALLING_STALACTITE = RegistryKey.unsafeOf("falling_stalactite");

    // Calls a method
    RegistryKey<DamageType> FIREBALL = RegistryKey.unsafeOf("fireball");

    // Calls a method
    RegistryKey<DamageType> SPIT = RegistryKey.unsafeOf("spit");

    // Calls a method
    RegistryKey<DamageType> STING = RegistryKey.unsafeOf("sting");

    // Calls a method
    RegistryKey<DamageType> SPEAR = RegistryKey.unsafeOf("spear");

    // Calls a method
    RegistryKey<DamageType> IN_FIRE = RegistryKey.unsafeOf("in_fire");

    // Calls a method
    RegistryKey<DamageType> ARROW = RegistryKey.unsafeOf("arrow");

    // Calls a method
    RegistryKey<DamageType> HOT_FLOOR = RegistryKey.unsafeOf("hot_floor");

    // Calls a method
    RegistryKey<DamageType> DROWN = RegistryKey.unsafeOf("drown");

    // Calls a method
    RegistryKey<DamageType> GENERIC_KILL = RegistryKey.unsafeOf("generic_kill");

    // Calls a method
    RegistryKey<DamageType> DRAGON_BREATH = RegistryKey.unsafeOf("dragon_breath");

    // Calls a method
    RegistryKey<DamageType> LAVA = RegistryKey.unsafeOf("lava");

    // Calls a method
    RegistryKey<DamageType> FLY_INTO_WALL = RegistryKey.unsafeOf("fly_into_wall");

    // Calls a method
    RegistryKey<DamageType> PLAYER_ATTACK = RegistryKey.unsafeOf("player_attack");

    // Calls a method
    RegistryKey<DamageType> FREEZE = RegistryKey.unsafeOf("freeze");

    // Calls a method
    RegistryKey<DamageType> FALLING_ANVIL = RegistryKey.unsafeOf("falling_anvil");

    // Calls a method
    RegistryKey<DamageType> SWEET_BERRY_BUSH = RegistryKey.unsafeOf("sweet_berry_bush");

    // Calls a method
    RegistryKey<DamageType> FIREWORKS = RegistryKey.unsafeOf("fireworks");

    // Calls a method
    RegistryKey<DamageType> STALAGMITE = RegistryKey.unsafeOf("stalagmite");

    // Calls a method
    RegistryKey<DamageType> GENERIC = RegistryKey.unsafeOf("generic");

    // Calls a method
    RegistryKey<DamageType> SONIC_BOOM = RegistryKey.unsafeOf("sonic_boom");

    // Calls a method
    RegistryKey<DamageType> DRY_OUT = RegistryKey.unsafeOf("dry_out");

    // Calls a method
    RegistryKey<DamageType> ENDER_PEARL = RegistryKey.unsafeOf("ender_pearl");

    // Calls a method
    RegistryKey<DamageType> MOB_PROJECTILE = RegistryKey.unsafeOf("mob_projectile");

    // Calls a method
    RegistryKey<DamageType> MOB_ATTACK = RegistryKey.unsafeOf("mob_attack");

    // Calls a method
    RegistryKey<DamageType> FALL = RegistryKey.unsafeOf("fall");

    // Calls a method
    RegistryKey<DamageType> THROWN = RegistryKey.unsafeOf("thrown");

    // Calls a method
    RegistryKey<DamageType> FALLING_BLOCK = RegistryKey.unsafeOf("falling_block");

    // Calls a method
    RegistryKey<DamageType> WIND_CHARGE = RegistryKey.unsafeOf("wind_charge");

    // Calls a method
    RegistryKey<DamageType> PLAYER_EXPLOSION = RegistryKey.unsafeOf("player_explosion");

    // Calls a method
    RegistryKey<DamageType> UNATTRIBUTED_FIREBALL = RegistryKey.unsafeOf("unattributed_fireball");

    // Calls a method
    RegistryKey<DamageType> IN_WALL = RegistryKey.unsafeOf("in_wall");

    // Calls a method
    RegistryKey<DamageType> STARVE = RegistryKey.unsafeOf("starve");

    // Calls a method
    RegistryKey<DamageType> MOB_ATTACK_NO_AGGRO = RegistryKey.unsafeOf("mob_attack_no_aggro");

    // Calls a method
    RegistryKey<DamageType> OUTSIDE_BORDER = RegistryKey.unsafeOf("outside_border");

    // Calls a method
    RegistryKey<DamageType> LIGHTNING_BOLT = RegistryKey.unsafeOf("lightning_bolt");

    // Calls a method
    RegistryKey<DamageType> OUT_OF_WORLD = RegistryKey.unsafeOf("out_of_world");

    // Calls a method
    RegistryKey<DamageType> MAGIC = RegistryKey.unsafeOf("magic");

    // Calls a method
    RegistryKey<DamageType> EXPLOSION = RegistryKey.unsafeOf("explosion");

    // Calls a method
    RegistryKey<DamageType> THORNS = RegistryKey.unsafeOf("thorns");

    // Calls a method
    RegistryKey<DamageType> BAD_RESPAWN_POINT = RegistryKey.unsafeOf("bad_respawn_point");

    // Calls a method
    RegistryKey<DamageType> INDIRECT_MAGIC = RegistryKey.unsafeOf("indirect_magic");

    // Calls a method
    RegistryKey<DamageType> CRAMMING = RegistryKey.unsafeOf("cramming");

    // Calls a method
    RegistryKey<DamageType> CACTUS = RegistryKey.unsafeOf("cactus");
// End of a block/expression
}
