// Package declaration for this file
package net.minestom.server.entity.metadata.animal;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link ChickenSoundVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface ChickenSoundVariants permits ChickenSoundVariant {
    // Calls a method
    RegistryKey<ChickenSoundVariant> PICKY = RegistryKey.unsafeOf("picky");

    // Calls a method
    RegistryKey<ChickenSoundVariant> CLASSIC = RegistryKey.unsafeOf("classic");
// End of a block/expression
}
