// Déclaration du paquet de ce fichier
package net.minestom.server.entity.metadata.animal;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link ChickenSoundVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface ChickenSoundVariants permits ChickenSoundVariant {
    // Appelle une méthode
    RegistryKey<ChickenSoundVariant> PICKY = RegistryKey.unsafeOf("picky");

    // Appelle une méthode
    RegistryKey<ChickenSoundVariant> CLASSIC = RegistryKey.unsafeOf("classic");
// Fin d'un bloc/d'une expression
}
