// Déclaration du paquet de ce fichier
package net.minestom.server.entity.metadata.animal;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link ChickenVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface ChickenVariants permits ChickenVariant {
    // Appelle une méthode
    RegistryKey<ChickenVariant> WARM = RegistryKey.unsafeOf("warm");

    // Appelle une méthode
    RegistryKey<ChickenVariant> TEMPERATE = RegistryKey.unsafeOf("temperate");

    // Appelle une méthode
    RegistryKey<ChickenVariant> COLD = RegistryKey.unsafeOf("cold");
// Fin d'un bloc/d'une expression
}
