// Package declaration for this file
package net.minestom.server.entity.metadata.animal;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link CowSoundVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface CowSoundVariants permits CowSoundVariant {
    // Calls a method
    RegistryKey<CowSoundVariant> MOODY = RegistryKey.unsafeOf("moody");

    // Calls a method
    RegistryKey<CowSoundVariant> CLASSIC = RegistryKey.unsafeOf("classic");
// End of a block/expression
}
