// Déclaration du paquet de ce fichier
package net.minestom.server.entity.metadata.animal;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link CowVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface CowVariants permits CowVariant {
    // Appelle une méthode
    RegistryKey<CowVariant> WARM = RegistryKey.unsafeOf("warm");

    // Appelle une méthode
    RegistryKey<CowVariant> COLD = RegistryKey.unsafeOf("cold");

    // Appelle une méthode
    RegistryKey<CowVariant> TEMPERATE = RegistryKey.unsafeOf("temperate");
// Fin d'un bloc/d'une expression
}
