// Package declaration for this file
package net.minestom.server.entity.metadata.animal;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link FrogVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface FrogVariants permits FrogVariant {
    // Calls a method
    RegistryKey<FrogVariant> WARM = RegistryKey.unsafeOf("warm");

    // Calls a method
    RegistryKey<FrogVariant> TEMPERATE = RegistryKey.unsafeOf("temperate");

    // Calls a method
    RegistryKey<FrogVariant> COLD = RegistryKey.unsafeOf("cold");
// End of a block/expression
}
