// Déclaration du paquet de ce fichier
package net.minestom.server.entity.metadata.animal;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link PigSoundVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface PigSoundVariants permits PigSoundVariant {
    // Appelle une méthode
    RegistryKey<PigSoundVariant> BIG = RegistryKey.unsafeOf("big");

    // Appelle une méthode
    RegistryKey<PigSoundVariant> CLASSIC = RegistryKey.unsafeOf("classic");

    // Appelle une méthode
    RegistryKey<PigSoundVariant> MINI = RegistryKey.unsafeOf("mini");
// Fin d'un bloc/d'une expression
}
