// Package declaration for this file
package net.minestom.server.entity.metadata.animal;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link PigSoundVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface PigSoundVariants permits PigSoundVariant {
    // Calls a method
    RegistryKey<PigSoundVariant> BIG = RegistryKey.unsafeOf("big");

    // Calls a method
    RegistryKey<PigSoundVariant> CLASSIC = RegistryKey.unsafeOf("classic");

    // Calls a method
    RegistryKey<PigSoundVariant> MINI = RegistryKey.unsafeOf("mini");
// End of a block/expression
}
