// Déclaration du paquet de ce fichier
package net.minestom.server.entity.metadata.animal;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link PigVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface PigVariants permits PigVariant {
    // Appelle une méthode
    RegistryKey<PigVariant> WARM = RegistryKey.unsafeOf("warm");

    // Appelle une méthode
    RegistryKey<PigVariant> TEMPERATE = RegistryKey.unsafeOf("temperate");

    // Appelle une méthode
    RegistryKey<PigVariant> COLD = RegistryKey.unsafeOf("cold");
// Fin d'un bloc/d'une expression
}
