// Package declaration for this file
package net.minestom.server.entity.metadata.animal;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link ZombieNautilusVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface ZombieNautilusVariants permits ZombieNautilusVariant {
    // Calls a method
    RegistryKey<ZombieNautilusVariant> WARM = RegistryKey.unsafeOf("warm");

    // Calls a method
    RegistryKey<ZombieNautilusVariant> TEMPERATE = RegistryKey.unsafeOf("temperate");
// End of a block/expression
}
