// Déclaration du paquet de ce fichier
package net.minestom.server.entity.metadata.other;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link PaintingVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface PaintingVariants permits PaintingVariant {
    // Appelle une méthode
    RegistryKey<PaintingVariant> WITHER = RegistryKey.unsafeOf("wither");

    // Appelle une méthode
    RegistryKey<PaintingVariant> BOUQUET = RegistryKey.unsafeOf("bouquet");

    // Appelle une méthode
    RegistryKey<PaintingVariant> ALBAN = RegistryKey.unsafeOf("alban");

    // Appelle une méthode
    RegistryKey<PaintingVariant> UNPACKED = RegistryKey.unsafeOf("unpacked");

    // Appelle une méthode
    RegistryKey<PaintingVariant> AZTEC = RegistryKey.unsafeOf("aztec");

    // Appelle une méthode
    RegistryKey<PaintingVariant> MATCH = RegistryKey.unsafeOf("match");

    // Appelle une méthode
    RegistryKey<PaintingVariant> FINDING = RegistryKey.unsafeOf("finding");

    // Appelle une méthode
    RegistryKey<PaintingVariant> ORB = RegistryKey.unsafeOf("orb");

    // Appelle une méthode
    RegistryKey<PaintingVariant> ENDBOSS = RegistryKey.unsafeOf("endboss");

    // Appelle une méthode
    RegistryKey<PaintingVariant> BAROQUE = RegistryKey.unsafeOf("baroque");

    // Appelle une méthode
    RegistryKey<PaintingVariant> AZTEC2 = RegistryKey.unsafeOf("aztec2");

    // Appelle une méthode
    RegistryKey<PaintingVariant> SUNFLOWERS = RegistryKey.unsafeOf("sunflowers");

    // Appelle une méthode
    RegistryKey<PaintingVariant> WASTELAND = RegistryKey.unsafeOf("wasteland");

    // Appelle une méthode
    RegistryKey<PaintingVariant> CHANGING = RegistryKey.unsafeOf("changing");

    // Appelle une méthode
    RegistryKey<PaintingVariant> DONKEY_KONG = RegistryKey.unsafeOf("donkey_kong");

    // Appelle une méthode
    RegistryKey<PaintingVariant> POOL = RegistryKey.unsafeOf("pool");

    // Appelle une méthode
    RegistryKey<PaintingVariant> BUST = RegistryKey.unsafeOf("bust");

    // Appelle une méthode
    RegistryKey<PaintingVariant> PIGSCENE = RegistryKey.unsafeOf("pigscene");

    // Appelle une méthode
    RegistryKey<PaintingVariant> FIRE = RegistryKey.unsafeOf("fire");

    // Appelle une méthode
    RegistryKey<PaintingVariant> BURNING_SKULL = RegistryKey.unsafeOf("burning_skull");

    // Appelle une méthode
    RegistryKey<PaintingVariant> SEA = RegistryKey.unsafeOf("sea");

    // Appelle une méthode
    RegistryKey<PaintingVariant> SUNSET = RegistryKey.unsafeOf("sunset");

    // Appelle une méthode
    RegistryKey<PaintingVariant> POND = RegistryKey.unsafeOf("pond");

    // Appelle une méthode
    RegistryKey<PaintingVariant> HUMBLE = RegistryKey.unsafeOf("humble");

    // Appelle une méthode
    RegistryKey<PaintingVariant> TIDES = RegistryKey.unsafeOf("tides");

    // Appelle une méthode
    RegistryKey<PaintingVariant> PRAIRIE_RIDE = RegistryKey.unsafeOf("prairie_ride");

    // Appelle une méthode
    RegistryKey<PaintingVariant> PASSAGE = RegistryKey.unsafeOf("passage");

    // Appelle une méthode
    RegistryKey<PaintingVariant> FERN = RegistryKey.unsafeOf("fern");

    // Appelle une méthode
    RegistryKey<PaintingVariant> LOWMIST = RegistryKey.unsafeOf("lowmist");

    // Appelle une méthode
    RegistryKey<PaintingVariant> COURBET = RegistryKey.unsafeOf("courbet");

    // Appelle une méthode
    RegistryKey<PaintingVariant> WANDERER = RegistryKey.unsafeOf("wanderer");

    // Appelle une méthode
    RegistryKey<PaintingVariant> EARTH = RegistryKey.unsafeOf("earth");

    // Appelle une méthode
    RegistryKey<PaintingVariant> BACKYARD = RegistryKey.unsafeOf("backyard");

    // Appelle une méthode
    RegistryKey<PaintingVariant> SKULL_AND_ROSES = RegistryKey.unsafeOf("skull_and_roses");

    // Appelle une méthode
    RegistryKey<PaintingVariant> FIGHTERS = RegistryKey.unsafeOf("fighters");

    // Appelle une méthode
    RegistryKey<PaintingVariant> CAVEBIRD = RegistryKey.unsafeOf("cavebird");

    // Appelle une méthode
    RegistryKey<PaintingVariant> COTAN = RegistryKey.unsafeOf("cotan");

    // Appelle une méthode
    RegistryKey<PaintingVariant> CREEBET = RegistryKey.unsafeOf("creebet");

    // Appelle une méthode
    RegistryKey<PaintingVariant> OWLEMONS = RegistryKey.unsafeOf("owlemons");

    // Appelle une méthode
    RegistryKey<PaintingVariant> GRAHAM = RegistryKey.unsafeOf("graham");

    // Appelle une méthode
    RegistryKey<PaintingVariant> MEDITATIVE = RegistryKey.unsafeOf("meditative");

    // Appelle une méthode
    RegistryKey<PaintingVariant> DENNIS = RegistryKey.unsafeOf("dennis");

    // Appelle une méthode
    RegistryKey<PaintingVariant> KEBAB = RegistryKey.unsafeOf("kebab");

    // Appelle une méthode
    RegistryKey<PaintingVariant> STAGE = RegistryKey.unsafeOf("stage");

    // Appelle une méthode
    RegistryKey<PaintingVariant> BOMB = RegistryKey.unsafeOf("bomb");

    // Appelle une méthode
    RegistryKey<PaintingVariant> PLANT = RegistryKey.unsafeOf("plant");

    // Appelle une méthode
    RegistryKey<PaintingVariant> WATER = RegistryKey.unsafeOf("water");

    // Appelle une méthode
    RegistryKey<PaintingVariant> POINTER = RegistryKey.unsafeOf("pointer");

    // Appelle une méthode
    RegistryKey<PaintingVariant> SKELETON = RegistryKey.unsafeOf("skeleton");

    // Appelle une méthode
    RegistryKey<PaintingVariant> VOID = RegistryKey.unsafeOf("void");

    // Appelle une méthode
    RegistryKey<PaintingVariant> WIND = RegistryKey.unsafeOf("wind");
// Fin d'un bloc/d'une expression
}
