// Déclaration du paquet de ce fichier
package net.minestom.server.item.instrument;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link Instrument}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface Instruments permits Instrument {
    // Appelle une méthode
    RegistryKey<Instrument> ADMIRE_GOAT_HORN = RegistryKey.unsafeOf("admire_goat_horn");

    // Appelle une méthode
    RegistryKey<Instrument> SING_GOAT_HORN = RegistryKey.unsafeOf("sing_goat_horn");

    // Appelle une méthode
    RegistryKey<Instrument> YEARN_GOAT_HORN = RegistryKey.unsafeOf("yearn_goat_horn");

    // Appelle une méthode
    RegistryKey<Instrument> SEEK_GOAT_HORN = RegistryKey.unsafeOf("seek_goat_horn");

    // Appelle une méthode
    RegistryKey<Instrument> DREAM_GOAT_HORN = RegistryKey.unsafeOf("dream_goat_horn");

    // Appelle une méthode
    RegistryKey<Instrument> FEEL_GOAT_HORN = RegistryKey.unsafeOf("feel_goat_horn");

    // Appelle une méthode
    RegistryKey<Instrument> CALL_GOAT_HORN = RegistryKey.unsafeOf("call_goat_horn");

    // Appelle une méthode
    RegistryKey<Instrument> PONDER_GOAT_HORN = RegistryKey.unsafeOf("ponder_goat_horn");
// Fin d'un bloc/d'une expression
}
