// Package declaration for this file
package net.minestom.server.item.instrument;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link Instrument}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface Instruments permits Instrument {
    // Calls a method
    RegistryKey<Instrument> ADMIRE_GOAT_HORN = RegistryKey.unsafeOf("admire_goat_horn");

    // Calls a method
    RegistryKey<Instrument> YEARN_GOAT_HORN = RegistryKey.unsafeOf("yearn_goat_horn");

    // Calls a method
    RegistryKey<Instrument> SING_GOAT_HORN = RegistryKey.unsafeOf("sing_goat_horn");

    // Calls a method
    RegistryKey<Instrument> SEEK_GOAT_HORN = RegistryKey.unsafeOf("seek_goat_horn");

    // Calls a method
    RegistryKey<Instrument> FEEL_GOAT_HORN = RegistryKey.unsafeOf("feel_goat_horn");

    // Calls a method
    RegistryKey<Instrument> DREAM_GOAT_HORN = RegistryKey.unsafeOf("dream_goat_horn");

    // Calls a method
    RegistryKey<Instrument> CALL_GOAT_HORN = RegistryKey.unsafeOf("call_goat_horn");

    // Calls a method
    RegistryKey<Instrument> PONDER_GOAT_HORN = RegistryKey.unsafeOf("ponder_goat_horn");
// End of a block/expression
}
