// Déclaration du paquet de ce fichier
package net.minestom.server.world.clock;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link ClockTimeMarker}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface ClockTimeMarkers permits ClockTimeMarker {
    // Appelle une méthode
    RegistryKey<ClockTimeMarker> CLOCK_TIME_MARKER = RegistryKey.unsafeOf("clock_time_marker");

    // Appelle une méthode
    RegistryKey<ClockTimeMarker> DAY = RegistryKey.unsafeOf("day");

    // Appelle une méthode
    RegistryKey<ClockTimeMarker> NOON = RegistryKey.unsafeOf("noon");

    // Appelle une méthode
    RegistryKey<ClockTimeMarker> NIGHT = RegistryKey.unsafeOf("night");

    // Appelle une méthode
    RegistryKey<ClockTimeMarker> MIDNIGHT = RegistryKey.unsafeOf("midnight");

    // Appelle une méthode
    RegistryKey<ClockTimeMarker> WAKE_UP_FROM_SLEEP = RegistryKey.unsafeOf("wake_up_from_sleep");

    // Appelle une méthode
    RegistryKey<ClockTimeMarker> ROLL_VILLAGE_SIEGE = RegistryKey.unsafeOf("roll_village_siege");
// Fin d'un bloc/d'une expression
}
