// Package declaration for this file
package net.minestom.server.world.clock;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link ClockTimeMarker}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface ClockTimeMarkers permits ClockTimeMarker {
    // Calls a method
    RegistryKey<ClockTimeMarker> CLOCK_TIME_MARKER = RegistryKey.unsafeOf("clock_time_marker");

    // Calls a method
    RegistryKey<ClockTimeMarker> DAY = RegistryKey.unsafeOf("day");

    // Calls a method
    RegistryKey<ClockTimeMarker> NOON = RegistryKey.unsafeOf("noon");

    // Calls a method
    RegistryKey<ClockTimeMarker> NIGHT = RegistryKey.unsafeOf("night");

    // Calls a method
    RegistryKey<ClockTimeMarker> MIDNIGHT = RegistryKey.unsafeOf("midnight");

    // Calls a method
    RegistryKey<ClockTimeMarker> WAKE_UP_FROM_SLEEP = RegistryKey.unsafeOf("wake_up_from_sleep");

    // Calls a method
    RegistryKey<ClockTimeMarker> ROLL_VILLAGE_SIEGE = RegistryKey.unsafeOf("roll_village_siege");
// End of a block/expression
}
