// Package declaration for this file
package net.minestom.server.world.clock;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link WorldClock}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface WorldClocks permits WorldClock {
    // Calls a method
    RegistryKey<WorldClock> THE_END = RegistryKey.unsafeOf("the_end");

    // Calls a method
    RegistryKey<WorldClock> OVERWORLD = RegistryKey.unsafeOf("overworld");
// End of a block/expression
}
