// Déclaration du paquet de ce fichier
package net.minestom.server.world.clock;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link WorldClock}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface WorldClocks permits WorldClock {
    // Appelle une méthode
    RegistryKey<WorldClock> THE_END = RegistryKey.unsafeOf("the_end");

    // Appelle une méthode
    RegistryKey<WorldClock> OVERWORLD = RegistryKey.unsafeOf("overworld");
// Fin d'un bloc/d'une expression
}
