// Package declaration for this file
package net.minestom.server.recipe.display;

// Import of a required class
import java.util.Arrays;
// Import of a required class
import java.util.Map;
// Import of a required class
import java.util.function.Function;
// Import of a required class
import java.util.stream.Collectors;
// Import of a required class
import net.kyori.adventure.key.Key;
// Import of a required class
import net.minestom.server.codec.Codec;
// Import of a required class
import net.minestom.server.network.NetworkBuffer;
// Import of a required class
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Type declaration (class/interface/enum/record)
public enum RecipeDisplayType implements StaticProtocolObject<RecipeDisplayType> {
    // Code statement
    CRAFTING_SHAPELESS("crafting_shapeless"),

    // Code statement
    CRAFTING_SHAPED("crafting_shaped"),

    // Code statement
    FURNACE("furnace"),

    // Code statement
    STONECUTTER("stonecutter"),

    // Calls a method
    SMITHING("smithing");

    // Calls a method
    private static final Map<Key, RecipeDisplayType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(RecipeDisplayType::key, Function.identity()));

    // Calls a method
    public static final NetworkBuffer.Type<RecipeDisplayType> NETWORK_TYPE = NetworkBuffer.Enum(RecipeDisplayType.class);

    // Calls a method
    public static final Codec<RecipeDisplayType> CODEC = Codec.KEY.transform(BY_KEY::get, RecipeDisplayType::key);

    // Code statement
    private final Key key;

    // Start of a method/block
    RecipeDisplayType(String key) {
        // Access to the current/parent object
        this.key = Key.key(key);
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public Key key() {
        // Returns a value to the caller
        return this.key;
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public int id() {
        // Returns a value to the caller
        return this.ordinal();
    // End of a block/expression
    }
// End of a block/expression
}
