// Déclaration du paquet de ce fichier
package net.minestom.server.recipe.display;

// Import d'une classe nécessaire
import java.util.Arrays;
// Import d'une classe nécessaire
import java.util.Map;
// Import d'une classe nécessaire
import java.util.function.Function;
// Import d'une classe nécessaire
import java.util.stream.Collectors;
// Import d'une classe nécessaire
import net.kyori.adventure.key.Key;
// Import d'une classe nécessaire
import net.minestom.server.codec.Codec;
// Import d'une classe nécessaire
import net.minestom.server.network.NetworkBuffer;
// Import d'une classe nécessaire
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Déclaration de type (classe/interface/enum/record)
public enum RecipeDisplayType implements StaticProtocolObject<RecipeDisplayType> {
    // Instruction de code
    CRAFTING_SHAPELESS("crafting_shapeless"),

    // Instruction de code
    CRAFTING_SHAPED("crafting_shaped"),

    // Instruction de code
    FURNACE("furnace"),

    // Instruction de code
    STONECUTTER("stonecutter"),

    // Appelle une méthode
    SMITHING("smithing");

    // Appelle une méthode
    private static final Map<Key, RecipeDisplayType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(RecipeDisplayType::key, Function.identity()));

    // Appelle une méthode
    public static final NetworkBuffer.Type<RecipeDisplayType> NETWORK_TYPE = NetworkBuffer.Enum(RecipeDisplayType.class);

    // Appelle une méthode
    public static final Codec<RecipeDisplayType> CODEC = Codec.KEY.transform(BY_KEY::get, RecipeDisplayType::key);

    // Instruction de code
    private final Key key;

    // Début d'une méthode/d'un bloc
    RecipeDisplayType(String key) {
        // Accès à l'objet courant/parent
        this.key = Key.key(key);
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public Key key() {
        // Renvoie une valeur à l'appelant
        return this.key;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public int id() {
        // Renvoie une valeur à l'appelant
        return this.ordinal();
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
