// Déclaration du paquet de ce fichier
package net.minestom.server.recipe.display;

// Import d'une classe nécessaire
import java.util.Arrays;
// Import d'une classe nécessaire
import java.util.Map;
// Import d'une classe nécessaire
import java.util.function.Function;
// Import d'une classe nécessaire
import java.util.stream.Collectors;
// Import d'une classe nécessaire
import net.kyori.adventure.key.Key;
// Import d'une classe nécessaire
import net.minestom.server.codec.Codec;
// Import d'une classe nécessaire
import net.minestom.server.network.NetworkBuffer;
// Import d'une classe nécessaire
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Déclaration de type (classe/interface/enum/record)
public enum SlotDisplayType implements StaticProtocolObject<SlotDisplayType> {
    // Instruction de code
    EMPTY("empty"),

    // Instruction de code
    ANY_FUEL("any_fuel"),

    // Instruction de code
    WITH_ANY_POTION("with_any_potion"),

    // Instruction de code
    ONLY_WITH_COMPONENT("only_with_component"),

    // Instruction de code
    ITEM("item"),

    // Instruction de code
    ITEM_STACK("item_stack"),

    // Instruction de code
    TAG("tag"),

    // Instruction de code
    DYED("dyed"),

    // Instruction de code
    SMITHING_TRIM("smithing_trim"),

    // Instruction de code
    WITH_REMAINDER("with_remainder"),

    // Appelle une méthode
    COMPOSITE("composite");

    // Appelle une méthode
    private static final Map<Key, SlotDisplayType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(SlotDisplayType::key, Function.identity()));

    // Appelle une méthode
    public static final NetworkBuffer.Type<SlotDisplayType> NETWORK_TYPE = NetworkBuffer.Enum(SlotDisplayType.class);

    // Appelle une méthode
    public static final Codec<SlotDisplayType> CODEC = Codec.KEY.transform(BY_KEY::get, SlotDisplayType::key);

    // Instruction de code
    private final Key key;

    // Début d'une méthode/d'un bloc
    SlotDisplayType(String key) {
        // Accès à l'objet courant/parent
        this.key = Key.key(key);
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public Key key() {
        // Renvoie une valeur à l'appelant
        return this.key;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public int id() {
        // Renvoie une valeur à l'appelant
        return this.ordinal();
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
