// Package declaration for this file
package net.minestom.server.recipe.display;

// Import of a required class
import java.util.Arrays;
// Import of a required class
import java.util.Map;
// Import of a required class
import java.util.function.Function;
// Import of a required class
import java.util.stream.Collectors;
// Import of a required class
import net.kyori.adventure.key.Key;
// Import of a required class
import net.minestom.server.codec.Codec;
// Import of a required class
import net.minestom.server.network.NetworkBuffer;
// Import of a required class
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Type declaration (class/interface/enum/record)
public enum SlotDisplayType implements StaticProtocolObject<SlotDisplayType> {
    // Code statement
    EMPTY("empty"),

    // Code statement
    ANY_FUEL("any_fuel"),

    // Code statement
    WITH_ANY_POTION("with_any_potion"),

    // Code statement
    ONLY_WITH_COMPONENT("only_with_component"),

    // Code statement
    ITEM("item"),

    // Code statement
    ITEM_STACK("item_stack"),

    // Code statement
    TAG("tag"),

    // Code statement
    DYED("dyed"),

    // Code statement
    SMITHING_TRIM("smithing_trim"),

    // Code statement
    WITH_REMAINDER("with_remainder"),

    // Calls a method
    COMPOSITE("composite");

    // Calls a method
    private static final Map<Key, SlotDisplayType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(SlotDisplayType::key, Function.identity()));

    // Calls a method
    public static final NetworkBuffer.Type<SlotDisplayType> NETWORK_TYPE = NetworkBuffer.Enum(SlotDisplayType.class);

    // Calls a method
    public static final Codec<SlotDisplayType> CODEC = Codec.KEY.transform(BY_KEY::get, SlotDisplayType::key);

    // Code statement
    private final Key key;

    // Start of a method/block
    SlotDisplayType(String key) {
        // Access to the current/parent object
        this.key = Key.key(key);
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public Key key() {
        // Returns a value to the caller
        return this.key;
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public int id() {
        // Returns a value to the caller
        return this.ordinal();
    // End of a block/expression
    }
// End of a block/expression
}
