// Déclaration du paquet de ce fichier
package net.minestom.server.command;

// Import d'une classe nécessaire
import java.util.Arrays;
// Import d'une classe nécessaire
import java.util.Map;
// Import d'une classe nécessaire
import java.util.function.Function;
// Import d'une classe nécessaire
import java.util.stream.Collectors;
// Import d'une classe nécessaire
import net.kyori.adventure.key.Key;
// Import d'une classe nécessaire
import net.minestom.server.codec.Codec;
// Import d'une classe nécessaire
import net.minestom.server.network.NetworkBuffer;
// Import d'une classe nécessaire
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Déclaration de type (classe/interface/enum/record)
public enum ArgumentParserType implements StaticProtocolObject<ArgumentParserType> {
    // Instruction de code
    BOOL("brigadier:bool"),

    // Instruction de code
    FLOAT("brigadier:float"),

    // Instruction de code
    DOUBLE("brigadier:double"),

    // Instruction de code
    INTEGER("brigadier:integer"),

    // Instruction de code
    LONG("brigadier:long"),

    // Instruction de code
    STRING("brigadier:string"),

    // Instruction de code
    ENTITY("entity"),

    // Instruction de code
    GAME_PROFILE("game_profile"),

    // Instruction de code
    BLOCK_POS("block_pos"),

    // Instruction de code
    COLUMN_POS("column_pos"),

    // Instruction de code
    VEC3("vec3"),

    // Instruction de code
    VEC2("vec2"),

    // Instruction de code
    BLOCK_STATE("block_state"),

    // Instruction de code
    BLOCK_PREDICATE("block_predicate"),

    // Instruction de code
    ITEM_STACK("item_stack"),

    // Instruction de code
    ITEM_PREDICATE("item_predicate"),

    // Instruction de code
    COLOR("color"),

    // Instruction de code
    HEX_COLOR("hex_color"),

    // Instruction de code
    COMPONENT("component"),

    // Instruction de code
    STYLE("style"),

    // Instruction de code
    MESSAGE("message"),

    // Instruction de code
    NBT_COMPOUND_TAG("nbt_compound_tag"),

    // Instruction de code
    NBT_TAG("nbt_tag"),

    // Instruction de code
    NBT_PATH("nbt_path"),

    // Instruction de code
    OBJECTIVE("objective"),

    // Instruction de code
    OBJECTIVE_CRITERIA("objective_criteria"),

    // Instruction de code
    OPERATION("operation"),

    // Instruction de code
    PARTICLE("particle"),

    // Instruction de code
    ANGLE("angle"),

    // Instruction de code
    ROTATION("rotation"),

    // Instruction de code
    SCOREBOARD_SLOT("scoreboard_slot"),

    // Instruction de code
    SCORE_HOLDER("score_holder"),

    // Instruction de code
    SWIZZLE("swizzle"),

    // Instruction de code
    TEAM("team"),

    // Instruction de code
    ITEM_SLOT("item_slot"),

    // Instruction de code
    ITEM_SLOTS("item_slots"),

    // Instruction de code
    RESOURCE_LOCATION("resource_location"),

    // Instruction de code
    FUNCTION("function"),

    // Instruction de code
    ENTITY_ANCHOR("entity_anchor"),

    // Instruction de code
    INT_RANGE("int_range"),

    // Instruction de code
    FLOAT_RANGE("float_range"),

    // Instruction de code
    DIMENSION("dimension"),

    // Instruction de code
    GAMEMODE("gamemode"),

    // Instruction de code
    TIME("time"),

    // Instruction de code
    RESOURCE_OR_TAG("resource_or_tag"),

    // Instruction de code
    RESOURCE_OR_TAG_KEY("resource_or_tag_key"),

    // Instruction de code
    RESOURCE("resource"),

    // Instruction de code
    RESOURCE_KEY("resource_key"),

    // Instruction de code
    RESOURCE_SELECTOR("resource_selector"),

    // Instruction de code
    TEMPLATE_MIRROR("template_mirror"),

    // Instruction de code
    TEMPLATE_ROTATION("template_rotation"),

    // Instruction de code
    HEIGHTMAP("heightmap"),

    // Instruction de code
    LOOT_TABLE("loot_table"),

    // Instruction de code
    LOOT_PREDICATE("loot_predicate"),

    // Instruction de code
    LOOT_MODIFIER("loot_modifier"),

    // Instruction de code
    DIALOG("dialog"),

    // Appelle une méthode
    UUID("uuid");

    // Appelle une méthode
    private static final Map<Key, ArgumentParserType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(ArgumentParserType::key, Function.identity()));

    // Appelle une méthode
    public static final NetworkBuffer.Type<ArgumentParserType> NETWORK_TYPE = NetworkBuffer.Enum(ArgumentParserType.class);

    // Appelle une méthode
    public static final Codec<ArgumentParserType> CODEC = Codec.KEY.transform(BY_KEY::get, ArgumentParserType::key);

    // Instruction de code
    private final Key key;

    // Début d'une méthode/d'un bloc
    ArgumentParserType(String key) {
        // Accès à l'objet courant/parent
        this.key = Key.key(key);
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public Key key() {
        // Renvoie une valeur à l'appelant
        return this.key;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public int id() {
        // Renvoie une valeur à l'appelant
        return this.ordinal();
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
