// Package declaration for this file
package net.minestom.server.command;

// Import of a required class
import java.util.Arrays;
// Import of a required class
import java.util.Map;
// Import of a required class
import java.util.function.Function;
// Import of a required class
import java.util.stream.Collectors;
// Import of a required class
import net.kyori.adventure.key.Key;
// Import of a required class
import net.minestom.server.codec.Codec;
// Import of a required class
import net.minestom.server.network.NetworkBuffer;
// Import of a required class
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Type declaration (class/interface/enum/record)
public enum ArgumentParserType implements StaticProtocolObject<ArgumentParserType> {
    // Code statement
    BOOL("brigadier:bool"),

    // Code statement
    FLOAT("brigadier:float"),

    // Code statement
    DOUBLE("brigadier:double"),

    // Code statement
    INTEGER("brigadier:integer"),

    // Code statement
    LONG("brigadier:long"),

    // Code statement
    STRING("brigadier:string"),

    // Code statement
    ENTITY("entity"),

    // Code statement
    GAME_PROFILE("game_profile"),

    // Code statement
    BLOCK_POS("block_pos"),

    // Code statement
    COLUMN_POS("column_pos"),

    // Code statement
    VEC3("vec3"),

    // Code statement
    VEC2("vec2"),

    // Code statement
    BLOCK_STATE("block_state"),

    // Code statement
    BLOCK_PREDICATE("block_predicate"),

    // Code statement
    ITEM_STACK("item_stack"),

    // Code statement
    ITEM_PREDICATE("item_predicate"),

    // Code statement
    COLOR("color"),

    // Code statement
    HEX_COLOR("hex_color"),

    // Code statement
    COMPONENT("component"),

    // Code statement
    STYLE("style"),

    // Code statement
    MESSAGE("message"),

    // Code statement
    NBT_COMPOUND_TAG("nbt_compound_tag"),

    // Code statement
    NBT_TAG("nbt_tag"),

    // Code statement
    NBT_PATH("nbt_path"),

    // Code statement
    OBJECTIVE("objective"),

    // Code statement
    OBJECTIVE_CRITERIA("objective_criteria"),

    // Code statement
    OPERATION("operation"),

    // Code statement
    PARTICLE("particle"),

    // Code statement
    ANGLE("angle"),

    // Code statement
    ROTATION("rotation"),

    // Code statement
    SCOREBOARD_SLOT("scoreboard_slot"),

    // Code statement
    SCORE_HOLDER("score_holder"),

    // Code statement
    SWIZZLE("swizzle"),

    // Code statement
    TEAM("team"),

    // Code statement
    ITEM_SLOT("item_slot"),

    // Code statement
    ITEM_SLOTS("item_slots"),

    // Code statement
    RESOURCE_LOCATION("resource_location"),

    // Code statement
    FUNCTION("function"),

    // Code statement
    ENTITY_ANCHOR("entity_anchor"),

    // Code statement
    INT_RANGE("int_range"),

    // Code statement
    FLOAT_RANGE("float_range"),

    // Code statement
    DIMENSION("dimension"),

    // Code statement
    GAMEMODE("gamemode"),

    // Code statement
    TIME("time"),

    // Code statement
    RESOURCE_OR_TAG("resource_or_tag"),

    // Code statement
    RESOURCE_OR_TAG_KEY("resource_or_tag_key"),

    // Code statement
    RESOURCE("resource"),

    // Code statement
    RESOURCE_KEY("resource_key"),

    // Code statement
    RESOURCE_SELECTOR("resource_selector"),

    // Code statement
    TEMPLATE_MIRROR("template_mirror"),

    // Code statement
    TEMPLATE_ROTATION("template_rotation"),

    // Code statement
    HEIGHTMAP("heightmap"),

    // Code statement
    LOOT_TABLE("loot_table"),

    // Code statement
    LOOT_PREDICATE("loot_predicate"),

    // Code statement
    LOOT_MODIFIER("loot_modifier"),

    // Code statement
    DIALOG("dialog"),

    // Calls a method
    UUID("uuid");

    // Calls a method
    private static final Map<Key, ArgumentParserType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(ArgumentParserType::key, Function.identity()));

    // Calls a method
    public static final NetworkBuffer.Type<ArgumentParserType> NETWORK_TYPE = NetworkBuffer.Enum(ArgumentParserType.class);

    // Calls a method
    public static final Codec<ArgumentParserType> CODEC = Codec.KEY.transform(BY_KEY::get, ArgumentParserType::key);

    // Code statement
    private final Key key;

    // Start of a method/block
    ArgumentParserType(String key) {
        // Access to the current/parent object
        this.key = Key.key(key);
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public Key key() {
        // Returns a value to the caller
        return this.key;
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public int id() {
        // Returns a value to the caller
        return this.ordinal();
    // End of a block/expression
    }
// End of a block/expression
}
