// Package declaration for this file
package net.minestom.server.particle;

/**
 * This class contains all the generated constants for {@link Particle}
 * <br>
 * Code autogenerated, do not edit!
 */
// Type declaration (class/interface/enum/record)
sealed interface Particles permits Particle {
    // Calls a method
    Particle ANGRY_VILLAGER = ParticleImpl.get("minecraft:angry_villager");

    // Calls a method
    Particle.Block BLOCK = ParticleImpl.get("minecraft:block");

    // Calls a method
    Particle.BlockMarker BLOCK_MARKER = ParticleImpl.get("minecraft:block_marker");

    // Calls a method
    Particle BUBBLE = ParticleImpl.get("minecraft:bubble");

    // Calls a method
    Particle CLOUD = ParticleImpl.get("minecraft:cloud");

    // Calls a method
    Particle COPPER_FIRE_FLAME = ParticleImpl.get("minecraft:copper_fire_flame");

    // Calls a method
    Particle CRIT = ParticleImpl.get("minecraft:crit");

    // Calls a method
    Particle DAMAGE_INDICATOR = ParticleImpl.get("minecraft:damage_indicator");

    // Calls a method
    Particle.DragonBreath DRAGON_BREATH = ParticleImpl.get("minecraft:dragon_breath");

    // Calls a method
    Particle DRIPPING_LAVA = ParticleImpl.get("minecraft:dripping_lava");

    // Calls a method
    Particle FALLING_LAVA = ParticleImpl.get("minecraft:falling_lava");

    // Calls a method
    Particle LANDING_LAVA = ParticleImpl.get("minecraft:landing_lava");

    // Calls a method
    Particle DRIPPING_WATER = ParticleImpl.get("minecraft:dripping_water");

    // Calls a method
    Particle FALLING_WATER = ParticleImpl.get("minecraft:falling_water");

    // Calls a method
    Particle.Dust DUST = ParticleImpl.get("minecraft:dust");

    // Calls a method
    Particle.DustColorTransition DUST_COLOR_TRANSITION = ParticleImpl.get("minecraft:dust_color_transition");

    // Calls a method
    Particle.Effect EFFECT = ParticleImpl.get("minecraft:effect");

    // Calls a method
    Particle ELDER_GUARDIAN = ParticleImpl.get("minecraft:elder_guardian");

    // Calls a method
    Particle ENCHANTED_HIT = ParticleImpl.get("minecraft:enchanted_hit");

    // Calls a method
    Particle ENCHANT = ParticleImpl.get("minecraft:enchant");

    // Calls a method
    Particle END_ROD = ParticleImpl.get("minecraft:end_rod");

    // Calls a method
    Particle.EntityEffect ENTITY_EFFECT = ParticleImpl.get("minecraft:entity_effect");

    // Calls a method
    Particle EXPLOSION_EMITTER = ParticleImpl.get("minecraft:explosion_emitter");

    // Calls a method
    Particle EXPLOSION = ParticleImpl.get("minecraft:explosion");

    // Calls a method
    Particle GUST = ParticleImpl.get("minecraft:gust");

    // Calls a method
    Particle SMALL_GUST = ParticleImpl.get("minecraft:small_gust");

    // Calls a method
    Particle GUST_EMITTER_LARGE = ParticleImpl.get("minecraft:gust_emitter_large");

    // Calls a method
    Particle GUST_EMITTER_SMALL = ParticleImpl.get("minecraft:gust_emitter_small");

    // Calls a method
    Particle SONIC_BOOM = ParticleImpl.get("minecraft:sonic_boom");

    // Calls a method
    Particle.FallingDust FALLING_DUST = ParticleImpl.get("minecraft:falling_dust");

    // Calls a method
    Particle FIREWORK = ParticleImpl.get("minecraft:firework");

    // Calls a method
    Particle FISHING = ParticleImpl.get("minecraft:fishing");

    // Calls a method
    Particle FLAME = ParticleImpl.get("minecraft:flame");

    // Calls a method
    Particle INFESTED = ParticleImpl.get("minecraft:infested");

    // Calls a method
    Particle CHERRY_LEAVES = ParticleImpl.get("minecraft:cherry_leaves");

    // Calls a method
    Particle PALE_OAK_LEAVES = ParticleImpl.get("minecraft:pale_oak_leaves");

    // Calls a method
    Particle.TintedLeaves TINTED_LEAVES = ParticleImpl.get("minecraft:tinted_leaves");

    // Calls a method
    Particle SCULK_SOUL = ParticleImpl.get("minecraft:sculk_soul");

    // Calls a method
    Particle.SculkCharge SCULK_CHARGE = ParticleImpl.get("minecraft:sculk_charge");

    // Calls a method
    Particle SCULK_CHARGE_POP = ParticleImpl.get("minecraft:sculk_charge_pop");

    // Calls a method
    Particle SOUL_FIRE_FLAME = ParticleImpl.get("minecraft:soul_fire_flame");

    // Calls a method
    Particle SOUL = ParticleImpl.get("minecraft:soul");

    // Calls a method
    Particle.Flash FLASH = ParticleImpl.get("minecraft:flash");

    // Calls a method
    Particle HAPPY_VILLAGER = ParticleImpl.get("minecraft:happy_villager");

    // Calls a method
    Particle COMPOSTER = ParticleImpl.get("minecraft:composter");

    // Calls a method
    Particle HEART = ParticleImpl.get("minecraft:heart");

    // Calls a method
    Particle.InstantEffect INSTANT_EFFECT = ParticleImpl.get("minecraft:instant_effect");

    // Calls a method
    Particle.Item ITEM = ParticleImpl.get("minecraft:item");

    // Calls a method
    Particle.Vibration VIBRATION = ParticleImpl.get("minecraft:vibration");

    // Calls a method
    Particle.Trail TRAIL = ParticleImpl.get("minecraft:trail");

    // Calls a method
    Particle PAUSE_MOB_GROWTH = ParticleImpl.get("minecraft:pause_mob_growth");

    // Calls a method
    Particle RESET_MOB_GROWTH = ParticleImpl.get("minecraft:reset_mob_growth");

    // Calls a method
    Particle ITEM_SLIME = ParticleImpl.get("minecraft:item_slime");

    // Calls a method
    Particle ITEM_COBWEB = ParticleImpl.get("minecraft:item_cobweb");

    // Calls a method
    Particle ITEM_SNOWBALL = ParticleImpl.get("minecraft:item_snowball");

    // Calls a method
    Particle LARGE_SMOKE = ParticleImpl.get("minecraft:large_smoke");

    // Calls a method
    Particle LAVA = ParticleImpl.get("minecraft:lava");

    // Calls a method
    Particle MYCELIUM = ParticleImpl.get("minecraft:mycelium");

    // Calls a method
    Particle NOTE = ParticleImpl.get("minecraft:note");

    // Calls a method
    Particle POOF = ParticleImpl.get("minecraft:poof");

    // Calls a method
    Particle PORTAL = ParticleImpl.get("minecraft:portal");

    // Calls a method
    Particle RAIN = ParticleImpl.get("minecraft:rain");

    // Calls a method
    Particle SMOKE = ParticleImpl.get("minecraft:smoke");

    // Calls a method
    Particle WHITE_SMOKE = ParticleImpl.get("minecraft:white_smoke");

    // Calls a method
    Particle SNEEZE = ParticleImpl.get("minecraft:sneeze");

    // Calls a method
    Particle SPIT = ParticleImpl.get("minecraft:spit");

    // Calls a method
    Particle SQUID_INK = ParticleImpl.get("minecraft:squid_ink");

    // Calls a method
    Particle SWEEP_ATTACK = ParticleImpl.get("minecraft:sweep_attack");

    // Calls a method
    Particle TOTEM_OF_UNDYING = ParticleImpl.get("minecraft:totem_of_undying");

    // Calls a method
    Particle UNDERWATER = ParticleImpl.get("minecraft:underwater");

    // Calls a method
    Particle SPLASH = ParticleImpl.get("minecraft:splash");

    // Calls a method
    Particle WITCH = ParticleImpl.get("minecraft:witch");

    // Calls a method
    Particle BUBBLE_POP = ParticleImpl.get("minecraft:bubble_pop");

    // Calls a method
    Particle CURRENT_DOWN = ParticleImpl.get("minecraft:current_down");

    // Calls a method
    Particle BUBBLE_COLUMN_UP = ParticleImpl.get("minecraft:bubble_column_up");

    // Calls a method
    Particle NAUTILUS = ParticleImpl.get("minecraft:nautilus");

    // Calls a method
    Particle DOLPHIN = ParticleImpl.get("minecraft:dolphin");

    // Calls a method
    Particle CAMPFIRE_COSY_SMOKE = ParticleImpl.get("minecraft:campfire_cosy_smoke");

    // Calls a method
    Particle CAMPFIRE_SIGNAL_SMOKE = ParticleImpl.get("minecraft:campfire_signal_smoke");

    // Calls a method
    Particle DRIPPING_HONEY = ParticleImpl.get("minecraft:dripping_honey");

    // Calls a method
    Particle FALLING_HONEY = ParticleImpl.get("minecraft:falling_honey");

    // Calls a method
    Particle LANDING_HONEY = ParticleImpl.get("minecraft:landing_honey");

    // Calls a method
    Particle FALLING_NECTAR = ParticleImpl.get("minecraft:falling_nectar");

    // Calls a method
    Particle FALLING_SPORE_BLOSSOM = ParticleImpl.get("minecraft:falling_spore_blossom");

    // Calls a method
    Particle ASH = ParticleImpl.get("minecraft:ash");

    // Calls a method
    Particle CRIMSON_SPORE = ParticleImpl.get("minecraft:crimson_spore");

    // Calls a method
    Particle WARPED_SPORE = ParticleImpl.get("minecraft:warped_spore");

    // Calls a method
    Particle SPORE_BLOSSOM_AIR = ParticleImpl.get("minecraft:spore_blossom_air");

    // Calls a method
    Particle DRIPPING_OBSIDIAN_TEAR = ParticleImpl.get("minecraft:dripping_obsidian_tear");

    // Calls a method
    Particle FALLING_OBSIDIAN_TEAR = ParticleImpl.get("minecraft:falling_obsidian_tear");

    // Calls a method
    Particle LANDING_OBSIDIAN_TEAR = ParticleImpl.get("minecraft:landing_obsidian_tear");

    // Calls a method
    Particle REVERSE_PORTAL = ParticleImpl.get("minecraft:reverse_portal");

    // Calls a method
    Particle WHITE_ASH = ParticleImpl.get("minecraft:white_ash");

    // Calls a method
    Particle SMALL_FLAME = ParticleImpl.get("minecraft:small_flame");

    // Calls a method
    Particle SNOWFLAKE = ParticleImpl.get("minecraft:snowflake");

    // Calls a method
    Particle DRIPPING_DRIPSTONE_LAVA = ParticleImpl.get("minecraft:dripping_dripstone_lava");

    // Calls a method
    Particle FALLING_DRIPSTONE_LAVA = ParticleImpl.get("minecraft:falling_dripstone_lava");

    // Calls a method
    Particle DRIPPING_DRIPSTONE_WATER = ParticleImpl.get("minecraft:dripping_dripstone_water");

    // Calls a method
    Particle FALLING_DRIPSTONE_WATER = ParticleImpl.get("minecraft:falling_dripstone_water");

    // Calls a method
    Particle GLOW_SQUID_INK = ParticleImpl.get("minecraft:glow_squid_ink");

    // Calls a method
    Particle GLOW = ParticleImpl.get("minecraft:glow");

    // Calls a method
    Particle WAX_ON = ParticleImpl.get("minecraft:wax_on");

    // Calls a method
    Particle WAX_OFF = ParticleImpl.get("minecraft:wax_off");

    // Calls a method
    Particle ELECTRIC_SPARK = ParticleImpl.get("minecraft:electric_spark");

    // Calls a method
    Particle SCRAPE = ParticleImpl.get("minecraft:scrape");

    // Calls a method
    Particle.Shriek SHRIEK = ParticleImpl.get("minecraft:shriek");

    // Calls a method
    Particle EGG_CRACK = ParticleImpl.get("minecraft:egg_crack");

    // Calls a method
    Particle DUST_PLUME = ParticleImpl.get("minecraft:dust_plume");

    // Calls a method
    Particle TRIAL_SPAWNER_DETECTION = ParticleImpl.get("minecraft:trial_spawner_detection");

    // Calls a method
    Particle TRIAL_SPAWNER_DETECTION_OMINOUS = ParticleImpl.get("minecraft:trial_spawner_detection_ominous");

    // Calls a method
    Particle VAULT_CONNECTION = ParticleImpl.get("minecraft:vault_connection");

    // Calls a method
    Particle.DustPillar DUST_PILLAR = ParticleImpl.get("minecraft:dust_pillar");

    // Calls a method
    Particle OMINOUS_SPAWNING = ParticleImpl.get("minecraft:ominous_spawning");

    // Calls a method
    Particle RAID_OMEN = ParticleImpl.get("minecraft:raid_omen");

    // Calls a method
    Particle TRIAL_OMEN = ParticleImpl.get("minecraft:trial_omen");

    // Calls a method
    Particle.BlockCrumble BLOCK_CRUMBLE = ParticleImpl.get("minecraft:block_crumble");

    // Calls a method
    Particle FIREFLY = ParticleImpl.get("minecraft:firefly");
// End of a block/expression
}
