// Package declaration for this file
package net.minestom.server.instance.block.jukebox;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link JukeboxSong}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface JukeboxSongs permits JukeboxSong {
    // Calls a method
    RegistryKey<JukeboxSong> STAL = RegistryKey.unsafeOf("stal");

    // Calls a method
    RegistryKey<JukeboxSong> PRECIPICE = RegistryKey.unsafeOf("precipice");

    // Calls a method
    RegistryKey<JukeboxSong> STRAD = RegistryKey.unsafeOf("strad");

    // Calls a method
    RegistryKey<JukeboxSong> CREATOR_MUSIC_BOX = RegistryKey.unsafeOf("creator_music_box");

    // Calls a method
    RegistryKey<JukeboxSong> _13 = RegistryKey.unsafeOf("13");

    // Calls a method
    RegistryKey<JukeboxSong> RELIC = RegistryKey.unsafeOf("relic");

    // Calls a method
    RegistryKey<JukeboxSong> FAR = RegistryKey.unsafeOf("far");

    // Calls a method
    RegistryKey<JukeboxSong> BLOCKS = RegistryKey.unsafeOf("blocks");

    // Calls a method
    RegistryKey<JukeboxSong> _5 = RegistryKey.unsafeOf("5");

    // Calls a method
    RegistryKey<JukeboxSong> LAVA_CHICKEN = RegistryKey.unsafeOf("lava_chicken");

    // Calls a method
    RegistryKey<JukeboxSong> OTHERSIDE = RegistryKey.unsafeOf("otherside");

    // Calls a method
    RegistryKey<JukeboxSong> TEARS = RegistryKey.unsafeOf("tears");

    // Calls a method
    RegistryKey<JukeboxSong> MELLOHI = RegistryKey.unsafeOf("mellohi");

    // Calls a method
    RegistryKey<JukeboxSong> MALL = RegistryKey.unsafeOf("mall");

    // Calls a method
    RegistryKey<JukeboxSong> PIGSTEP = RegistryKey.unsafeOf("pigstep");

    // Calls a method
    RegistryKey<JukeboxSong> CREATOR = RegistryKey.unsafeOf("creator");

    // Calls a method
    RegistryKey<JukeboxSong> CHIRP = RegistryKey.unsafeOf("chirp");

    // Calls a method
    RegistryKey<JukeboxSong> WARD = RegistryKey.unsafeOf("ward");

    // Calls a method
    RegistryKey<JukeboxSong> WAIT = RegistryKey.unsafeOf("wait");

    // Calls a method
    RegistryKey<JukeboxSong> CAT = RegistryKey.unsafeOf("cat");

    // Calls a method
    RegistryKey<JukeboxSong> _11 = RegistryKey.unsafeOf("11");
// End of a block/expression
}
