// Déclaration du paquet de ce fichier
package net.minestom.codegen;

// Import d'une classe nécessaire
import com.google.gson.JsonArray;
// Import d'une classe nécessaire
import com.google.gson.JsonElement;
// Import d'une classe nécessaire
import com.google.gson.JsonObject;
// Import d'une classe nécessaire
import com.palantir.javapoet.*;

// Import d'une classe nécessaire
import javax.lang.model.element.Modifier;
// Import d'une classe nécessaire
import java.io.InputStream;
// Import d'une classe nécessaire
import java.io.InputStreamReader;
// Import d'une classe nécessaire
import java.nio.file.Path;
// Import d'une classe nécessaire
import java.util.Comparator;
// Import d'une classe nécessaire
import java.util.List;
// Import d'une classe nécessaire
import java.util.Objects;
// Import d'une classe nécessaire
import java.util.stream.StreamSupport;

// Déclaration de type (classe/interface/enum/record)
public record DyeColorGenerator(InputStream dyeColorsFile,
                                // Début d'une méthode/d'un bloc
                                Path outputFolder) implements MinestomCodeGenerator {
    // Début d'une méthode/d'un bloc
    public DyeColorGenerator {
        // Appelle une méthode
        Objects.requireNonNull(dyeColorsFile, "Dye colors file cannot be null");
        // Appelle une méthode
        Objects.requireNonNull(outputFolder, "Output folder cannot be null");
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public void generate() {
        // Appelle une méthode
        ensureDirectory(outputFolder);
        // Important classes we use a lot
        // Appelle une méthode
        ClassName colorCN = ClassName.get("net.minestom.server.color", "Color");

        // Appelle une méthode
        JsonArray dyeColors = GSON.fromJson(new InputStreamReader(dyeColorsFile), JsonArray.class);
        // Appelle une méthode
        ClassName dyeColorCN = ClassName.get("net.minestom.server.color", "DyeColor");
        // Dye Color Enum
        // Affecte une valeur
        TypeSpec.Builder dyeColorEnum = TypeSpec.enumBuilder(dyeColorCN)
                // Instruction de code
                .addSuperinterface(ClassName.get("net.kyori.adventure.util", "RGBLike"))
                // Appelle une méthode
                .addModifiers(Modifier.PUBLIC).addJavadoc("AUTOGENERATED by " + getClass().getSimpleName());

        // Appelle une méthode
        ClassName networkBufferCN = ClassName.get("net.minestom.server.network", "NetworkBuffer");
        // Appelle une méthode
        ParameterizedTypeName networkBufferTypeCN = ParameterizedTypeName.get(networkBufferCN.nestedClass("Type"), dyeColorCN);
        // Appelle une méthode
        ClassName codecCN = ClassName.get("net.minestom.server.codec", "Codec");
        // Appelle une méthode
        ParameterizedTypeName codecTypeCN = ParameterizedTypeName.get(codecCN, dyeColorCN);

        // Fields
        // Instruction de code
        dyeColorEnum.addFields(
                // Instruction de code
                List.of(
                        // Instruction de code
                        FieldSpec.builder(networkBufferTypeCN, "NETWORK_TYPE", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                                // Instruction de code
                                .initializer("$T.Enum($T.class)", networkBufferCN, dyeColorCN)
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        FieldSpec.builder(codecTypeCN, "CODEC", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                                // Instruction de code
                                .initializer("$T.Enum($T.class)", codecCN, dyeColorCN)
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        FieldSpec.builder(colorCN, "textureDiffuseColor", Modifier.PRIVATE, Modifier.FINAL).build(),
                        // Instruction de code
                        FieldSpec.builder(colorCN, "textColor", Modifier.PRIVATE, Modifier.FINAL).build(),
                        // Instruction de code
                        FieldSpec.builder(colorCN, "fireworkColor", Modifier.PRIVATE, Modifier.FINAL).build(),
                        // Instruction de code
                        FieldSpec.builder(TypeName.INT, "mapColorId", Modifier.PRIVATE, Modifier.FINAL).build()
                // Fin d'un bloc/d'une expression
                )
        // Fin d'un bloc/d'une expression
        );

        // Methods
        // Instruction de code
        dyeColorEnum.addMethods(
                // Instruction de code
                List.of(
                        // Constructor
                        // Instruction de code
                        MethodSpec.constructorBuilder()
                                // Instruction de code
                                .addParameters(
                                        // Instruction de code
                                        List.of(
                                                // Instruction de code
                                                ParameterSpec.builder(colorCN, "textureDiffuseColor").build(),
                                                // Instruction de code
                                                ParameterSpec.builder(colorCN, "textColor").build(),
                                                // Instruction de code
                                                ParameterSpec.builder(colorCN, "fireworkColor").build(),
                                                // Instruction de code
                                                ParameterSpec.builder(TypeName.INT, "mapColorId").build()
                                        // Fin d'un bloc/d'une expression
                                        )
                                // Fin d'un bloc/d'une expression
                                )
                                // Affecte une valeur
                                .addStatement("this.textureDiffuseColor = textureDiffuseColor")
                                // Affecte une valeur
                                .addStatement("this.textColor = textColor")
                                // Affecte une valeur
                                .addStatement("this.fireworkColor = fireworkColor")
                                // Affecte une valeur
                                .addStatement("this.mapColorId = mapColorId")
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("color")
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC)
                                // Instruction de code
                                .returns(colorCN)
                                // Instruction de code
                                .addStatement("return this.textureDiffuseColor")
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("textColor")
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC)
                                // Instruction de code
                                .returns(colorCN)
                                // Instruction de code
                                .addStatement("return this.textColor")
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("fireworkColor")
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC)
                                // Instruction de code
                                .returns(colorCN)
                                // Instruction de code
                                .addStatement("return this.fireworkColor")
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("red")
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC)
                                // Instruction de code
                                .returns(TypeName.INT)
                                // Instruction de code
                                .addAnnotation(Override.class)
                                // Instruction de code
                                .addStatement("return this.textureDiffuseColor.red()")
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("green")
                                // Instruction de code
                                .returns(TypeName.INT)
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC)
                                // Instruction de code
                                .addAnnotation(Override.class)
                                // Instruction de code
                                .addStatement("return this.textureDiffuseColor.green()")
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("blue")
                                // Instruction de code
                                .returns(TypeName.INT)
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC)
                                // Instruction de code
                                .addAnnotation(Override.class)
                                // Instruction de code
                                .addStatement("return this.textureDiffuseColor.blue()")
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("mapColorId")
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC)
                                // Instruction de code
                                .returns(TypeName.INT)
                                // Instruction de code
                                .addStatement("return this.mapColorId")
                                // Instruction de code
                                .build()
                // Fin d'un bloc/d'une expression
                )
        // Fin d'un bloc/d'une expression
        );

        // Use data
        // Boucle : répète un bloc
        for (JsonObject dyeColorObject : StreamSupport.stream(dyeColors.spliterator(), true).map(JsonElement::getAsJsonObject).sorted(Comparator.comparingInt(o -> o.get("id").getAsInt())).toList()) {
            // Appelle une méthode
            String dyeColorName = dyeColorObject.get("name").getAsString();
            // Instruction de code
            dyeColorEnum.addEnumConstant(toConstant(dyeColorName), TypeSpec.anonymousClassBuilder(
                            // Instruction de code
                            "new $T(0x$L), new $T(0x$L), new $T(0x$L), $L",
                            // Instruction de code
                            colorCN, Integer.toHexString(dyeColorObject.get("textureDiffuseColor").getAsInt()),
                            // Chop 2 because we don't care about the alpha in this context.
                            // Instruction de code
                            colorCN, Integer.toHexString(dyeColorObject.get("textColor").getAsInt()).substring(2),
                            // Instruction de code
                            colorCN, Integer.toHexString(dyeColorObject.get("fireworkColor").getAsInt()),
                            // Instruction de code
                            dyeColorObject.get("mapColorId").getAsInt()
                    // Instruction de code
                    ).build()
            // Fin d'un bloc/d'une expression
            );
        // Fin d'un bloc/d'une expression
        }

        // Write files to outputFolder
        // Instruction de code
        writeFiles(JavaFile.builder("net.minestom.server.color", dyeColorEnum.build())
                // Instruction de code
                .indent("    ")
                // Instruction de code
                .skipJavaLangImports(true)
                // Instruction de code
                .build()
        // Fin d'un bloc/d'une expression
        );
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
