// Package declaration for this file
package net.minestom.codegen;

// Import of a required class
import com.google.gson.JsonObject;
// Import of a required class
import com.palantir.javapoet.*;

// Import of a required class
import javax.lang.model.element.Modifier;
// Import of a required class
import java.util.List;

// Type declaration (class/interface/enum/record)
record DyeColorGenerator(Codegen codegen) {

    // Start of a method/block
    void generate() {
        // Calls a method
        ClassName colorCN = ClassName.get("net.minestom.server.color", "Color");
        // Calls a method
        ClassName dyeColorCN = ClassName.get("net.minestom.server.color", "DyeColor");

        // Assigns a value
        TypeSpec.Builder dyeColorEnum = TypeSpec.enumBuilder(dyeColorCN)
                // Code statement
                .addSuperinterface(ClassName.get("net.kyori.adventure.util", "RGBLike"))
                // Code statement
                .addModifiers(Modifier.PUBLIC)
                // Calls a method
                .addJavadoc("AUTOGENERATED by DyeColorGenerator");

        // Calls a method
        ClassName networkBufferCN = ClassName.get("net.minestom.server.network", "NetworkBuffer");
        // Calls a method
        ParameterizedTypeName networkBufferTypeCN = ParameterizedTypeName.get(networkBufferCN.nestedClass("Type"), dyeColorCN);
        // Calls a method
        ClassName codecCN = ClassName.get("net.minestom.server.codec", "Codec");
        // Calls a method
        ParameterizedTypeName codecTypeCN = ParameterizedTypeName.get(codecCN, dyeColorCN);

        // Code statement
        dyeColorEnum.addFields(List.of(
                // Code statement
                FieldSpec.builder(networkBufferTypeCN, "NETWORK_TYPE", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                        // Code statement
                        .initializer("$T.Enum($T.class)", networkBufferCN, dyeColorCN)
                        // Code statement
                        .build(),
                // Code statement
                FieldSpec.builder(codecTypeCN, "CODEC", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                        // Code statement
                        .initializer("$T.Enum($T.class)", codecCN, dyeColorCN)
                        // Code statement
                        .build(),
                // Code statement
                FieldSpec.builder(colorCN, "textureDiffuseColor", Modifier.PRIVATE, Modifier.FINAL).build(),
                // Code statement
                FieldSpec.builder(colorCN, "textColor", Modifier.PRIVATE, Modifier.FINAL).build(),
                // Code statement
                FieldSpec.builder(colorCN, "fireworkColor", Modifier.PRIVATE, Modifier.FINAL).build(),
                // Code statement
                FieldSpec.builder(TypeName.INT, "mapColorId", Modifier.PRIVATE, Modifier.FINAL).build()
        // Code statement
        ));

        // Code statement
        dyeColorEnum.addMethods(List.of(
                // Code statement
                MethodSpec.constructorBuilder()
                        // Code statement
                        .addParameters(List.of(
                                // Code statement
                                ParameterSpec.builder(colorCN, "textureDiffuseColor").build(),
                                // Code statement
                                ParameterSpec.builder(colorCN, "textColor").build(),
                                // Code statement
                                ParameterSpec.builder(colorCN, "fireworkColor").build(),
                                // Code statement
                                ParameterSpec.builder(TypeName.INT, "mapColorId").build()
                        // Code statement
                        ))
                        // Assigns a value
                        .addStatement("this.textureDiffuseColor = textureDiffuseColor")
                        // Assigns a value
                        .addStatement("this.textColor = textColor")
                        // Assigns a value
                        .addStatement("this.fireworkColor = fireworkColor")
                        // Assigns a value
                        .addStatement("this.mapColorId = mapColorId")
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("color")
                        // Code statement
                        .addModifiers(Modifier.PUBLIC)
                        // Code statement
                        .returns(colorCN)
                        // Code statement
                        .addStatement("return this.textureDiffuseColor")
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("textColor")
                        // Code statement
                        .addModifiers(Modifier.PUBLIC)
                        // Code statement
                        .returns(colorCN)
                        // Code statement
                        .addStatement("return this.textColor")
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("fireworkColor")
                        // Code statement
                        .addModifiers(Modifier.PUBLIC)
                        // Code statement
                        .returns(colorCN)
                        // Code statement
                        .addStatement("return this.fireworkColor")
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("red")
                        // Code statement
                        .addModifiers(Modifier.PUBLIC)
                        // Code statement
                        .returns(TypeName.INT)
                        // Code statement
                        .addAnnotation(Override.class)
                        // Code statement
                        .addStatement("return this.textureDiffuseColor.red()")
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("green")
                        // Code statement
                        .returns(TypeName.INT)
                        // Code statement
                        .addModifiers(Modifier.PUBLIC)
                        // Code statement
                        .addAnnotation(Override.class)
                        // Code statement
                        .addStatement("return this.textureDiffuseColor.green()")
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("blue")
                        // Code statement
                        .returns(TypeName.INT)
                        // Code statement
                        .addModifiers(Modifier.PUBLIC)
                        // Code statement
                        .addAnnotation(Override.class)
                        // Code statement
                        .addStatement("return this.textureDiffuseColor.blue()")
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("mapColorId")
                        // Code statement
                        .addModifiers(Modifier.PUBLIC)
                        // Code statement
                        .returns(TypeName.INT)
                        // Code statement
                        .addStatement("return this.mapColorId")
                        // Code statement
                        .build()
        // Code statement
        ));

        // Loop: repeats a block
        for (JsonObject dyeColorObject : codegen.orderedObjects("dye_colors.json")) {
            // Calls a method
            String dyeColorName = dyeColorObject.get("name").getAsString();
            // Code statement
            dyeColorEnum.addEnumConstant(codegen.constantName(dyeColorName), TypeSpec.anonymousClassBuilder(
                            // Code statement
                            "new $T(0x$L), new $T(0x$L), new $T(0x$L), $L",
                            // Code statement
                            colorCN, Integer.toHexString(dyeColorObject.get("textureDiffuseColor").getAsInt()),
                            // Code statement
                            colorCN, Integer.toHexString(dyeColorObject.get("textColor").getAsInt()).substring(2),
                            // Code statement
                            colorCN, Integer.toHexString(dyeColorObject.get("fireworkColor").getAsInt()),
                            // Code statement
                            dyeColorObject.get("mapColorId").getAsInt()
                    // Code statement
                    ).build()
            // End of a block/expression
            );
        // End of a block/expression
        }

        // Calls a method
        codegen.write(codegen.javaFile("net.minestom.server.color", dyeColorEnum.build()));
    // End of a block/expression
    }
// End of a block/expression
}
