// Déclaration du paquet de ce fichier
package net.minestom.codegen;

// Import d'une classe nécessaire
import com.google.gson.JsonArray;
// Import d'une classe nécessaire
import com.google.gson.JsonElement;
// Import d'une classe nécessaire
import com.google.gson.JsonObject;
// Import d'une classe nécessaire
import com.palantir.javapoet.*;

// Import d'une classe nécessaire
import javax.lang.model.element.Modifier;
// Import d'une classe nécessaire
import java.io.InputStream;
// Import d'une classe nécessaire
import java.io.InputStreamReader;
// Import d'une classe nécessaire
import java.nio.file.Path;
// Import d'une classe nécessaire
import java.util.*;
// Import d'une classe nécessaire
import java.util.function.Function;
// Import d'une classe nécessaire
import java.util.stream.Collectors;
// Import d'une classe nécessaire
import java.util.stream.StreamSupport;

// Déclaration de type (classe/interface/enum/record)
public class GenericEnumGenerator implements MinestomCodeGenerator {
    // Instruction de code
    private final String packageName;
    // Instruction de code
    private final String className;
    // Instruction de code
    private final InputStream entriesFile;
    // Instruction de code
    private final Path outputFolder;

    // Affecte une valeur
    private boolean isPackagePrivate = false;

    // Instruction de code
    public GenericEnumGenerator(
            // Instruction de code
            String packageName, String className,
            // Instruction de code
            InputStream entriesFile, Path outputFolder
    // Début d'une méthode/d'un bloc
    ) {
        // Accès à l'objet courant/parent
        this.packageName = Objects.requireNonNull(packageName, "Package name cannot be null");
        // Accès à l'objet courant/parent
        this.className = Objects.requireNonNull(className, "Class name cannot be null");
        // Accès à l'objet courant/parent
        this.entriesFile = Objects.requireNonNull(entriesFile, "Entries file cannot be null");
        // Accès à l'objet courant/parent
        this.outputFolder = Objects.requireNonNull(outputFolder, "Output folder cannot be null");
    // Fin d'un bloc/d'une expression
    }

    // Début d'une méthode/d'un bloc
    public GenericEnumGenerator packagePrivate() {
        // Accès à l'objet courant/parent
        this.isPackagePrivate = true;
        // Renvoie une valeur à l'appelant
        return this;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public Path outputFolder() {
        // Renvoie une valeur à l'appelant
        return outputFolder;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public void generate() {
        // Appelle une méthode
        ensureDirectory(outputFolder);

        // Important classes we use alot
        // Appelle une méthode
        JsonArray entryList = GSON.fromJson(new InputStreamReader(entriesFile), JsonArray.class);
        // Appelle une méthode
        ClassName entryCN = ClassName.get(packageName, className);
        // Affecte une valeur
        Modifier[] modifiers = isPackagePrivate ? new Modifier[0] : new Modifier[]{Modifier.PUBLIC};
        // Affecte une valeur
        TypeSpec.Builder entryEnum = TypeSpec.enumBuilder(entryCN)
                // Instruction de code
                .addSuperinterface(
                        // Instruction de code
                        ParameterizedTypeName.get(
                                // Instruction de code
                                ClassName.get("net.minestom.server.registry", "StaticProtocolObject"),
                                // Instruction de code
                                entryCN
                        // Fin d'un bloc/d'une expression
                        )
                // Fin d'un bloc/d'une expression
                )
                // Appelle une méthode
                .addModifiers(modifiers).addJavadoc("AUTOGENERATED by " + getClass().getSimpleName());
        // Appelle une méthode
        ClassName keyCN = ClassName.get("net.kyori.adventure.key", "Key");

        // Appelle une méthode
        ClassName networkBufferCN = ClassName.get("net.minestom.server.network", "NetworkBuffer");
        // Appelle une méthode
        ParameterizedTypeName networkBufferTypeCN = ParameterizedTypeName.get(networkBufferCN.nestedClass("Type"), entryCN);
        // Appelle une méthode
        ClassName codecRawCN = ClassName.get("net.minestom.server.codec", "Codec");
        // Appelle une méthode
        ParameterizedTypeName codecCN = ParameterizedTypeName.get(codecRawCN, entryCN);

        // Fields
        // Instruction de code
        entryEnum.addFields(
                // Instruction de code
                List.of(
                        // Instruction de code
                        FieldSpec.builder(ParameterizedTypeName.get(ClassName.get(Map.class), keyCN, entryCN), "BY_KEY", Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                                // Instruction de code
                                .initializer("$T.stream(values()).collect($T.toUnmodifiableMap($T::key, $T.identity()))", Arrays.class, Collectors.class, entryCN, Function.class)
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        FieldSpec.builder(networkBufferTypeCN, "NETWORK_TYPE", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                                // Instruction de code
                                .initializer("$T.Enum($T.class)", networkBufferCN, entryCN)
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        FieldSpec.builder(codecCN, "CODEC", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                                // Instruction de code
                                .initializer("$T.KEY.transform(BY_KEY::get, $T::key)", codecRawCN, entryCN)
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        FieldSpec.builder(keyCN, "key", Modifier.PRIVATE, Modifier.FINAL).build()
                // Fin d'un bloc/d'une expression
                )
        // Fin d'un bloc/d'une expression
        );

        // Methods
        // Instruction de code
        entryEnum.addMethods(
                // Instruction de code
                List.of(
                        // Constructor
                        // Instruction de code
                        MethodSpec.constructorBuilder()
                                // Instruction de code
                                .addParameter(ParameterSpec.builder(String.class, "key").build())
                                // Affecte une valeur
                                .addStatement("this.key = $T.key(key)", keyCN)
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("key")
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC)
                                // Instruction de code
                                .addAnnotation(Override.class)
                                // Instruction de code
                                .returns(keyCN)
                                // Instruction de code
                                .addStatement("return this.key")
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("id")
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC)
                                // Instruction de code
                                .returns(TypeName.INT)
                                // Instruction de code
                                .addAnnotation(Override.class)
                                // Instruction de code
                                .addStatement("return this.ordinal()")
                                // Instruction de code
                                .build()
                // Fin d'un bloc/d'une expression
                )
        // Fin d'un bloc/d'une expression
        );

        // Use data
        // Boucle : répète un bloc
        for (JsonObject entryObject : StreamSupport.stream(entryList.spliterator(), true).map(JsonElement::getAsJsonObject).sorted(Comparator.comparingInt(o -> o.get("id").getAsInt())).toList()) {
            // Appelle une méthode
            final String entryName = entryObject.get("name").getAsString();
            // Appelle une méthode
            final String namespaceString = namespaceShort(entryName);
            // Instruction de code
            entryEnum.addEnumConstant(toConstant(entryName), TypeSpec.anonymousClassBuilder(
                    // Instruction de code
                    "$S", namespaceString
            // Appelle une méthode
            ).build());
        // Fin d'un bloc/d'une expression
        }

        // Write files
        // Instruction de code
        writeFiles(JavaFile.builder(packageName, entryEnum.build())
                // Instruction de code
                .indent("    ")
                // Instruction de code
                .skipJavaLangImports(true)
                // Instruction de code
                .build()
        // Fin d'un bloc/d'une expression
        );
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
