// Package declaration for this file
package net.minestom.codegen;

// Import of a required class
import com.google.gson.JsonObject;
// Import of a required class
import com.palantir.javapoet.*;

// Import of a required class
import javax.lang.model.element.Modifier;
// Import of a required class
import java.util.Arrays;
// Import of a required class
import java.util.List;
// Import of a required class
import java.util.Map;
// Import of a required class
import java.util.function.Function;
// Import of a required class
import java.util.stream.Collectors;

// Type declaration (class/interface/enum/record)
record GenericEnumGenerator(Codegen codegen) {

    // Start of a method/block
    void generate(Generators.EnumSpec spec) {
        // Calls a method
        ClassName entryCN = ClassName.get(spec.packageName(), spec.className());
        // Assigns a value
        TypeSpec.Builder entryEnum = TypeSpec.enumBuilder(entryCN)
                // Code statement
                .addSuperinterface(
                        // Code statement
                        ParameterizedTypeName.get(
                                // Code statement
                                ClassName.get("net.minestom.server.registry", "StaticProtocolObject"),
                                // Code statement
                                entryCN
                        // End of a block/expression
                        )
                // End of a block/expression
                )
                // Code statement
                .addModifiers(spec.isPublic() ? new Modifier[]{Modifier.PUBLIC} : new Modifier[0])
                // Calls a method
                .addJavadoc("AUTOGENERATED by " + spec.generatorName());

        // Calls a method
        ClassName keyCN = ClassName.get("net.kyori.adventure.key", "Key");
        // Calls a method
        ClassName networkBufferCN = ClassName.get("net.minestom.server.network", "NetworkBuffer");
        // Calls a method
        ParameterizedTypeName networkBufferTypeCN = ParameterizedTypeName.get(networkBufferCN.nestedClass("Type"), entryCN);
        // Calls a method
        ClassName codecRawCN = ClassName.get("net.minestom.server.codec", "Codec");
        // Calls a method
        ParameterizedTypeName codecCN = ParameterizedTypeName.get(codecRawCN, entryCN);

        // Code statement
        entryEnum.addFields(List.of(
                // Code statement
                FieldSpec.builder(ParameterizedTypeName.get(ClassName.get(Map.class), keyCN, entryCN), "BY_KEY", Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                        // Code statement
                        .initializer("$T.stream(values()).collect($T.toUnmodifiableMap($T::key, $T.identity()))", Arrays.class, Collectors.class, entryCN, Function.class)
                        // Code statement
                        .build(),
                // Code statement
                FieldSpec.builder(networkBufferTypeCN, "NETWORK_TYPE", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                        // Code statement
                        .initializer("$T.Enum($T.class)", networkBufferCN, entryCN)
                        // Code statement
                        .build(),
                // Code statement
                FieldSpec.builder(codecCN, "CODEC", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                        // Code statement
                        .initializer("$T.KEY.transform(BY_KEY::get, $T::key)", codecRawCN, entryCN)
                        // Code statement
                        .build(),
                // Code statement
                FieldSpec.builder(keyCN, "key", Modifier.PRIVATE, Modifier.FINAL).build()
        // Code statement
        ));

        // Code statement
        entryEnum.addMethods(List.of(
                // Code statement
                MethodSpec.constructorBuilder()
                        // Code statement
                        .addParameter(ParameterSpec.builder(String.class, "key").build())
                        // Assigns a value
                        .addStatement("this.key = $T.key(key)", keyCN)
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("key")
                        // Code statement
                        .addModifiers(Modifier.PUBLIC)
                        // Code statement
                        .addAnnotation(Override.class)
                        // Code statement
                        .returns(keyCN)
                        // Code statement
                        .addStatement("return this.key")
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("id")
                        // Code statement
                        .addModifiers(Modifier.PUBLIC)
                        // Code statement
                        .returns(TypeName.INT)
                        // Code statement
                        .addAnnotation(Override.class)
                        // Code statement
                        .addStatement("return this.ordinal()")
                        // Code statement
                        .build()
        // Code statement
        ));

        // Loop: repeats a block
        for (JsonObject entryObject : codegen.orderedObjects(spec.resource())) {
            // Calls a method
            String entryName = entryObject.get("name").getAsString();
            // Calls a method
            String constantName = spec.constantNameTransform().apply(codegen.constantName(entryName));
            // Code statement
            entryEnum.addEnumConstant(constantName, TypeSpec.anonymousClassBuilder(
                    // Code statement
                    "$S", codegen.namespaceShort(entryName)
            // Calls a method
            ).build());
        // End of a block/expression
        }

        // Calls a method
        codegen.write(codegen.javaFile(spec.packageName(), entryEnum.build()));
    // End of a block/expression
    }
// End of a block/expression
}
