// Déclaration du paquet de ce fichier
package net.minestom.codegen;

// Import d'une classe nécessaire
import com.google.gson.Gson;
// Import d'une classe nécessaire
import com.google.gson.GsonBuilder;
// Import d'une classe nécessaire
import com.palantir.javapoet.ClassName;
// Import d'une classe nécessaire
import com.palantir.javapoet.CodeBlock;
// Import d'une classe nécessaire
import com.palantir.javapoet.JavaFile;

// Import d'une classe nécessaire
import javax.lang.model.SourceVersion;
// Import d'une classe nécessaire
import java.io.IOException;
// Import d'une classe nécessaire
import java.nio.file.Files;
// Import d'une classe nécessaire
import java.nio.file.Path;
// Import d'une classe nécessaire
import java.util.Locale;
// Import d'une classe nécessaire
import java.util.Objects;

// Déclaration de type (classe/interface/enum/record)
public interface MinestomCodeGenerator {
    // Appelle une méthode
    Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    // Début d'une méthode/d'un bloc
    default String toConstant(String namespace) {
        // Affecte une valeur
        String constant = namespaceShort(namespace)
                // Instruction de code
                .replaceFirst("brigadier:", "") // Not implicit, do not put into namespaceShort
                // Instruction de code
                .replace(".", "_")
                // Appelle une méthode
                .toUpperCase(Locale.ROOT);
        // Embranchement : vérifie une condition
        if (!SourceVersion.isName(constant)) {
            // Affecte une valeur
            constant = "_" + constant;
        // Fin d'un bloc/d'une expression
        }
        // Renvoie une valeur à l'appelant
        return constant;
    // Fin d'un bloc/d'une expression
    }

    // Début d'une méthode/d'un bloc
    default String namespaceShort(String namespace) {
        // Renvoie une valeur à l'appelant
        return namespace.replaceFirst("minecraft:", "");
    // Fin d'un bloc/d'une expression
    }

    // Début d'une méthode/d'un bloc
    default void ensureDirectory(Path directory) throws IllegalStateException {
        // Appelle une méthode
        Objects.requireNonNull(directory, "Directory is null");
        // Embranchement : vérifie une condition
        if (Files.isDirectory(directory)) return;
        // Gestion des exceptions
        try {
            // Appelle une méthode
            Files.createDirectories(directory);
        // Début d'une méthode/d'un bloc
        } catch (IOException e) {
            // Lève une exception
            throw new IllegalStateException("Failed to create folder for %s".formatted(directory), e);
        // Fin d'un bloc/d'une expression
        }
    // Fin d'un bloc/d'une expression
    }

    // Début d'une méthode/d'un bloc
    default void writeFiles(JavaFile... files) {
        // Appelle une méthode
        Objects.requireNonNull(files, "File list cannot be null");
        // Appelle une méthode
        final Path to = outputFolder();
        // Appelle une méthode
        Objects.requireNonNull(to, "Output folder cannot be null");
        // Boucle : répète un bloc
        for (JavaFile javaFile : files) {
            // Gestion des exceptions
            try {
                // Appelle une méthode
                javaFile.writeTo(to);
            // Début d'une méthode/d'un bloc
            } catch (IOException e) {
                // Lève une exception
                throw new IllegalStateException("Failed to write all the output!", e);
            // Fin d'un bloc/d'une expression
            }
        // Fin d'un bloc/d'une expression
        }
    // Fin d'un bloc/d'une expression
    }

    // Début d'une méthode/d'un bloc
    default CodeBlock generateJavadoc(ClassName forImpl) {
        // Appelle une méthode
        Objects.requireNonNull(forImpl, "for cannot be null");
        // Renvoie une valeur à l'appelant
        return CodeBlock.builder()
                // Instruction de code
                .add("This class contains all the generated constants for {@link $T}\n<br>\n", forImpl)
                // Instruction de code
                .add("Code autogenerated, do not edit!")
                // Appelle une méthode
                .build();
    // Fin d'un bloc/d'une expression
    }

    // Appelle une méthode
    Path outputFolder();

    // Début d'une méthode/d'un bloc
    default void generate() {
        // Lève une exception
        throw new UnsupportedOperationException("This generator `%s` does not implement the generate method".formatted(getClass().getSimpleName()));
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
