// Déclaration du paquet de ce fichier
package net.minestom.codegen;

// Import d'une classe nécessaire
import com.google.gson.JsonArray;
// Import d'une classe nécessaire
import com.google.gson.JsonElement;
// Import d'une classe nécessaire
import com.google.gson.JsonObject;
// Import d'une classe nécessaire
import com.palantir.javapoet.*;
// Import d'une classe nécessaire
import org.jetbrains.annotations.Nullable;

// Import d'une classe nécessaire
import javax.lang.model.element.Modifier;
// Import d'une classe nécessaire
import java.io.InputStream;
// Import d'une classe nécessaire
import java.io.InputStreamReader;
// Import d'une classe nécessaire
import java.nio.file.Path;
// Import d'une classe nécessaire
import java.util.Comparator;
// Import d'une classe nécessaire
import java.util.List;
// Import d'une classe nécessaire
import java.util.Objects;
// Import d'une classe nécessaire
import java.util.stream.StreamSupport;

// Déclaration de type (classe/interface/enum/record)
public record WorldEventGenerator(String packageName, String worldEventClassName,
                                  // Instruction de code
                                  InputStream entriesFile,
                                  // Début d'une méthode/d'un bloc
                                  Path outputFolder) implements MinestomCodeGenerator {
    // Début d'une méthode/d'un bloc
    public WorldEventGenerator {
        // Appelle une méthode
        Objects.requireNonNull(packageName, "packageName cannot be null");
        // Appelle une méthode
        Objects.requireNonNull(worldEventClassName, "worldEventClassName cannot be null");
        // Appelle une méthode
        Objects.requireNonNull(entriesFile, "entriesFile cannot be null");
        // Appelle une méthode
        Objects.requireNonNull(outputFolder, "outputFolder cannot be null");
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public void generate() {
        // Appelle une méthode
        ensureDirectory(outputFolder);

        // Important classes we use alot
        // Appelle une méthode
        JsonArray entryList = GSON.fromJson(new InputStreamReader(entriesFile), JsonArray.class);
        // Appelle une méthode
        ClassName entryCN = ClassName.get(packageName, worldEventClassName);
        // Affecte une valeur
        TypeSpec.Builder entryEnum = TypeSpec.enumBuilder(entryCN)
                // Instruction de code
                .addModifiers(Modifier.PUBLIC)
                // Appelle une méthode
                .addJavadoc("AUTOGENERATED by " + getClass().getSimpleName());
        // Appelle une méthode
        ClassName networkBufferCN = ClassName.get("net.minestom.server.network", "NetworkBuffer");
        // Appelle une méthode
        ParameterizedTypeName networkBufferTypeCN = ParameterizedTypeName.get(networkBufferCN.nestedClass("Type"), entryCN);

        // Fields
        // Instruction de code
        entryEnum.addFields(
                // Instruction de code
                List.of(
                        // Instruction de code
                        FieldSpec.builder(networkBufferTypeCN, "NETWORK_TYPE", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                                // Instruction de code
                                .initializer("$T.VAR_INT.transform($T::fromId, $T::id)", networkBufferCN, entryCN, entryCN)
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        FieldSpec.builder(TypeName.INT, "eventId", Modifier.PRIVATE, Modifier.FINAL).build(),
                        // Instruction de code
                        FieldSpec.builder(ArrayTypeName.of(entryCN), "VALUES")
                                // Instruction de code
                                .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                                // Instruction de code
                                .initializer("values()")
                                // Instruction de code
                                .build()
                // Fin d'un bloc/d'une expression
                )
        // Fin d'un bloc/d'une expression
        );

        // Methods
        // Instruction de code
        entryEnum.addMethods(
                // Instruction de code
                List.of(
                        // Constructor
                        // Instruction de code
                        MethodSpec.constructorBuilder()
                                // Instruction de code
                                .addParameter(ParameterSpec.builder(int.class, "eventId").build())
                                // Affecte une valeur
                                .addStatement("this.eventId = eventId")
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("id")
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC)
                                // Instruction de code
                                .returns(TypeName.INT)
                                // Instruction de code
                                .addStatement("return this.eventId")
                                // Instruction de code
                                .build(),
                        // Instruction de code
                        MethodSpec.methodBuilder("fromId")
                                // Instruction de code
                                .addParameter(ParameterSpec.builder(int.class, "id").build())
                                // Instruction de code
                                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                                // Instruction de code
                                .beginControlFlow("for ($T event : VALUES)", entryCN)
                                // Instruction de code
                                .beginControlFlow("if (event.id() == id)")
                                // Instruction de code
                                .addStatement("return event")
                                // Instruction de code
                                .endControlFlow()
                                // Instruction de code
                                .endControlFlow()
                                // Instruction de code
                                .addStatement("return null")
                                // Instruction de code
                                .returns(entryCN)
                                // Instruction de code
                                .addAnnotation(Nullable.class)
                                // Instruction de code
                                .build()
                // Fin d'un bloc/d'une expression
                )
        // Fin d'un bloc/d'une expression
        );

        // Use data
        // Boucle : répète un bloc
        for (JsonObject entryObject : StreamSupport.stream(entryList.spliterator(), true).map(JsonElement::getAsJsonObject).sorted(Comparator.comparingInt(o -> o.get("id").getAsInt())).toList()) {
            // Appelle une méthode
            String entryName = entryObject.get("name").getAsString().toUpperCase();
            // Appelle une méthode
            int id = entryObject.get("id").getAsInt();
            // Appelle une méthode
            entryEnum.addEnumConstant(entryName, TypeSpec.anonymousClassBuilder("$L", id).build());
        // Fin d'un bloc/d'une expression
        }

        // Write files to outputFolder
        // Instruction de code
        writeFiles(JavaFile.builder(packageName, entryEnum.build())
                // Instruction de code
                .indent("    ")
                // Instruction de code
                .skipJavaLangImports(true)
                // Instruction de code
                .build()
        // Fin d'un bloc/d'une expression
        );
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
