// Package declaration for this file
package net.minestom.codegen;

// Import of a required class
import com.google.gson.JsonObject;
// Import of a required class
import com.palantir.javapoet.*;
// Import of a required class
import org.jetbrains.annotations.Nullable;

// Import of a required class
import javax.lang.model.element.Modifier;
// Import of a required class
import java.util.List;

// Type declaration (class/interface/enum/record)
record WorldEventGenerator(Codegen codegen, String packageName, String worldEventClassName, String resource) {

    // Start of a method/block
    void generate() {
        // Calls a method
        ClassName entryCN = ClassName.get(packageName, worldEventClassName);
        // Assigns a value
        TypeSpec.Builder entryEnum = TypeSpec.enumBuilder(entryCN)
                // Code statement
                .addModifiers(Modifier.PUBLIC)
                // Calls a method
                .addJavadoc("AUTOGENERATED by WorldEventGenerator");
        // Calls a method
        ClassName networkBufferCN = ClassName.get("net.minestom.server.network", "NetworkBuffer");
        // Calls a method
        ParameterizedTypeName networkBufferTypeCN = ParameterizedTypeName.get(networkBufferCN.nestedClass("Type"), entryCN);

        // Code statement
        entryEnum.addFields(List.of(
                // Code statement
                FieldSpec.builder(networkBufferTypeCN, "NETWORK_TYPE", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                        // Code statement
                        .initializer("$T.VAR_INT.transform($T::fromId, $T::id)", networkBufferCN, entryCN, entryCN)
                        // Code statement
                        .build(),
                // Code statement
                FieldSpec.builder(TypeName.INT, "eventId", Modifier.PRIVATE, Modifier.FINAL).build(),
                // Code statement
                FieldSpec.builder(ArrayTypeName.of(entryCN), "VALUES")
                        // Code statement
                        .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                        // Code statement
                        .initializer("values()")
                        // Code statement
                        .build()
        // Code statement
        ));

        // Code statement
        entryEnum.addMethods(List.of(
                // Code statement
                MethodSpec.constructorBuilder()
                        // Code statement
                        .addParameter(ParameterSpec.builder(int.class, "eventId").build())
                        // Assigns a value
                        .addStatement("this.eventId = eventId")
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("id")
                        // Code statement
                        .addModifiers(Modifier.PUBLIC)
                        // Code statement
                        .returns(TypeName.INT)
                        // Code statement
                        .addStatement("return this.eventId")
                        // Code statement
                        .build(),
                // Code statement
                MethodSpec.methodBuilder("fromId")
                        // Code statement
                        .addParameter(ParameterSpec.builder(int.class, "id").build())
                        // Code statement
                        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                        // Code statement
                        .beginControlFlow("for ($T event : VALUES)", entryCN)
                        // Code statement
                        .beginControlFlow("if (event.id() == id)")
                        // Code statement
                        .addStatement("return event")
                        // Code statement
                        .endControlFlow()
                        // Code statement
                        .endControlFlow()
                        // Code statement
                        .addStatement("return null")
                        // Code statement
                        .returns(entryCN)
                        // Code statement
                        .addAnnotation(Nullable.class)
                        // Code statement
                        .build()
        // Code statement
        ));

        // Loop: repeats a block
        for (JsonObject entryObject : codegen.orderedObjects(resource)) {
            // Calls a method
            String entryName = entryObject.get("name").getAsString().toUpperCase();
            // Calls a method
            int id = entryObject.get("id").getAsInt();
            // Calls a method
            entryEnum.addEnumConstant(entryName, TypeSpec.anonymousClassBuilder("$L", id).build());
        // End of a block/expression
        }

        // Calls a method
        codegen.write(codegen.javaFile(packageName, entryEnum.build()));
    // End of a block/expression
    }
// End of a block/expression
}
