// Package declaration for this file
package net.minestom.server.world;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link DimensionType}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface DimensionTypes permits DimensionType {
    // Calls a method
    RegistryKey<DimensionType> THE_END = RegistryKey.unsafeOf("the_end");

    // Calls a method
    RegistryKey<DimensionType> OVERWORLD_CAVES = RegistryKey.unsafeOf("overworld_caves");

    // Calls a method
    RegistryKey<DimensionType> THE_NETHER = RegistryKey.unsafeOf("the_nether");

    // Calls a method
    RegistryKey<DimensionType> OVERWORLD = RegistryKey.unsafeOf("overworld");
// End of a block/expression
}
