// Déclaration du paquet de ce fichier
package net.minestom.server.world;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link DimensionType}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface DimensionTypes permits DimensionType {
    // Appelle une méthode
    RegistryKey<DimensionType> THE_END = RegistryKey.unsafeOf("the_end");

    // Appelle une méthode
    RegistryKey<DimensionType> OVERWORLD_CAVES = RegistryKey.unsafeOf("overworld_caves");

    // Appelle une méthode
    RegistryKey<DimensionType> THE_NETHER = RegistryKey.unsafeOf("the_nether");

    // Appelle une méthode
    RegistryKey<DimensionType> OVERWORLD = RegistryKey.unsafeOf("overworld");
// Fin d'un bloc/d'une expression
}
