// Déclaration du paquet de ce fichier
package net.minestom.server.instance.gamerule;

/**
 * This class contains all the generated constants for {@link GameRule}
 * <br>
 * Code autogenerated, do not edit!
 */
// Déclaration de type (classe/interface/enum/record)
sealed interface GameRules permits GameRule {
    // Appelle une méthode
    GameRule<Boolean> ADVANCE_TIME = GameRuleImpl.get("advance_time");

    // Appelle une méthode
    GameRule<Boolean> ADVANCE_WEATHER = GameRuleImpl.get("advance_weather");

    // Appelle une méthode
    GameRule<Boolean> ALLOW_ENTERING_NETHER_USING_PORTALS = GameRuleImpl.get("allow_entering_nether_using_portals");

    // Appelle une méthode
    GameRule<Boolean> BLOCK_DROPS = GameRuleImpl.get("block_drops");

    // Appelle une méthode
    GameRule<Boolean> BLOCK_EXPLOSION_DROP_DECAY = GameRuleImpl.get("block_explosion_drop_decay");

    // Appelle une méthode
    GameRule<Boolean> COMMAND_BLOCKS_WORK = GameRuleImpl.get("command_blocks_work");

    // Appelle une méthode
    GameRule<Boolean> COMMAND_BLOCK_OUTPUT = GameRuleImpl.get("command_block_output");

    // Appelle une méthode
    GameRule<Boolean> DROWNING_DAMAGE = GameRuleImpl.get("drowning_damage");

    // Appelle une méthode
    GameRule<Boolean> ELYTRA_MOVEMENT_CHECK = GameRuleImpl.get("elytra_movement_check");

    // Appelle une méthode
    GameRule<Boolean> ENDER_PEARLS_VANISH_ON_DEATH = GameRuleImpl.get("ender_pearls_vanish_on_death");

    // Appelle une méthode
    GameRule<Boolean> ENTITY_DROPS = GameRuleImpl.get("entity_drops");

    // Appelle une méthode
    GameRule<Boolean> FALL_DAMAGE = GameRuleImpl.get("fall_damage");

    // Appelle une méthode
    GameRule<Boolean> FIRE_DAMAGE = GameRuleImpl.get("fire_damage");

    // Appelle une méthode
    GameRule<Integer> FIRE_SPREAD_RADIUS_AROUND_PLAYER = GameRuleImpl.get("fire_spread_radius_around_player");

    // Appelle une méthode
    GameRule<Boolean> FORGIVE_DEAD_PLAYERS = GameRuleImpl.get("forgive_dead_players");

    // Appelle une méthode
    GameRule<Boolean> FREEZE_DAMAGE = GameRuleImpl.get("freeze_damage");

    // Appelle une méthode
    GameRule<Boolean> GLOBAL_SOUND_EVENTS = GameRuleImpl.get("global_sound_events");

    // Appelle une méthode
    GameRule<Boolean> IMMEDIATE_RESPAWN = GameRuleImpl.get("immediate_respawn");

    // Appelle une méthode
    GameRule<Boolean> KEEP_INVENTORY = GameRuleImpl.get("keep_inventory");

    // Appelle une méthode
    GameRule<Boolean> LAVA_SOURCE_CONVERSION = GameRuleImpl.get("lava_source_conversion");

    // Appelle une méthode
    GameRule<Boolean> LIMITED_CRAFTING = GameRuleImpl.get("limited_crafting");

    // Appelle une méthode
    GameRule<Boolean> LOCATOR_BAR = GameRuleImpl.get("locator_bar");

    // Appelle une méthode
    GameRule<Boolean> LOG_ADMIN_COMMANDS = GameRuleImpl.get("log_admin_commands");

    // Appelle une méthode
    GameRule<Integer> MAX_BLOCK_MODIFICATIONS = GameRuleImpl.get("max_block_modifications");

    // Appelle une méthode
    GameRule<Integer> MAX_COMMAND_FORKS = GameRuleImpl.get("max_command_forks");

    // Appelle une méthode
    GameRule<Integer> MAX_COMMAND_SEQUENCE_LENGTH = GameRuleImpl.get("max_command_sequence_length");

    // Appelle une méthode
    GameRule<Integer> MAX_ENTITY_CRAMMING = GameRuleImpl.get("max_entity_cramming");

    // Appelle une méthode
    GameRule<Integer> MAX_MINECART_SPEED = GameRuleImpl.get("max_minecart_speed");

    // Appelle une méthode
    GameRule<Integer> MAX_SNOW_ACCUMULATION_HEIGHT = GameRuleImpl.get("max_snow_accumulation_height");

    // Appelle une méthode
    GameRule<Boolean> MOB_DROPS = GameRuleImpl.get("mob_drops");

    // Appelle une méthode
    GameRule<Boolean> MOB_EXPLOSION_DROP_DECAY = GameRuleImpl.get("mob_explosion_drop_decay");

    // Appelle une méthode
    GameRule<Boolean> MOB_GRIEFING = GameRuleImpl.get("mob_griefing");

    // Appelle une méthode
    GameRule<Boolean> NATURAL_HEALTH_REGENERATION = GameRuleImpl.get("natural_health_regeneration");

    // Appelle une méthode
    GameRule<Boolean> PLAYER_MOVEMENT_CHECK = GameRuleImpl.get("player_movement_check");

    // Appelle une méthode
    GameRule<Integer> PLAYERS_NETHER_PORTAL_CREATIVE_DELAY = GameRuleImpl.get("players_nether_portal_creative_delay");

    // Appelle une méthode
    GameRule<Integer> PLAYERS_NETHER_PORTAL_DEFAULT_DELAY = GameRuleImpl.get("players_nether_portal_default_delay");

    // Appelle une méthode
    GameRule<Integer> PLAYERS_SLEEPING_PERCENTAGE = GameRuleImpl.get("players_sleeping_percentage");

    // Appelle une méthode
    GameRule<Boolean> PROJECTILES_CAN_BREAK_BLOCKS = GameRuleImpl.get("projectiles_can_break_blocks");

    // Appelle une méthode
    GameRule<Boolean> PVP = GameRuleImpl.get("pvp");

    // Appelle une méthode
    GameRule<Boolean> RAIDS = GameRuleImpl.get("raids");

    // Appelle une méthode
    GameRule<Integer> RANDOM_TICK_SPEED = GameRuleImpl.get("random_tick_speed");

    // Appelle une méthode
    GameRule<Boolean> REDUCED_DEBUG_INFO = GameRuleImpl.get("reduced_debug_info");

    // Appelle une méthode
    GameRule<Integer> RESPAWN_RADIUS = GameRuleImpl.get("respawn_radius");

    // Appelle une méthode
    GameRule<Boolean> SEND_COMMAND_FEEDBACK = GameRuleImpl.get("send_command_feedback");

    // Appelle une méthode
    GameRule<Boolean> SHOW_ADVANCEMENT_MESSAGES = GameRuleImpl.get("show_advancement_messages");

    // Appelle une méthode
    GameRule<Boolean> SHOW_DEATH_MESSAGES = GameRuleImpl.get("show_death_messages");

    // Appelle une méthode
    GameRule<Boolean> SPAWNER_BLOCKS_WORK = GameRuleImpl.get("spawner_blocks_work");

    // Appelle une méthode
    GameRule<Boolean> SPAWN_MOBS = GameRuleImpl.get("spawn_mobs");

    // Appelle une méthode
    GameRule<Boolean> SPAWN_MONSTERS = GameRuleImpl.get("spawn_monsters");

    // Appelle une méthode
    GameRule<Boolean> SPAWN_PATROLS = GameRuleImpl.get("spawn_patrols");

    // Appelle une méthode
    GameRule<Boolean> SPAWN_PHANTOMS = GameRuleImpl.get("spawn_phantoms");

    // Appelle une méthode
    GameRule<Boolean> SPAWN_WANDERING_TRADERS = GameRuleImpl.get("spawn_wandering_traders");

    // Appelle une méthode
    GameRule<Boolean> SPAWN_WARDENS = GameRuleImpl.get("spawn_wardens");

    // Appelle une méthode
    GameRule<Boolean> SPECTATORS_GENERATE_CHUNKS = GameRuleImpl.get("spectators_generate_chunks");

    // Appelle une méthode
    GameRule<Boolean> SPREAD_VINES = GameRuleImpl.get("spread_vines");

    // Appelle une méthode
    GameRule<Boolean> TNT_EXPLODES = GameRuleImpl.get("tnt_explodes");

    // Appelle une méthode
    GameRule<Boolean> TNT_EXPLOSION_DROP_DECAY = GameRuleImpl.get("tnt_explosion_drop_decay");

    // Appelle une méthode
    GameRule<Boolean> UNIVERSAL_ANGER = GameRuleImpl.get("universal_anger");

    // Appelle une méthode
    GameRule<Boolean> WATER_SOURCE_CONVERSION = GameRuleImpl.get("water_source_conversion");
// Fin d'un bloc/d'une expression
}
