// Déclaration du paquet de ce fichier
package net.minestom.server.instance.block.banner;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link BannerPattern}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface BannerPatterns permits BannerPattern {
    // Appelle une méthode
    RegistryKey<BannerPattern> BORDER = RegistryKey.unsafeOf("border");

    // Appelle une méthode
    RegistryKey<BannerPattern> SQUARE_BOTTOM_RIGHT = RegistryKey.unsafeOf("square_bottom_right");

    // Appelle une méthode
    RegistryKey<BannerPattern> STRIPE_RIGHT = RegistryKey.unsafeOf("stripe_right");

    // Appelle une méthode
    RegistryKey<BannerPattern> RHOMBUS = RegistryKey.unsafeOf("rhombus");

    // Appelle une méthode
    RegistryKey<BannerPattern> FLOW = RegistryKey.unsafeOf("flow");

    // Appelle une méthode
    RegistryKey<BannerPattern> TRIANGLES_TOP = RegistryKey.unsafeOf("triangles_top");

    // Appelle une méthode
    RegistryKey<BannerPattern> GRADIENT = RegistryKey.unsafeOf("gradient");

    // Appelle une méthode
    RegistryKey<BannerPattern> GLOBE = RegistryKey.unsafeOf("globe");

    // Appelle une méthode
    RegistryKey<BannerPattern> STRIPE_BOTTOM = RegistryKey.unsafeOf("stripe_bottom");

    // Appelle une méthode
    RegistryKey<BannerPattern> MOJANG = RegistryKey.unsafeOf("mojang");

    // Appelle une méthode
    RegistryKey<BannerPattern> STRIPE_MIDDLE = RegistryKey.unsafeOf("stripe_middle");

    // Appelle une méthode
    RegistryKey<BannerPattern> FLOWER = RegistryKey.unsafeOf("flower");

    // Appelle une méthode
    RegistryKey<BannerPattern> DIAGONAL_UP_RIGHT = RegistryKey.unsafeOf("diagonal_up_right");

    // Appelle une méthode
    RegistryKey<BannerPattern> CIRCLE = RegistryKey.unsafeOf("circle");

    // Appelle une méthode
    RegistryKey<BannerPattern> HALF_HORIZONTAL = RegistryKey.unsafeOf("half_horizontal");

    // Appelle une méthode
    RegistryKey<BannerPattern> TRIANGLE_BOTTOM = RegistryKey.unsafeOf("triangle_bottom");

    // Appelle une méthode
    RegistryKey<BannerPattern> BRICKS = RegistryKey.unsafeOf("bricks");

    // Appelle une méthode
    RegistryKey<BannerPattern> CURLY_BORDER = RegistryKey.unsafeOf("curly_border");

    // Appelle une méthode
    RegistryKey<BannerPattern> PIGLIN = RegistryKey.unsafeOf("piglin");

    // Appelle une méthode
    RegistryKey<BannerPattern> BASE = RegistryKey.unsafeOf("base");

    // Appelle une méthode
    RegistryKey<BannerPattern> STRIPE_CENTER = RegistryKey.unsafeOf("stripe_center");

    // Appelle une méthode
    RegistryKey<BannerPattern> SQUARE_BOTTOM_LEFT = RegistryKey.unsafeOf("square_bottom_left");

    // Appelle une méthode
    RegistryKey<BannerPattern> SQUARE_TOP_RIGHT = RegistryKey.unsafeOf("square_top_right");

    // Appelle une méthode
    RegistryKey<BannerPattern> STRIPE_DOWNRIGHT = RegistryKey.unsafeOf("stripe_downright");

    // Appelle une méthode
    RegistryKey<BannerPattern> GUSTER = RegistryKey.unsafeOf("guster");

    // Appelle une méthode
    RegistryKey<BannerPattern> GRADIENT_UP = RegistryKey.unsafeOf("gradient_up");

    // Appelle une méthode
    RegistryKey<BannerPattern> DIAGONAL_RIGHT = RegistryKey.unsafeOf("diagonal_right");

    // Appelle une méthode
    RegistryKey<BannerPattern> HALF_VERTICAL_RIGHT = RegistryKey.unsafeOf("half_vertical_right");

    // Appelle une méthode
    RegistryKey<BannerPattern> SMALL_STRIPES = RegistryKey.unsafeOf("small_stripes");

    // Appelle une méthode
    RegistryKey<BannerPattern> DIAGONAL_LEFT = RegistryKey.unsafeOf("diagonal_left");

    // Appelle une méthode
    RegistryKey<BannerPattern> CROSS = RegistryKey.unsafeOf("cross");

    // Appelle une méthode
    RegistryKey<BannerPattern> STRIPE_DOWNLEFT = RegistryKey.unsafeOf("stripe_downleft");

    // Appelle une méthode
    RegistryKey<BannerPattern> SKULL = RegistryKey.unsafeOf("skull");

    // Appelle une méthode
    RegistryKey<BannerPattern> TRIANGLE_TOP = RegistryKey.unsafeOf("triangle_top");

    // Appelle une méthode
    RegistryKey<BannerPattern> HALF_VERTICAL = RegistryKey.unsafeOf("half_vertical");

    // Appelle une méthode
    RegistryKey<BannerPattern> DIAGONAL_UP_LEFT = RegistryKey.unsafeOf("diagonal_up_left");

    // Appelle une méthode
    RegistryKey<BannerPattern> STRIPE_TOP = RegistryKey.unsafeOf("stripe_top");

    // Appelle une méthode
    RegistryKey<BannerPattern> SQUARE_TOP_LEFT = RegistryKey.unsafeOf("square_top_left");

    // Appelle une méthode
    RegistryKey<BannerPattern> HALF_HORIZONTAL_BOTTOM = RegistryKey.unsafeOf("half_horizontal_bottom");

    // Appelle une méthode
    RegistryKey<BannerPattern> CREEPER = RegistryKey.unsafeOf("creeper");

    // Appelle une méthode
    RegistryKey<BannerPattern> STRIPE_LEFT = RegistryKey.unsafeOf("stripe_left");

    // Appelle une méthode
    RegistryKey<BannerPattern> TRIANGLES_BOTTOM = RegistryKey.unsafeOf("triangles_bottom");

    // Appelle une méthode
    RegistryKey<BannerPattern> STRAIGHT_CROSS = RegistryKey.unsafeOf("straight_cross");
// Fin d'un bloc/d'une expression
}
