// Package declaration for this file
package net.minestom.server.recipe;

// Import of a required class
import java.util.Arrays;
// Import of a required class
import java.util.Map;
// Import of a required class
import java.util.function.Function;
// Import of a required class
import java.util.stream.Collectors;
// Import of a required class
import net.kyori.adventure.key.Key;
// Import of a required class
import net.minestom.server.codec.Codec;
// Import of a required class
import net.minestom.server.network.NetworkBuffer;
// Import of a required class
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by RecipeTypeGenerator
 */
// Type declaration (class/interface/enum/record)
public enum RecipeType implements StaticProtocolObject<RecipeType> {
    // Code statement
    CRAFTING("crafting"),

    // Code statement
    SMELTING("smelting"),

    // Code statement
    BLASTING("blasting"),

    // Code statement
    SMOKING("smoking"),

    // Code statement
    CAMPFIRE_COOKING("campfire_cooking"),

    // Code statement
    STONECUTTING("stonecutting"),

    // Calls a method
    SMITHING("smithing");

    // Calls a method
    private static final Map<Key, RecipeType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(RecipeType::key, Function.identity()));

    // Calls a method
    public static final NetworkBuffer.Type<RecipeType> NETWORK_TYPE = NetworkBuffer.Enum(RecipeType.class);

    // Calls a method
    public static final Codec<RecipeType> CODEC = Codec.KEY.transform(BY_KEY::get, RecipeType::key);

    // Code statement
    private final Key key;

    // Start of a method/block
    RecipeType(String key) {
        // Access to the current/parent object
        this.key = Key.key(key);
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public Key key() {
        // Returns a value to the caller
        return this.key;
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public int id() {
        // Returns a value to the caller
        return this.ordinal();
    // End of a block/expression
    }
// End of a block/expression
}
