// Package declaration for this file
package net.minestom.server.recipe;

// Import of a required class
import java.util.Arrays;
// Import of a required class
import java.util.Map;
// Import of a required class
import java.util.function.Function;
// Import of a required class
import java.util.stream.Collectors;
// Import of a required class
import net.kyori.adventure.key.Key;
// Import of a required class
import net.minestom.server.codec.Codec;
// Import of a required class
import net.minestom.server.network.NetworkBuffer;
// Import of a required class
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Type declaration (class/interface/enum/record)
public enum RecipeBookCategory implements StaticProtocolObject<RecipeBookCategory> {
    // Code statement
    CRAFTING_BUILDING_BLOCKS("crafting_building_blocks"),

    // Code statement
    CRAFTING_REDSTONE("crafting_redstone"),

    // Code statement
    CRAFTING_EQUIPMENT("crafting_equipment"),

    // Code statement
    CRAFTING_MISC("crafting_misc"),

    // Code statement
    FURNACE_FOOD("furnace_food"),

    // Code statement
    FURNACE_BLOCKS("furnace_blocks"),

    // Code statement
    FURNACE_MISC("furnace_misc"),

    // Code statement
    BLAST_FURNACE_BLOCKS("blast_furnace_blocks"),

    // Code statement
    BLAST_FURNACE_MISC("blast_furnace_misc"),

    // Code statement
    SMOKER_FOOD("smoker_food"),

    // Code statement
    STONECUTTER("stonecutter"),

    // Code statement
    SMITHING("smithing"),

    // Calls a method
    CAMPFIRE("campfire");

    // Calls a method
    private static final Map<Key, RecipeBookCategory> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(RecipeBookCategory::key, Function.identity()));

    // Calls a method
    public static final NetworkBuffer.Type<RecipeBookCategory> NETWORK_TYPE = NetworkBuffer.Enum(RecipeBookCategory.class);

    // Calls a method
    public static final Codec<RecipeBookCategory> CODEC = Codec.KEY.transform(BY_KEY::get, RecipeBookCategory::key);

    // Code statement
    private final Key key;

    // Start of a method/block
    RecipeBookCategory(String key) {
        // Access to the current/parent object
        this.key = Key.key(key);
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public Key key() {
        // Returns a value to the caller
        return this.key;
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public int id() {
        // Returns a value to the caller
        return this.ordinal();
    // End of a block/expression
    }
// End of a block/expression
}
