// Déclaration du paquet de ce fichier
package net.minestom.server.recipe;

// Import d'une classe nécessaire
import java.util.Arrays;
// Import d'une classe nécessaire
import java.util.Map;
// Import d'une classe nécessaire
import java.util.function.Function;
// Import d'une classe nécessaire
import java.util.stream.Collectors;
// Import d'une classe nécessaire
import net.kyori.adventure.key.Key;
// Import d'une classe nécessaire
import net.minestom.server.codec.Codec;
// Import d'une classe nécessaire
import net.minestom.server.network.NetworkBuffer;
// Import d'une classe nécessaire
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Déclaration de type (classe/interface/enum/record)
public enum RecipeBookCategory implements StaticProtocolObject<RecipeBookCategory> {
    // Instruction de code
    CRAFTING_BUILDING_BLOCKS("crafting_building_blocks"),

    // Instruction de code
    CRAFTING_REDSTONE("crafting_redstone"),

    // Instruction de code
    CRAFTING_EQUIPMENT("crafting_equipment"),

    // Instruction de code
    CRAFTING_MISC("crafting_misc"),

    // Instruction de code
    FURNACE_FOOD("furnace_food"),

    // Instruction de code
    FURNACE_BLOCKS("furnace_blocks"),

    // Instruction de code
    FURNACE_MISC("furnace_misc"),

    // Instruction de code
    BLAST_FURNACE_BLOCKS("blast_furnace_blocks"),

    // Instruction de code
    BLAST_FURNACE_MISC("blast_furnace_misc"),

    // Instruction de code
    SMOKER_FOOD("smoker_food"),

    // Instruction de code
    STONECUTTER("stonecutter"),

    // Instruction de code
    SMITHING("smithing"),

    // Appelle une méthode
    CAMPFIRE("campfire");

    // Appelle une méthode
    private static final Map<Key, RecipeBookCategory> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(RecipeBookCategory::key, Function.identity()));

    // Appelle une méthode
    public static final NetworkBuffer.Type<RecipeBookCategory> NETWORK_TYPE = NetworkBuffer.Enum(RecipeBookCategory.class);

    // Appelle une méthode
    public static final Codec<RecipeBookCategory> CODEC = Codec.KEY.transform(BY_KEY::get, RecipeBookCategory::key);

    // Instruction de code
    private final Key key;

    // Début d'une méthode/d'un bloc
    RecipeBookCategory(String key) {
        // Accès à l'objet courant/parent
        this.key = Key.key(key);
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public Key key() {
        // Renvoie une valeur à l'appelant
        return this.key;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public int id() {
        // Renvoie une valeur à l'appelant
        return this.ordinal();
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
