// Déclaration du paquet de ce fichier
package net.minestom.server.recipe;

// Import d'une classe nécessaire
import java.util.Arrays;
// Import d'une classe nécessaire
import java.util.Map;
// Import d'une classe nécessaire
import java.util.function.Function;
// Import d'une classe nécessaire
import java.util.stream.Collectors;
// Import d'une classe nécessaire
import net.kyori.adventure.key.Key;
// Import d'une classe nécessaire
import net.minestom.server.codec.Codec;
// Import d'une classe nécessaire
import net.minestom.server.network.NetworkBuffer;
// Import d'une classe nécessaire
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by RecipeTypeGenerator
 */
// Déclaration de type (classe/interface/enum/record)
public enum RecipeType implements StaticProtocolObject<RecipeType> {
    // Instruction de code
    CRAFTING("crafting"),

    // Instruction de code
    SMELTING("smelting"),

    // Instruction de code
    BLASTING("blasting"),

    // Instruction de code
    SMOKING("smoking"),

    // Instruction de code
    CAMPFIRE_COOKING("campfire_cooking"),

    // Instruction de code
    STONECUTTING("stonecutting"),

    // Appelle une méthode
    SMITHING("smithing");

    // Appelle une méthode
    private static final Map<Key, RecipeType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(RecipeType::key, Function.identity()));

    // Appelle une méthode
    public static final NetworkBuffer.Type<RecipeType> NETWORK_TYPE = NetworkBuffer.Enum(RecipeType.class);

    // Appelle une méthode
    public static final Codec<RecipeType> CODEC = Codec.KEY.transform(BY_KEY::get, RecipeType::key);

    // Instruction de code
    private final Key key;

    // Début d'une méthode/d'un bloc
    RecipeType(String key) {
        // Accès à l'objet courant/parent
        this.key = Key.key(key);
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public Key key() {
        // Renvoie une valeur à l'appelant
        return this.key;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public int id() {
        // Renvoie une valeur à l'appelant
        return this.ordinal();
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
