// Package declaration for this file
package net.minestom.server.entity;

/**
 * This class contains all the generated constants for {@link EntityType}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface EntityTypes permits EntityType {
    // Calls a method
    EntityType ACACIA_BOAT = EntityTypeImpl.get("acacia_boat");

    // Calls a method
    EntityType ACACIA_CHEST_BOAT = EntityTypeImpl.get("acacia_chest_boat");

    // Calls a method
    EntityType ALLAY = EntityTypeImpl.get("allay");

    // Calls a method
    EntityType AREA_EFFECT_CLOUD = EntityTypeImpl.get("area_effect_cloud");

    // Calls a method
    EntityType ARMADILLO = EntityTypeImpl.get("armadillo");

    // Calls a method
    EntityType ARMOR_STAND = EntityTypeImpl.get("armor_stand");

    // Calls a method
    EntityType ARROW = EntityTypeImpl.get("arrow");

    // Calls a method
    EntityType AXOLOTL = EntityTypeImpl.get("axolotl");

    // Calls a method
    EntityType BAMBOO_CHEST_RAFT = EntityTypeImpl.get("bamboo_chest_raft");

    // Calls a method
    EntityType BAMBOO_RAFT = EntityTypeImpl.get("bamboo_raft");

    // Calls a method
    EntityType BAT = EntityTypeImpl.get("bat");

    // Calls a method
    EntityType BEE = EntityTypeImpl.get("bee");

    // Calls a method
    EntityType BIRCH_BOAT = EntityTypeImpl.get("birch_boat");

    // Calls a method
    EntityType BIRCH_CHEST_BOAT = EntityTypeImpl.get("birch_chest_boat");

    // Calls a method
    EntityType BLAZE = EntityTypeImpl.get("blaze");

    // Calls a method
    EntityType BLOCK_DISPLAY = EntityTypeImpl.get("block_display");

    // Calls a method
    EntityType BOGGED = EntityTypeImpl.get("bogged");

    // Calls a method
    EntityType BREEZE = EntityTypeImpl.get("breeze");

    // Calls a method
    EntityType BREEZE_WIND_CHARGE = EntityTypeImpl.get("breeze_wind_charge");

    // Calls a method
    EntityType CAMEL = EntityTypeImpl.get("camel");

    // Calls a method
    EntityType CAMEL_HUSK = EntityTypeImpl.get("camel_husk");

    // Calls a method
    EntityType CAT = EntityTypeImpl.get("cat");

    // Calls a method
    EntityType CAVE_SPIDER = EntityTypeImpl.get("cave_spider");

    // Calls a method
    EntityType CHERRY_BOAT = EntityTypeImpl.get("cherry_boat");

    // Calls a method
    EntityType CHERRY_CHEST_BOAT = EntityTypeImpl.get("cherry_chest_boat");

    // Calls a method
    EntityType CHEST_MINECART = EntityTypeImpl.get("chest_minecart");

    // Calls a method
    EntityType CHICKEN = EntityTypeImpl.get("chicken");

    // Calls a method
    EntityType COD = EntityTypeImpl.get("cod");

    // Calls a method
    EntityType COPPER_GOLEM = EntityTypeImpl.get("copper_golem");

    // Calls a method
    EntityType COMMAND_BLOCK_MINECART = EntityTypeImpl.get("command_block_minecart");

    // Calls a method
    EntityType COW = EntityTypeImpl.get("cow");

    // Calls a method
    EntityType CREAKING = EntityTypeImpl.get("creaking");

    // Calls a method
    EntityType CREEPER = EntityTypeImpl.get("creeper");

    // Calls a method
    EntityType DARK_OAK_BOAT = EntityTypeImpl.get("dark_oak_boat");

    // Calls a method
    EntityType DARK_OAK_CHEST_BOAT = EntityTypeImpl.get("dark_oak_chest_boat");

    // Calls a method
    EntityType DOLPHIN = EntityTypeImpl.get("dolphin");

    // Calls a method
    EntityType DONKEY = EntityTypeImpl.get("donkey");

    // Calls a method
    EntityType DRAGON_FIREBALL = EntityTypeImpl.get("dragon_fireball");

    // Calls a method
    EntityType DROWNED = EntityTypeImpl.get("drowned");

    // Calls a method
    EntityType EGG = EntityTypeImpl.get("egg");

    // Calls a method
    EntityType ELDER_GUARDIAN = EntityTypeImpl.get("elder_guardian");

    // Calls a method
    EntityType ENDERMAN = EntityTypeImpl.get("enderman");

    // Calls a method
    EntityType ENDERMITE = EntityTypeImpl.get("endermite");

    // Calls a method
    EntityType ENDER_DRAGON = EntityTypeImpl.get("ender_dragon");

    // Calls a method
    EntityType ENDER_PEARL = EntityTypeImpl.get("ender_pearl");

    // Calls a method
    EntityType END_CRYSTAL = EntityTypeImpl.get("end_crystal");

    // Calls a method
    EntityType EVOKER = EntityTypeImpl.get("evoker");

    // Calls a method
    EntityType EVOKER_FANGS = EntityTypeImpl.get("evoker_fangs");

    // Calls a method
    EntityType EXPERIENCE_BOTTLE = EntityTypeImpl.get("experience_bottle");

    // Calls a method
    EntityType EXPERIENCE_ORB = EntityTypeImpl.get("experience_orb");

    // Calls a method
    EntityType EYE_OF_ENDER = EntityTypeImpl.get("eye_of_ender");

    // Calls a method
    EntityType FALLING_BLOCK = EntityTypeImpl.get("falling_block");

    // Calls a method
    EntityType FIREBALL = EntityTypeImpl.get("fireball");

    // Calls a method
    EntityType FIREWORK_ROCKET = EntityTypeImpl.get("firework_rocket");

    // Calls a method
    EntityType FOX = EntityTypeImpl.get("fox");

    // Calls a method
    EntityType FROG = EntityTypeImpl.get("frog");

    // Calls a method
    EntityType FURNACE_MINECART = EntityTypeImpl.get("furnace_minecart");

    // Calls a method
    EntityType GHAST = EntityTypeImpl.get("ghast");

    // Calls a method
    EntityType HAPPY_GHAST = EntityTypeImpl.get("happy_ghast");

    // Calls a method
    EntityType GIANT = EntityTypeImpl.get("giant");

    // Calls a method
    EntityType GLOW_ITEM_FRAME = EntityTypeImpl.get("glow_item_frame");

    // Calls a method
    EntityType GLOW_SQUID = EntityTypeImpl.get("glow_squid");

    // Calls a method
    EntityType GOAT = EntityTypeImpl.get("goat");

    // Calls a method
    EntityType GUARDIAN = EntityTypeImpl.get("guardian");

    // Calls a method
    EntityType HOGLIN = EntityTypeImpl.get("hoglin");

    // Calls a method
    EntityType HOPPER_MINECART = EntityTypeImpl.get("hopper_minecart");

    // Calls a method
    EntityType HORSE = EntityTypeImpl.get("horse");

    // Calls a method
    EntityType HUSK = EntityTypeImpl.get("husk");

    // Calls a method
    EntityType ILLUSIONER = EntityTypeImpl.get("illusioner");

    // Calls a method
    EntityType INTERACTION = EntityTypeImpl.get("interaction");

    // Calls a method
    EntityType IRON_GOLEM = EntityTypeImpl.get("iron_golem");

    // Calls a method
    EntityType ITEM = EntityTypeImpl.get("item");

    // Calls a method
    EntityType ITEM_DISPLAY = EntityTypeImpl.get("item_display");

    // Calls a method
    EntityType ITEM_FRAME = EntityTypeImpl.get("item_frame");

    // Calls a method
    EntityType JUNGLE_BOAT = EntityTypeImpl.get("jungle_boat");

    // Calls a method
    EntityType JUNGLE_CHEST_BOAT = EntityTypeImpl.get("jungle_chest_boat");

    // Calls a method
    EntityType LEASH_KNOT = EntityTypeImpl.get("leash_knot");

    // Calls a method
    EntityType LIGHTNING_BOLT = EntityTypeImpl.get("lightning_bolt");

    // Calls a method
    EntityType LLAMA = EntityTypeImpl.get("llama");

    // Calls a method
    EntityType LLAMA_SPIT = EntityTypeImpl.get("llama_spit");

    // Calls a method
    EntityType MAGMA_CUBE = EntityTypeImpl.get("magma_cube");

    // Calls a method
    EntityType MANGROVE_BOAT = EntityTypeImpl.get("mangrove_boat");

    // Calls a method
    EntityType MANGROVE_CHEST_BOAT = EntityTypeImpl.get("mangrove_chest_boat");

    // Calls a method
    EntityType MANNEQUIN = EntityTypeImpl.get("mannequin");

    // Calls a method
    EntityType MARKER = EntityTypeImpl.get("marker");

    // Calls a method
    EntityType MINECART = EntityTypeImpl.get("minecart");

    // Calls a method
    EntityType MOOSHROOM = EntityTypeImpl.get("mooshroom");

    // Calls a method
    EntityType MULE = EntityTypeImpl.get("mule");

    // Calls a method
    EntityType NAUTILUS = EntityTypeImpl.get("nautilus");

    // Calls a method
    EntityType OAK_BOAT = EntityTypeImpl.get("oak_boat");

    // Calls a method
    EntityType OAK_CHEST_BOAT = EntityTypeImpl.get("oak_chest_boat");

    // Calls a method
    EntityType OCELOT = EntityTypeImpl.get("ocelot");

    // Calls a method
    EntityType OMINOUS_ITEM_SPAWNER = EntityTypeImpl.get("ominous_item_spawner");

    // Calls a method
    EntityType PAINTING = EntityTypeImpl.get("painting");

    // Calls a method
    EntityType PALE_OAK_BOAT = EntityTypeImpl.get("pale_oak_boat");

    // Calls a method
    EntityType PALE_OAK_CHEST_BOAT = EntityTypeImpl.get("pale_oak_chest_boat");

    // Calls a method
    EntityType PANDA = EntityTypeImpl.get("panda");

    // Calls a method
    EntityType PARCHED = EntityTypeImpl.get("parched");

    // Calls a method
    EntityType PARROT = EntityTypeImpl.get("parrot");

    // Calls a method
    EntityType PHANTOM = EntityTypeImpl.get("phantom");

    // Calls a method
    EntityType PIG = EntityTypeImpl.get("pig");

    // Calls a method
    EntityType PIGLIN = EntityTypeImpl.get("piglin");

    // Calls a method
    EntityType PIGLIN_BRUTE = EntityTypeImpl.get("piglin_brute");

    // Calls a method
    EntityType PILLAGER = EntityTypeImpl.get("pillager");

    // Calls a method
    EntityType POLAR_BEAR = EntityTypeImpl.get("polar_bear");

    // Calls a method
    EntityType SPLASH_POTION = EntityTypeImpl.get("splash_potion");

    // Calls a method
    EntityType LINGERING_POTION = EntityTypeImpl.get("lingering_potion");

    // Calls a method
    EntityType PUFFERFISH = EntityTypeImpl.get("pufferfish");

    // Calls a method
    EntityType RABBIT = EntityTypeImpl.get("rabbit");

    // Calls a method
    EntityType RAVAGER = EntityTypeImpl.get("ravager");

    // Calls a method
    EntityType SALMON = EntityTypeImpl.get("salmon");

    // Calls a method
    EntityType SHEEP = EntityTypeImpl.get("sheep");

    // Calls a method
    EntityType SHULKER = EntityTypeImpl.get("shulker");

    // Calls a method
    EntityType SHULKER_BULLET = EntityTypeImpl.get("shulker_bullet");

    // Calls a method
    EntityType SILVERFISH = EntityTypeImpl.get("silverfish");

    // Calls a method
    EntityType SKELETON = EntityTypeImpl.get("skeleton");

    // Calls a method
    EntityType SKELETON_HORSE = EntityTypeImpl.get("skeleton_horse");

    // Calls a method
    EntityType SLIME = EntityTypeImpl.get("slime");

    // Calls a method
    EntityType SMALL_FIREBALL = EntityTypeImpl.get("small_fireball");

    // Calls a method
    EntityType SNIFFER = EntityTypeImpl.get("sniffer");

    // Calls a method
    EntityType SNOWBALL = EntityTypeImpl.get("snowball");

    // Calls a method
    EntityType SNOW_GOLEM = EntityTypeImpl.get("snow_golem");

    // Calls a method
    EntityType SPAWNER_MINECART = EntityTypeImpl.get("spawner_minecart");

    // Calls a method
    EntityType SPECTRAL_ARROW = EntityTypeImpl.get("spectral_arrow");

    // Calls a method
    EntityType SPIDER = EntityTypeImpl.get("spider");

    // Calls a method
    EntityType SPRUCE_BOAT = EntityTypeImpl.get("spruce_boat");

    // Calls a method
    EntityType SPRUCE_CHEST_BOAT = EntityTypeImpl.get("spruce_chest_boat");

    // Calls a method
    EntityType SQUID = EntityTypeImpl.get("squid");

    // Calls a method
    EntityType STRAY = EntityTypeImpl.get("stray");

    // Calls a method
    EntityType STRIDER = EntityTypeImpl.get("strider");

    // Calls a method
    EntityType TADPOLE = EntityTypeImpl.get("tadpole");

    // Calls a method
    EntityType TEXT_DISPLAY = EntityTypeImpl.get("text_display");

    // Calls a method
    EntityType TNT = EntityTypeImpl.get("tnt");

    // Calls a method
    EntityType TNT_MINECART = EntityTypeImpl.get("tnt_minecart");

    // Calls a method
    EntityType TRADER_LLAMA = EntityTypeImpl.get("trader_llama");

    // Calls a method
    EntityType TRIDENT = EntityTypeImpl.get("trident");

    // Calls a method
    EntityType TROPICAL_FISH = EntityTypeImpl.get("tropical_fish");

    // Calls a method
    EntityType TURTLE = EntityTypeImpl.get("turtle");

    // Calls a method
    EntityType VEX = EntityTypeImpl.get("vex");

    // Calls a method
    EntityType VILLAGER = EntityTypeImpl.get("villager");

    // Calls a method
    EntityType VINDICATOR = EntityTypeImpl.get("vindicator");

    // Calls a method
    EntityType WANDERING_TRADER = EntityTypeImpl.get("wandering_trader");

    // Calls a method
    EntityType WARDEN = EntityTypeImpl.get("warden");

    // Calls a method
    EntityType WIND_CHARGE = EntityTypeImpl.get("wind_charge");

    // Calls a method
    EntityType WITCH = EntityTypeImpl.get("witch");

    // Calls a method
    EntityType WITHER = EntityTypeImpl.get("wither");

    // Calls a method
    EntityType WITHER_SKELETON = EntityTypeImpl.get("wither_skeleton");

    // Calls a method
    EntityType WITHER_SKULL = EntityTypeImpl.get("wither_skull");

    // Calls a method
    EntityType WOLF = EntityTypeImpl.get("wolf");

    // Calls a method
    EntityType ZOGLIN = EntityTypeImpl.get("zoglin");

    // Calls a method
    EntityType ZOMBIE = EntityTypeImpl.get("zombie");

    // Calls a method
    EntityType ZOMBIE_HORSE = EntityTypeImpl.get("zombie_horse");

    // Calls a method
    EntityType ZOMBIE_NAUTILUS = EntityTypeImpl.get("zombie_nautilus");

    // Calls a method
    EntityType ZOMBIE_VILLAGER = EntityTypeImpl.get("zombie_villager");

    // Calls a method
    EntityType ZOMBIFIED_PIGLIN = EntityTypeImpl.get("zombified_piglin");

    // Calls a method
    EntityType PLAYER = EntityTypeImpl.get("player");

    // Calls a method
    EntityType FISHING_BOBBER = EntityTypeImpl.get("fishing_bobber");
// End of a block/expression
}
