// Package declaration for this file
package net.minestom.server.entity;

// Import of a required class
import java.util.Arrays;
// Import of a required class
import java.util.Map;
// Import of a required class
import java.util.function.Function;
// Import of a required class
import java.util.stream.Collectors;
// Import of a required class
import net.kyori.adventure.key.Key;
// Import of a required class
import net.minestom.server.codec.Codec;
// Import of a required class
import net.minestom.server.network.NetworkBuffer;
// Import of a required class
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Type declaration (class/interface/enum/record)
public enum VillagerType implements StaticProtocolObject<VillagerType> {
    // Code statement
    DESERT("desert"),

    // Code statement
    JUNGLE("jungle"),

    // Code statement
    PLAINS("plains"),

    // Code statement
    SAVANNA("savanna"),

    // Code statement
    SNOW("snow"),

    // Code statement
    SWAMP("swamp"),

    // Calls a method
    TAIGA("taiga");

    // Calls a method
    private static final Map<Key, VillagerType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(VillagerType::key, Function.identity()));

    // Calls a method
    public static final NetworkBuffer.Type<VillagerType> NETWORK_TYPE = NetworkBuffer.Enum(VillagerType.class);

    // Calls a method
    public static final Codec<VillagerType> CODEC = Codec.KEY.transform(BY_KEY::get, VillagerType::key);

    // Code statement
    private final Key key;

    // Start of a method/block
    VillagerType(String key) {
        // Access to the current/parent object
        this.key = Key.key(key);
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public Key key() {
        // Returns a value to the caller
        return this.key;
    // End of a block/expression
    }

    // Annotation for the following element
    @Override
    // Start of a method/block
    public int id() {
        // Returns a value to the caller
        return this.ordinal();
    // End of a block/expression
    }
// End of a block/expression
}
