// Déclaration du paquet de ce fichier
package net.minestom.server.entity;

/**
 * This class contains all the generated constants for {@link VillagerProfession}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface VillagerProfessions permits VillagerProfession {
    // Appelle une méthode
    VillagerProfession NONE = VillagerProfessionImpl.get("none");

    // Appelle une méthode
    VillagerProfession ARMORER = VillagerProfessionImpl.get("armorer");

    // Appelle une méthode
    VillagerProfession BUTCHER = VillagerProfessionImpl.get("butcher");

    // Appelle une méthode
    VillagerProfession CARTOGRAPHER = VillagerProfessionImpl.get("cartographer");

    // Appelle une méthode
    VillagerProfession CLERIC = VillagerProfessionImpl.get("cleric");

    // Appelle une méthode
    VillagerProfession FARMER = VillagerProfessionImpl.get("farmer");

    // Appelle une méthode
    VillagerProfession FISHERMAN = VillagerProfessionImpl.get("fisherman");

    // Appelle une méthode
    VillagerProfession FLETCHER = VillagerProfessionImpl.get("fletcher");

    // Appelle une méthode
    VillagerProfession LEATHERWORKER = VillagerProfessionImpl.get("leatherworker");

    // Appelle une méthode
    VillagerProfession LIBRARIAN = VillagerProfessionImpl.get("librarian");

    // Appelle une méthode
    VillagerProfession MASON = VillagerProfessionImpl.get("mason");

    // Appelle une méthode
    VillagerProfession NITWIT = VillagerProfessionImpl.get("nitwit");

    // Appelle une méthode
    VillagerProfession SHEPHERD = VillagerProfessionImpl.get("shepherd");

    // Appelle une méthode
    VillagerProfession TOOLSMITH = VillagerProfessionImpl.get("toolsmith");

    // Appelle une méthode
    VillagerProfession WEAPONSMITH = VillagerProfessionImpl.get("weaponsmith");
// Fin d'un bloc/d'une expression
}
