// Package declaration for this file
package net.minestom.server.entity;

/**
 * This class contains all the generated constants for {@link VillagerProfession}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface VillagerProfessions permits VillagerProfession {
    // Calls a method
    VillagerProfession NONE = VillagerProfessionImpl.get("none");

    // Calls a method
    VillagerProfession ARMORER = VillagerProfessionImpl.get("armorer");

    // Calls a method
    VillagerProfession BUTCHER = VillagerProfessionImpl.get("butcher");

    // Calls a method
    VillagerProfession CARTOGRAPHER = VillagerProfessionImpl.get("cartographer");

    // Calls a method
    VillagerProfession CLERIC = VillagerProfessionImpl.get("cleric");

    // Calls a method
    VillagerProfession FARMER = VillagerProfessionImpl.get("farmer");

    // Calls a method
    VillagerProfession FISHERMAN = VillagerProfessionImpl.get("fisherman");

    // Calls a method
    VillagerProfession FLETCHER = VillagerProfessionImpl.get("fletcher");

    // Calls a method
    VillagerProfession LEATHERWORKER = VillagerProfessionImpl.get("leatherworker");

    // Calls a method
    VillagerProfession LIBRARIAN = VillagerProfessionImpl.get("librarian");

    // Calls a method
    VillagerProfession MASON = VillagerProfessionImpl.get("mason");

    // Calls a method
    VillagerProfession NITWIT = VillagerProfessionImpl.get("nitwit");

    // Calls a method
    VillagerProfession SHEPHERD = VillagerProfessionImpl.get("shepherd");

    // Calls a method
    VillagerProfession TOOLSMITH = VillagerProfessionImpl.get("toolsmith");

    // Calls a method
    VillagerProfession WEAPONSMITH = VillagerProfessionImpl.get("weaponsmith");
// End of a block/expression
}
