// Déclaration du paquet de ce fichier
package net.minestom.server.entity;

// Import d'une classe nécessaire
import java.util.Arrays;
// Import d'une classe nécessaire
import java.util.Map;
// Import d'une classe nécessaire
import java.util.function.Function;
// Import d'une classe nécessaire
import java.util.stream.Collectors;
// Import d'une classe nécessaire
import net.kyori.adventure.key.Key;
// Import d'une classe nécessaire
import net.minestom.server.codec.Codec;
// Import d'une classe nécessaire
import net.minestom.server.network.NetworkBuffer;
// Import d'une classe nécessaire
import net.minestom.server.registry.StaticProtocolObject;

/**
 * AUTOGENERATED by GenericEnumGenerator
 */
// Déclaration de type (classe/interface/enum/record)
public enum VillagerType implements StaticProtocolObject<VillagerType> {
    // Instruction de code
    DESERT("desert"),

    // Instruction de code
    JUNGLE("jungle"),

    // Instruction de code
    PLAINS("plains"),

    // Instruction de code
    SAVANNA("savanna"),

    // Instruction de code
    SNOW("snow"),

    // Instruction de code
    SWAMP("swamp"),

    // Appelle une méthode
    TAIGA("taiga");

    // Appelle une méthode
    private static final Map<Key, VillagerType> BY_KEY = Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(VillagerType::key, Function.identity()));

    // Appelle une méthode
    public static final NetworkBuffer.Type<VillagerType> NETWORK_TYPE = NetworkBuffer.Enum(VillagerType.class);

    // Appelle une méthode
    public static final Codec<VillagerType> CODEC = Codec.KEY.transform(BY_KEY::get, VillagerType::key);

    // Instruction de code
    private final Key key;

    // Début d'une méthode/d'un bloc
    VillagerType(String key) {
        // Accès à l'objet courant/parent
        this.key = Key.key(key);
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public Key key() {
        // Renvoie une valeur à l'appelant
        return this.key;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public int id() {
        // Renvoie une valeur à l'appelant
        return this.ordinal();
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
