// Package declaration for this file
package net.minestom.server.statistic;

/**
 * This class contains all the generated constants for {@link StatisticType}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface StatisticTypes permits StatisticType {
    // Calls a method
    StatisticType LEAVE_GAME = StatisticTypeImpl.get("leave_game");

    // Calls a method
    StatisticType PLAY_TIME = StatisticTypeImpl.get("play_time");

    // Calls a method
    StatisticType TOTAL_WORLD_TIME = StatisticTypeImpl.get("total_world_time");

    // Calls a method
    StatisticType TIME_SINCE_DEATH = StatisticTypeImpl.get("time_since_death");

    // Calls a method
    StatisticType TIME_SINCE_REST = StatisticTypeImpl.get("time_since_rest");

    // Calls a method
    StatisticType SNEAK_TIME = StatisticTypeImpl.get("sneak_time");

    // Calls a method
    StatisticType WALK_ONE_CM = StatisticTypeImpl.get("walk_one_cm");

    // Calls a method
    StatisticType CROUCH_ONE_CM = StatisticTypeImpl.get("crouch_one_cm");

    // Calls a method
    StatisticType SPRINT_ONE_CM = StatisticTypeImpl.get("sprint_one_cm");

    // Calls a method
    StatisticType WALK_ON_WATER_ONE_CM = StatisticTypeImpl.get("walk_on_water_one_cm");

    // Calls a method
    StatisticType FALL_ONE_CM = StatisticTypeImpl.get("fall_one_cm");

    // Calls a method
    StatisticType CLIMB_ONE_CM = StatisticTypeImpl.get("climb_one_cm");

    // Calls a method
    StatisticType FLY_ONE_CM = StatisticTypeImpl.get("fly_one_cm");

    // Calls a method
    StatisticType WALK_UNDER_WATER_ONE_CM = StatisticTypeImpl.get("walk_under_water_one_cm");

    // Calls a method
    StatisticType MINECART_ONE_CM = StatisticTypeImpl.get("minecart_one_cm");

    // Calls a method
    StatisticType BOAT_ONE_CM = StatisticTypeImpl.get("boat_one_cm");

    // Calls a method
    StatisticType PIG_ONE_CM = StatisticTypeImpl.get("pig_one_cm");

    // Calls a method
    StatisticType HAPPY_GHAST_ONE_CM = StatisticTypeImpl.get("happy_ghast_one_cm");

    // Calls a method
    StatisticType HORSE_ONE_CM = StatisticTypeImpl.get("horse_one_cm");

    // Calls a method
    StatisticType AVIATE_ONE_CM = StatisticTypeImpl.get("aviate_one_cm");

    // Calls a method
    StatisticType SWIM_ONE_CM = StatisticTypeImpl.get("swim_one_cm");

    // Calls a method
    StatisticType STRIDER_ONE_CM = StatisticTypeImpl.get("strider_one_cm");

    // Calls a method
    StatisticType NAUTILUS_ONE_CM = StatisticTypeImpl.get("nautilus_one_cm");

    // Calls a method
    StatisticType JUMP = StatisticTypeImpl.get("jump");

    // Calls a method
    StatisticType DROP = StatisticTypeImpl.get("drop");

    // Calls a method
    StatisticType DAMAGE_DEALT = StatisticTypeImpl.get("damage_dealt");

    // Calls a method
    StatisticType DAMAGE_DEALT_ABSORBED = StatisticTypeImpl.get("damage_dealt_absorbed");

    // Calls a method
    StatisticType DAMAGE_DEALT_RESISTED = StatisticTypeImpl.get("damage_dealt_resisted");

    // Calls a method
    StatisticType DAMAGE_TAKEN = StatisticTypeImpl.get("damage_taken");

    // Calls a method
    StatisticType DAMAGE_BLOCKED_BY_SHIELD = StatisticTypeImpl.get("damage_blocked_by_shield");

    // Calls a method
    StatisticType DAMAGE_ABSORBED = StatisticTypeImpl.get("damage_absorbed");

    // Calls a method
    StatisticType DAMAGE_RESISTED = StatisticTypeImpl.get("damage_resisted");

    // Calls a method
    StatisticType DEATHS = StatisticTypeImpl.get("deaths");

    // Calls a method
    StatisticType MOB_KILLS = StatisticTypeImpl.get("mob_kills");

    // Calls a method
    StatisticType ANIMALS_BRED = StatisticTypeImpl.get("animals_bred");

    // Calls a method
    StatisticType PLAYER_KILLS = StatisticTypeImpl.get("player_kills");

    // Calls a method
    StatisticType FISH_CAUGHT = StatisticTypeImpl.get("fish_caught");

    // Calls a method
    StatisticType TALKED_TO_VILLAGER = StatisticTypeImpl.get("talked_to_villager");

    // Calls a method
    StatisticType TRADED_WITH_VILLAGER = StatisticTypeImpl.get("traded_with_villager");

    // Calls a method
    StatisticType EAT_CAKE_SLICE = StatisticTypeImpl.get("eat_cake_slice");

    // Calls a method
    StatisticType FILL_CAULDRON = StatisticTypeImpl.get("fill_cauldron");

    // Calls a method
    StatisticType USE_CAULDRON = StatisticTypeImpl.get("use_cauldron");

    // Calls a method
    StatisticType CLEAN_ARMOR = StatisticTypeImpl.get("clean_armor");

    // Calls a method
    StatisticType CLEAN_BANNER = StatisticTypeImpl.get("clean_banner");

    // Calls a method
    StatisticType CLEAN_SHULKER_BOX = StatisticTypeImpl.get("clean_shulker_box");

    // Calls a method
    StatisticType INTERACT_WITH_BREWINGSTAND = StatisticTypeImpl.get("interact_with_brewingstand");

    // Calls a method
    StatisticType INTERACT_WITH_BEACON = StatisticTypeImpl.get("interact_with_beacon");

    // Calls a method
    StatisticType INSPECT_DROPPER = StatisticTypeImpl.get("inspect_dropper");

    // Calls a method
    StatisticType INSPECT_HOPPER = StatisticTypeImpl.get("inspect_hopper");

    // Calls a method
    StatisticType INSPECT_DISPENSER = StatisticTypeImpl.get("inspect_dispenser");

    // Calls a method
    StatisticType PLAY_NOTEBLOCK = StatisticTypeImpl.get("play_noteblock");

    // Calls a method
    StatisticType TUNE_NOTEBLOCK = StatisticTypeImpl.get("tune_noteblock");

    // Calls a method
    StatisticType POT_FLOWER = StatisticTypeImpl.get("pot_flower");

    // Calls a method
    StatisticType TRIGGER_TRAPPED_CHEST = StatisticTypeImpl.get("trigger_trapped_chest");

    // Calls a method
    StatisticType OPEN_ENDERCHEST = StatisticTypeImpl.get("open_enderchest");

    // Calls a method
    StatisticType ENCHANT_ITEM = StatisticTypeImpl.get("enchant_item");

    // Calls a method
    StatisticType PLAY_RECORD = StatisticTypeImpl.get("play_record");

    // Calls a method
    StatisticType INTERACT_WITH_FURNACE = StatisticTypeImpl.get("interact_with_furnace");

    // Calls a method
    StatisticType INTERACT_WITH_CRAFTING_TABLE = StatisticTypeImpl.get("interact_with_crafting_table");

    // Calls a method
    StatisticType OPEN_CHEST = StatisticTypeImpl.get("open_chest");

    // Calls a method
    StatisticType SLEEP_IN_BED = StatisticTypeImpl.get("sleep_in_bed");

    // Calls a method
    StatisticType OPEN_SHULKER_BOX = StatisticTypeImpl.get("open_shulker_box");

    // Calls a method
    StatisticType OPEN_BARREL = StatisticTypeImpl.get("open_barrel");

    // Calls a method
    StatisticType INTERACT_WITH_BLAST_FURNACE = StatisticTypeImpl.get("interact_with_blast_furnace");

    // Calls a method
    StatisticType INTERACT_WITH_SMOKER = StatisticTypeImpl.get("interact_with_smoker");

    // Calls a method
    StatisticType INTERACT_WITH_LECTERN = StatisticTypeImpl.get("interact_with_lectern");

    // Calls a method
    StatisticType INTERACT_WITH_CAMPFIRE = StatisticTypeImpl.get("interact_with_campfire");

    // Calls a method
    StatisticType INTERACT_WITH_CARTOGRAPHY_TABLE = StatisticTypeImpl.get("interact_with_cartography_table");

    // Calls a method
    StatisticType INTERACT_WITH_LOOM = StatisticTypeImpl.get("interact_with_loom");

    // Calls a method
    StatisticType INTERACT_WITH_STONECUTTER = StatisticTypeImpl.get("interact_with_stonecutter");

    // Calls a method
    StatisticType BELL_RING = StatisticTypeImpl.get("bell_ring");

    // Calls a method
    StatisticType RAID_TRIGGER = StatisticTypeImpl.get("raid_trigger");

    // Calls a method
    StatisticType RAID_WIN = StatisticTypeImpl.get("raid_win");

    // Calls a method
    StatisticType INTERACT_WITH_ANVIL = StatisticTypeImpl.get("interact_with_anvil");

    // Calls a method
    StatisticType INTERACT_WITH_GRINDSTONE = StatisticTypeImpl.get("interact_with_grindstone");

    // Calls a method
    StatisticType TARGET_HIT = StatisticTypeImpl.get("target_hit");

    // Calls a method
    StatisticType INTERACT_WITH_SMITHING_TABLE = StatisticTypeImpl.get("interact_with_smithing_table");
// End of a block/expression
}
