// Package declaration for this file
package net.minestom.server.entity.metadata.animal.tameable;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link CatSoundVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface CatSoundVariants permits CatSoundVariant {
    // Calls a method
    RegistryKey<CatSoundVariant> CLASSIC = RegistryKey.unsafeOf("classic");

    // Calls a method
    RegistryKey<CatSoundVariant> ROYAL = RegistryKey.unsafeOf("royal");
// End of a block/expression
}
