// Déclaration du paquet de ce fichier
package net.minestom.server.entity.metadata.animal.tameable;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link CatSoundVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface CatSoundVariants permits CatSoundVariant {
    // Appelle une méthode
    RegistryKey<CatSoundVariant> CLASSIC = RegistryKey.unsafeOf("classic");

    // Appelle une méthode
    RegistryKey<CatSoundVariant> ROYAL = RegistryKey.unsafeOf("royal");
// Fin d'un bloc/d'une expression
}
