// Package declaration for this file
package net.minestom.server.entity.metadata.animal.tameable;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link CatVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface CatVariants permits CatVariant {
    // Calls a method
    RegistryKey<CatVariant> BLACK = RegistryKey.unsafeOf("black");

    // Calls a method
    RegistryKey<CatVariant> ALL_BLACK = RegistryKey.unsafeOf("all_black");

    // Calls a method
    RegistryKey<CatVariant> CALICO = RegistryKey.unsafeOf("calico");

    // Calls a method
    RegistryKey<CatVariant> JELLIE = RegistryKey.unsafeOf("jellie");

    // Calls a method
    RegistryKey<CatVariant> TABBY = RegistryKey.unsafeOf("tabby");

    // Calls a method
    RegistryKey<CatVariant> RAGDOLL = RegistryKey.unsafeOf("ragdoll");

    // Calls a method
    RegistryKey<CatVariant> SIAMESE = RegistryKey.unsafeOf("siamese");

    // Calls a method
    RegistryKey<CatVariant> PERSIAN = RegistryKey.unsafeOf("persian");

    // Calls a method
    RegistryKey<CatVariant> BRITISH_SHORTHAIR = RegistryKey.unsafeOf("british_shorthair");

    // Calls a method
    RegistryKey<CatVariant> WHITE = RegistryKey.unsafeOf("white");

    // Calls a method
    RegistryKey<CatVariant> RED = RegistryKey.unsafeOf("red");
// End of a block/expression
}
