// Déclaration du paquet de ce fichier
package net.minestom.server.entity.metadata.animal.tameable;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link CatVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface CatVariants permits CatVariant {
    // Appelle une méthode
    RegistryKey<CatVariant> BLACK = RegistryKey.unsafeOf("black");

    // Appelle une méthode
    RegistryKey<CatVariant> ALL_BLACK = RegistryKey.unsafeOf("all_black");

    // Appelle une méthode
    RegistryKey<CatVariant> CALICO = RegistryKey.unsafeOf("calico");

    // Appelle une méthode
    RegistryKey<CatVariant> JELLIE = RegistryKey.unsafeOf("jellie");

    // Appelle une méthode
    RegistryKey<CatVariant> TABBY = RegistryKey.unsafeOf("tabby");

    // Appelle une méthode
    RegistryKey<CatVariant> RAGDOLL = RegistryKey.unsafeOf("ragdoll");

    // Appelle une méthode
    RegistryKey<CatVariant> SIAMESE = RegistryKey.unsafeOf("siamese");

    // Appelle une méthode
    RegistryKey<CatVariant> PERSIAN = RegistryKey.unsafeOf("persian");

    // Appelle une méthode
    RegistryKey<CatVariant> BRITISH_SHORTHAIR = RegistryKey.unsafeOf("british_shorthair");

    // Appelle une méthode
    RegistryKey<CatVariant> RED = RegistryKey.unsafeOf("red");

    // Appelle une méthode
    RegistryKey<CatVariant> WHITE = RegistryKey.unsafeOf("white");
// Fin d'un bloc/d'une expression
}
