// Package declaration for this file
package net.minestom.server.entity.metadata.animal.tameable;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link WolfVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface WolfVariants permits WolfVariant {
    // Calls a method
    RegistryKey<WolfVariant> BLACK = RegistryKey.unsafeOf("black");

    // Calls a method
    RegistryKey<WolfVariant> SNOWY = RegistryKey.unsafeOf("snowy");

    // Calls a method
    RegistryKey<WolfVariant> CHESTNUT = RegistryKey.unsafeOf("chestnut");

    // Calls a method
    RegistryKey<WolfVariant> STRIPED = RegistryKey.unsafeOf("striped");

    // Calls a method
    RegistryKey<WolfVariant> SPOTTED = RegistryKey.unsafeOf("spotted");

    // Calls a method
    RegistryKey<WolfVariant> ASHEN = RegistryKey.unsafeOf("ashen");

    // Calls a method
    RegistryKey<WolfVariant> WOODS = RegistryKey.unsafeOf("woods");

    // Calls a method
    RegistryKey<WolfVariant> RUSTY = RegistryKey.unsafeOf("rusty");

    // Calls a method
    RegistryKey<WolfVariant> PALE = RegistryKey.unsafeOf("pale");
// End of a block/expression
}
