// Déclaration du paquet de ce fichier
package net.minestom.server.entity.metadata.animal.tameable;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link WolfVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface WolfVariants permits WolfVariant {
    // Appelle une méthode
    RegistryKey<WolfVariant> BLACK = RegistryKey.unsafeOf("black");

    // Appelle une méthode
    RegistryKey<WolfVariant> SNOWY = RegistryKey.unsafeOf("snowy");

    // Appelle une méthode
    RegistryKey<WolfVariant> CHESTNUT = RegistryKey.unsafeOf("chestnut");

    // Appelle une méthode
    RegistryKey<WolfVariant> STRIPED = RegistryKey.unsafeOf("striped");

    // Appelle une méthode
    RegistryKey<WolfVariant> SPOTTED = RegistryKey.unsafeOf("spotted");

    // Appelle une méthode
    RegistryKey<WolfVariant> ASHEN = RegistryKey.unsafeOf("ashen");

    // Appelle une méthode
    RegistryKey<WolfVariant> WOODS = RegistryKey.unsafeOf("woods");

    // Appelle une méthode
    RegistryKey<WolfVariant> RUSTY = RegistryKey.unsafeOf("rusty");

    // Appelle une méthode
    RegistryKey<WolfVariant> PALE = RegistryKey.unsafeOf("pale");
// Fin d'un bloc/d'une expression
}
