// Déclaration du paquet de ce fichier
package net.minestom.server.entity.metadata.animal.tameable;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link WolfSoundVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface WolfSoundVariants permits WolfSoundVariant {
    // Appelle une méthode
    RegistryKey<WolfSoundVariant> SAD = RegistryKey.unsafeOf("sad");

    // Appelle une méthode
    RegistryKey<WolfSoundVariant> PUGLIN = RegistryKey.unsafeOf("puglin");

    // Appelle une méthode
    RegistryKey<WolfSoundVariant> CUTE = RegistryKey.unsafeOf("cute");

    // Appelle une méthode
    RegistryKey<WolfSoundVariant> GRUMPY = RegistryKey.unsafeOf("grumpy");

    // Appelle une méthode
    RegistryKey<WolfSoundVariant> BIG = RegistryKey.unsafeOf("big");

    // Appelle une méthode
    RegistryKey<WolfSoundVariant> ANGRY = RegistryKey.unsafeOf("angry");

    // Appelle une méthode
    RegistryKey<WolfSoundVariant> CLASSIC = RegistryKey.unsafeOf("classic");
// Fin d'un bloc/d'une expression
}
