// Package declaration for this file
package net.minestom.server.entity.metadata.animal.tameable;

// Import of a required class
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link WolfSoundVariant}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface WolfSoundVariants permits WolfSoundVariant {
    // Calls a method
    RegistryKey<WolfSoundVariant> SAD = RegistryKey.unsafeOf("sad");

    // Calls a method
    RegistryKey<WolfSoundVariant> PUGLIN = RegistryKey.unsafeOf("puglin");

    // Calls a method
    RegistryKey<WolfSoundVariant> CUTE = RegistryKey.unsafeOf("cute");

    // Calls a method
    RegistryKey<WolfSoundVariant> GRUMPY = RegistryKey.unsafeOf("grumpy");

    // Calls a method
    RegistryKey<WolfSoundVariant> BIG = RegistryKey.unsafeOf("big");

    // Calls a method
    RegistryKey<WolfSoundVariant> ANGRY = RegistryKey.unsafeOf("angry");

    // Calls a method
    RegistryKey<WolfSoundVariant> CLASSIC = RegistryKey.unsafeOf("classic");
// End of a block/expression
}
