// Déclaration du paquet de ce fichier
package net.minestom.server.color;

// Import d'une classe nécessaire
import net.kyori.adventure.util.RGBLike;
// Import d'une classe nécessaire
import net.minestom.server.codec.Codec;
// Import d'une classe nécessaire
import net.minestom.server.network.NetworkBuffer;

/**
 * AUTOGENERATED by DyeColorGenerator
 */
// Déclaration de type (classe/interface/enum/record)
public enum DyeColor implements RGBLike {
    // Instruction de code
    WHITE(new Color(0xf9fffe), new Color(0xffffff), new Color(0xf0f0f0), 8),

    // Instruction de code
    ORANGE(new Color(0xf9801d), new Color(0xff681f), new Color(0xeb8844), 15),

    // Instruction de code
    MAGENTA(new Color(0xc74ebd), new Color(0xff00ff), new Color(0xc354cd), 16),

    // Instruction de code
    LIGHT_BLUE(new Color(0x3ab3da), new Color(0x9ac0cd), new Color(0x6689d3), 17),

    // Instruction de code
    YELLOW(new Color(0xfed83d), new Color(0xffff00), new Color(0xdecf2a), 18),

    // Instruction de code
    LIME(new Color(0x80c71f), new Color(0xbfff00), new Color(0x41cd34), 19),

    // Instruction de code
    PINK(new Color(0xf38baa), new Color(0xff69b4), new Color(0xd88198), 20),

    // Instruction de code
    GRAY(new Color(0x474f52), new Color(0x808080), new Color(0x434343), 21),

    // Instruction de code
    LIGHT_GRAY(new Color(0x9d9d97), new Color(0xd3d3d3), new Color(0xababab), 22),

    // Instruction de code
    CYAN(new Color(0x169c9c), new Color(0x00ffff), new Color(0x287697), 23),

    // Instruction de code
    PURPLE(new Color(0x8932b8), new Color(0xa020f0), new Color(0x7b2fbe), 24),

    // Instruction de code
    BLUE(new Color(0x3c44aa), new Color(0x0000ff), new Color(0x253192), 25),

    // Instruction de code
    BROWN(new Color(0x835432), new Color(0x8b4513), new Color(0x51301a), 26),

    // Instruction de code
    GREEN(new Color(0x5e7c16), new Color(0x00ff00), new Color(0x3b511a), 27),

    // Instruction de code
    RED(new Color(0xb02e26), new Color(0xff0000), new Color(0xb3312c), 28),

    // Appelle une méthode
    BLACK(new Color(0x1d1d21), new Color(0x000000), new Color(0x1e1b1b), 29);

    // Appelle une méthode
    public static final NetworkBuffer.Type<DyeColor> NETWORK_TYPE = NetworkBuffer.Enum(DyeColor.class);

    // Appelle une méthode
    public static final Codec<DyeColor> CODEC = Codec.Enum(DyeColor.class);

    // Instruction de code
    private final Color textureDiffuseColor;

    // Instruction de code
    private final Color textColor;

    // Instruction de code
    private final Color fireworkColor;

    // Instruction de code
    private final int mapColorId;

    // Début d'une méthode/d'un bloc
    DyeColor(Color textureDiffuseColor, Color textColor, Color fireworkColor, int mapColorId) {
        // Accès à l'objet courant/parent
        this.textureDiffuseColor = textureDiffuseColor;
        // Accès à l'objet courant/parent
        this.textColor = textColor;
        // Accès à l'objet courant/parent
        this.fireworkColor = fireworkColor;
        // Accès à l'objet courant/parent
        this.mapColorId = mapColorId;
    // Fin d'un bloc/d'une expression
    }

    // Début d'une méthode/d'un bloc
    public Color color() {
        // Renvoie une valeur à l'appelant
        return this.textureDiffuseColor;
    // Fin d'un bloc/d'une expression
    }

    // Début d'une méthode/d'un bloc
    public Color textColor() {
        // Renvoie une valeur à l'appelant
        return this.textColor;
    // Fin d'un bloc/d'une expression
    }

    // Début d'une méthode/d'un bloc
    public Color fireworkColor() {
        // Renvoie une valeur à l'appelant
        return this.fireworkColor;
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public int red() {
        // Renvoie une valeur à l'appelant
        return this.textureDiffuseColor.red();
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public int green() {
        // Renvoie une valeur à l'appelant
        return this.textureDiffuseColor.green();
    // Fin d'un bloc/d'une expression
    }

    // Annotation pour l'élément suivant
    @Override
    // Début d'une méthode/d'un bloc
    public int blue() {
        // Renvoie une valeur à l'appelant
        return this.textureDiffuseColor.blue();
    // Fin d'un bloc/d'une expression
    }

    // Début d'une méthode/d'un bloc
    public int mapColorId() {
        // Renvoie une valeur à l'appelant
        return this.mapColorId;
    // Fin d'un bloc/d'une expression
    }
// Fin d'un bloc/d'une expression
}
