// Déclaration du paquet de ce fichier
package net.minestom.server.world.biome;

// Import d'une classe nécessaire
import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link Biome}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface Biomes permits Biome {
    // Appelle une méthode
    RegistryKey<Biome> BAMBOO_JUNGLE = RegistryKey.unsafeOf("bamboo_jungle");

    // Appelle une méthode
    RegistryKey<Biome> JUNGLE = RegistryKey.unsafeOf("jungle");

    // Appelle une méthode
    RegistryKey<Biome> LUKEWARM_OCEAN = RegistryKey.unsafeOf("lukewarm_ocean");

    // Appelle une méthode
    RegistryKey<Biome> WINDSWEPT_SAVANNA = RegistryKey.unsafeOf("windswept_savanna");

    // Appelle une méthode
    RegistryKey<Biome> MANGROVE_SWAMP = RegistryKey.unsafeOf("mangrove_swamp");

    // Appelle une méthode
    RegistryKey<Biome> STONY_SHORE = RegistryKey.unsafeOf("stony_shore");

    // Appelle une méthode
    RegistryKey<Biome> OCEAN = RegistryKey.unsafeOf("ocean");

    // Appelle une méthode
    RegistryKey<Biome> END_HIGHLANDS = RegistryKey.unsafeOf("end_highlands");

    // Appelle une méthode
    RegistryKey<Biome> FROZEN_RIVER = RegistryKey.unsafeOf("frozen_river");

    // Appelle une méthode
    RegistryKey<Biome> DEEP_FROZEN_OCEAN = RegistryKey.unsafeOf("deep_frozen_ocean");

    // Appelle une méthode
    RegistryKey<Biome> DEEP_COLD_OCEAN = RegistryKey.unsafeOf("deep_cold_ocean");

    // Appelle une méthode
    RegistryKey<Biome> TAIGA = RegistryKey.unsafeOf("taiga");

    // Appelle une méthode
    RegistryKey<Biome> DRIPSTONE_CAVES = RegistryKey.unsafeOf("dripstone_caves");

    // Appelle une méthode
    RegistryKey<Biome> WINDSWEPT_FOREST = RegistryKey.unsafeOf("windswept_forest");

    // Appelle une méthode
    RegistryKey<Biome> FLOWER_FOREST = RegistryKey.unsafeOf("flower_forest");

    // Appelle une méthode
    RegistryKey<Biome> CHERRY_GROVE = RegistryKey.unsafeOf("cherry_grove");

    // Appelle une méthode
    RegistryKey<Biome> SAVANNA_PLATEAU = RegistryKey.unsafeOf("savanna_plateau");

    // Appelle une méthode
    RegistryKey<Biome> WINDSWEPT_HILLS = RegistryKey.unsafeOf("windswept_hills");

    // Appelle une méthode
    RegistryKey<Biome> WINDSWEPT_GRAVELLY_HILLS = RegistryKey.unsafeOf("windswept_gravelly_hills");

    // Appelle une méthode
    RegistryKey<Biome> WARPED_FOREST = RegistryKey.unsafeOf("warped_forest");

    // Appelle une méthode
    RegistryKey<Biome> SAVANNA = RegistryKey.unsafeOf("savanna");

    // Appelle une méthode
    RegistryKey<Biome> RIVER = RegistryKey.unsafeOf("river");

    // Appelle une méthode
    RegistryKey<Biome> DARK_FOREST = RegistryKey.unsafeOf("dark_forest");

    // Appelle une méthode
    RegistryKey<Biome> FROZEN_PEAKS = RegistryKey.unsafeOf("frozen_peaks");

    // Appelle une méthode
    RegistryKey<Biome> SOUL_SAND_VALLEY = RegistryKey.unsafeOf("soul_sand_valley");

    // Appelle une méthode
    RegistryKey<Biome> WOODED_BADLANDS = RegistryKey.unsafeOf("wooded_badlands");

    // Appelle une méthode
    RegistryKey<Biome> END_BARRENS = RegistryKey.unsafeOf("end_barrens");

    // Appelle une méthode
    RegistryKey<Biome> BADLANDS = RegistryKey.unsafeOf("badlands");

    // Appelle une méthode
    RegistryKey<Biome> SNOWY_PLAINS = RegistryKey.unsafeOf("snowy_plains");

    // Appelle une méthode
    RegistryKey<Biome> LUSH_CAVES = RegistryKey.unsafeOf("lush_caves");

    // Appelle une méthode
    RegistryKey<Biome> THE_VOID = RegistryKey.unsafeOf("the_void");

    // Appelle une méthode
    RegistryKey<Biome> DESERT = RegistryKey.unsafeOf("desert");

    // Appelle une méthode
    RegistryKey<Biome> BASALT_DELTAS = RegistryKey.unsafeOf("basalt_deltas");

    // Appelle une méthode
    RegistryKey<Biome> GROVE = RegistryKey.unsafeOf("grove");

    // Appelle une méthode
    RegistryKey<Biome> BEACH = RegistryKey.unsafeOf("beach");

    // Appelle une méthode
    RegistryKey<Biome> THE_END = RegistryKey.unsafeOf("the_end");

    // Appelle une méthode
    RegistryKey<Biome> SNOWY_TAIGA = RegistryKey.unsafeOf("snowy_taiga");

    // Appelle une méthode
    RegistryKey<Biome> PALE_GARDEN = RegistryKey.unsafeOf("pale_garden");

    // Appelle une méthode
    RegistryKey<Biome> SNOWY_SLOPES = RegistryKey.unsafeOf("snowy_slopes");

    // Appelle une méthode
    RegistryKey<Biome> DEEP_OCEAN = RegistryKey.unsafeOf("deep_ocean");

    // Appelle une méthode
    RegistryKey<Biome> SMALL_END_ISLANDS = RegistryKey.unsafeOf("small_end_islands");

    // Appelle une méthode
    RegistryKey<Biome> MEADOW = RegistryKey.unsafeOf("meadow");

    // Appelle une méthode
    RegistryKey<Biome> SWAMP = RegistryKey.unsafeOf("swamp");

    // Appelle une méthode
    RegistryKey<Biome> DEEP_LUKEWARM_OCEAN = RegistryKey.unsafeOf("deep_lukewarm_ocean");

    // Appelle une méthode
    RegistryKey<Biome> COLD_OCEAN = RegistryKey.unsafeOf("cold_ocean");

    // Appelle une méthode
    RegistryKey<Biome> STONY_PEAKS = RegistryKey.unsafeOf("stony_peaks");

    // Appelle une méthode
    RegistryKey<Biome> CRIMSON_FOREST = RegistryKey.unsafeOf("crimson_forest");

    // Appelle une méthode
    RegistryKey<Biome> SPARSE_JUNGLE = RegistryKey.unsafeOf("sparse_jungle");

    // Appelle une méthode
    RegistryKey<Biome> ERODED_BADLANDS = RegistryKey.unsafeOf("eroded_badlands");

    // Appelle une méthode
    RegistryKey<Biome> END_MIDLANDS = RegistryKey.unsafeOf("end_midlands");

    // Appelle une méthode
    RegistryKey<Biome> DEEP_DARK = RegistryKey.unsafeOf("deep_dark");

    // Appelle une méthode
    RegistryKey<Biome> OLD_GROWTH_BIRCH_FOREST = RegistryKey.unsafeOf("old_growth_birch_forest");

    // Appelle une méthode
    RegistryKey<Biome> BIRCH_FOREST = RegistryKey.unsafeOf("birch_forest");

    // Appelle une méthode
    RegistryKey<Biome> SUNFLOWER_PLAINS = RegistryKey.unsafeOf("sunflower_plains");

    // Appelle une méthode
    RegistryKey<Biome> NETHER_WASTES = RegistryKey.unsafeOf("nether_wastes");

    // Appelle une méthode
    RegistryKey<Biome> WARM_OCEAN = RegistryKey.unsafeOf("warm_ocean");

    // Appelle une méthode
    RegistryKey<Biome> ICE_SPIKES = RegistryKey.unsafeOf("ice_spikes");

    // Appelle une méthode
    RegistryKey<Biome> JAGGED_PEAKS = RegistryKey.unsafeOf("jagged_peaks");

    // Appelle une méthode
    RegistryKey<Biome> PLAINS = RegistryKey.unsafeOf("plains");

    // Appelle une méthode
    RegistryKey<Biome> MUSHROOM_FIELDS = RegistryKey.unsafeOf("mushroom_fields");

    // Appelle une méthode
    RegistryKey<Biome> FROZEN_OCEAN = RegistryKey.unsafeOf("frozen_ocean");

    // Appelle une méthode
    RegistryKey<Biome> FOREST = RegistryKey.unsafeOf("forest");

    // Appelle une méthode
    RegistryKey<Biome> OLD_GROWTH_SPRUCE_TAIGA = RegistryKey.unsafeOf("old_growth_spruce_taiga");

    // Appelle une méthode
    RegistryKey<Biome> SNOWY_BEACH = RegistryKey.unsafeOf("snowy_beach");

    // Appelle une méthode
    RegistryKey<Biome> OLD_GROWTH_PINE_TAIGA = RegistryKey.unsafeOf("old_growth_pine_taiga");
// Fin d'un bloc/d'une expression
}
