// Package declaration for this file
package net.minestom.server.instance.block;

/**
 * This class contains all the generated constants for {@link BlockSoundType}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation for the following element
@SuppressWarnings("unused")
// Type declaration (class/interface/enum/record)
sealed interface BlockSoundTypes permits BlockSoundType {
    // Calls a method
    BlockSoundType EMPTY = BlockSoundImpl.get("empty");

    // Calls a method
    BlockSoundType WOOD = BlockSoundImpl.get("wood");

    // Calls a method
    BlockSoundType GRAVEL = BlockSoundImpl.get("gravel");

    // Calls a method
    BlockSoundType GRASS = BlockSoundImpl.get("grass");

    // Calls a method
    BlockSoundType LILY_PAD = BlockSoundImpl.get("lily_pad");

    // Calls a method
    BlockSoundType STONE = BlockSoundImpl.get("stone");

    // Calls a method
    BlockSoundType METAL = BlockSoundImpl.get("metal");

    // Calls a method
    BlockSoundType GLASS = BlockSoundImpl.get("glass");

    // Calls a method
    BlockSoundType WOOL = BlockSoundImpl.get("wool");

    // Calls a method
    BlockSoundType SAND = BlockSoundImpl.get("sand");

    // Calls a method
    BlockSoundType SNOW = BlockSoundImpl.get("snow");

    // Calls a method
    BlockSoundType POWDER_SNOW = BlockSoundImpl.get("powder_snow");

    // Calls a method
    BlockSoundType LADDER = BlockSoundImpl.get("ladder");

    // Calls a method
    BlockSoundType ANVIL = BlockSoundImpl.get("anvil");

    // Calls a method
    BlockSoundType SLIME_BLOCK = BlockSoundImpl.get("slime_block");

    // Calls a method
    BlockSoundType HONEY_BLOCK = BlockSoundImpl.get("honey_block");

    // Calls a method
    BlockSoundType WET_GRASS = BlockSoundImpl.get("wet_grass");

    // Calls a method
    BlockSoundType CORAL_BLOCK = BlockSoundImpl.get("coral_block");

    // Calls a method
    BlockSoundType BAMBOO = BlockSoundImpl.get("bamboo");

    // Calls a method
    BlockSoundType BAMBOO_SAPLING = BlockSoundImpl.get("bamboo_sapling");

    // Calls a method
    BlockSoundType SCAFFOLDING = BlockSoundImpl.get("scaffolding");

    // Calls a method
    BlockSoundType SWEET_BERRY_BUSH = BlockSoundImpl.get("sweet_berry_bush");

    // Calls a method
    BlockSoundType CROP = BlockSoundImpl.get("crop");

    // Calls a method
    BlockSoundType HARD_CROP = BlockSoundImpl.get("hard_crop");

    // Calls a method
    BlockSoundType VINE = BlockSoundImpl.get("vine");

    // Calls a method
    BlockSoundType NETHER_WART = BlockSoundImpl.get("nether_wart");

    // Calls a method
    BlockSoundType LANTERN = BlockSoundImpl.get("lantern");

    // Calls a method
    BlockSoundType STEM = BlockSoundImpl.get("stem");

    // Calls a method
    BlockSoundType NYLIUM = BlockSoundImpl.get("nylium");

    // Calls a method
    BlockSoundType FUNGUS = BlockSoundImpl.get("fungus");

    // Calls a method
    BlockSoundType ROOTS = BlockSoundImpl.get("roots");

    // Calls a method
    BlockSoundType SHROOMLIGHT = BlockSoundImpl.get("shroomlight");

    // Calls a method
    BlockSoundType WEEPING_VINES = BlockSoundImpl.get("weeping_vines");

    // Calls a method
    BlockSoundType TWISTING_VINES = BlockSoundImpl.get("twisting_vines");

    // Calls a method
    BlockSoundType SOUL_SAND = BlockSoundImpl.get("soul_sand");

    // Calls a method
    BlockSoundType SOUL_SOIL = BlockSoundImpl.get("soul_soil");

    // Calls a method
    BlockSoundType BASALT = BlockSoundImpl.get("basalt");

    // Calls a method
    BlockSoundType WART_BLOCK = BlockSoundImpl.get("wart_block");

    // Calls a method
    BlockSoundType NETHERRACK = BlockSoundImpl.get("netherrack");

    // Calls a method
    BlockSoundType NETHER_BRICKS = BlockSoundImpl.get("nether_bricks");

    // Calls a method
    BlockSoundType NETHER_SPROUTS = BlockSoundImpl.get("nether_sprouts");

    // Calls a method
    BlockSoundType NETHER_ORE = BlockSoundImpl.get("nether_ore");

    // Calls a method
    BlockSoundType BONE_BLOCK = BlockSoundImpl.get("bone_block");

    // Calls a method
    BlockSoundType NETHERITE_BLOCK = BlockSoundImpl.get("netherite_block");

    // Calls a method
    BlockSoundType ANCIENT_DEBRIS = BlockSoundImpl.get("ancient_debris");

    // Calls a method
    BlockSoundType LODESTONE = BlockSoundImpl.get("lodestone");

    // Calls a method
    BlockSoundType CHAIN = BlockSoundImpl.get("chain");

    // Calls a method
    BlockSoundType NETHER_GOLD_ORE = BlockSoundImpl.get("nether_gold_ore");

    // Calls a method
    BlockSoundType GILDED_BLACKSTONE = BlockSoundImpl.get("gilded_blackstone");

    // Calls a method
    BlockSoundType CANDLE = BlockSoundImpl.get("candle");

    // Calls a method
    BlockSoundType AMETHYST = BlockSoundImpl.get("amethyst");

    // Calls a method
    BlockSoundType AMETHYST_CLUSTER = BlockSoundImpl.get("amethyst_cluster");

    // Calls a method
    BlockSoundType SMALL_AMETHYST_BUD = BlockSoundImpl.get("small_amethyst_bud");

    // Calls a method
    BlockSoundType MEDIUM_AMETHYST_BUD = BlockSoundImpl.get("medium_amethyst_bud");

    // Calls a method
    BlockSoundType LARGE_AMETHYST_BUD = BlockSoundImpl.get("large_amethyst_bud");

    // Calls a method
    BlockSoundType TUFF = BlockSoundImpl.get("tuff");

    // Calls a method
    BlockSoundType TUFF_BRICKS = BlockSoundImpl.get("tuff_bricks");

    // Calls a method
    BlockSoundType POLISHED_TUFF = BlockSoundImpl.get("polished_tuff");

    // Calls a method
    BlockSoundType CALCITE = BlockSoundImpl.get("calcite");

    // Calls a method
    BlockSoundType DRIPSTONE_BLOCK = BlockSoundImpl.get("dripstone_block");

    // Calls a method
    BlockSoundType POINTED_DRIPSTONE = BlockSoundImpl.get("pointed_dripstone");

    // Calls a method
    BlockSoundType COPPER = BlockSoundImpl.get("copper");

    // Calls a method
    BlockSoundType COPPER_BULB = BlockSoundImpl.get("copper_bulb");

    // Calls a method
    BlockSoundType COPPER_GRATE = BlockSoundImpl.get("copper_grate");

    // Calls a method
    BlockSoundType COPPER_GOLEM_STATUE = BlockSoundImpl.get("copper_golem_statue");

    // Calls a method
    BlockSoundType CAVE_VINES = BlockSoundImpl.get("cave_vines");

    // Calls a method
    BlockSoundType SPORE_BLOSSOM = BlockSoundImpl.get("spore_blossom");

    // Calls a method
    BlockSoundType CACTUS_FLOWER = BlockSoundImpl.get("cactus_flower");

    // Calls a method
    BlockSoundType AZALEA = BlockSoundImpl.get("azalea");

    // Calls a method
    BlockSoundType FLOWERING_AZALEA = BlockSoundImpl.get("flowering_azalea");

    // Calls a method
    BlockSoundType MOSS_CARPET = BlockSoundImpl.get("moss_carpet");

    // Calls a method
    BlockSoundType PINK_PETALS = BlockSoundImpl.get("pink_petals");

    // Calls a method
    BlockSoundType LEAF_LITTER = BlockSoundImpl.get("leaf_litter");

    // Calls a method
    BlockSoundType MOSS = BlockSoundImpl.get("moss");

    // Calls a method
    BlockSoundType BIG_DRIPLEAF = BlockSoundImpl.get("big_dripleaf");

    // Calls a method
    BlockSoundType SMALL_DRIPLEAF = BlockSoundImpl.get("small_dripleaf");

    // Calls a method
    BlockSoundType ROOTED_DIRT = BlockSoundImpl.get("rooted_dirt");

    // Calls a method
    BlockSoundType HANGING_ROOTS = BlockSoundImpl.get("hanging_roots");

    // Calls a method
    BlockSoundType AZALEA_LEAVES = BlockSoundImpl.get("azalea_leaves");

    // Calls a method
    BlockSoundType SCULK_SENSOR = BlockSoundImpl.get("sculk_sensor");

    // Calls a method
    BlockSoundType SCULK_CATALYST = BlockSoundImpl.get("sculk_catalyst");

    // Calls a method
    BlockSoundType SCULK = BlockSoundImpl.get("sculk");

    // Calls a method
    BlockSoundType SCULK_VEIN = BlockSoundImpl.get("sculk_vein");

    // Calls a method
    BlockSoundType SCULK_SHRIEKER = BlockSoundImpl.get("sculk_shrieker");

    // Calls a method
    BlockSoundType GLOW_LICHEN = BlockSoundImpl.get("glow_lichen");

    // Calls a method
    BlockSoundType DEEPSLATE = BlockSoundImpl.get("deepslate");

    // Calls a method
    BlockSoundType DEEPSLATE_BRICKS = BlockSoundImpl.get("deepslate_bricks");

    // Calls a method
    BlockSoundType DEEPSLATE_TILES = BlockSoundImpl.get("deepslate_tiles");

    // Calls a method
    BlockSoundType POLISHED_DEEPSLATE = BlockSoundImpl.get("polished_deepslate");

    // Calls a method
    BlockSoundType FROGLIGHT = BlockSoundImpl.get("froglight");

    // Calls a method
    BlockSoundType FROGSPAWN = BlockSoundImpl.get("frogspawn");

    // Calls a method
    BlockSoundType MANGROVE_ROOTS = BlockSoundImpl.get("mangrove_roots");

    // Calls a method
    BlockSoundType MUDDY_MANGROVE_ROOTS = BlockSoundImpl.get("muddy_mangrove_roots");

    // Calls a method
    BlockSoundType MUD = BlockSoundImpl.get("mud");

    // Calls a method
    BlockSoundType MUD_BRICKS = BlockSoundImpl.get("mud_bricks");

    // Calls a method
    BlockSoundType PACKED_MUD = BlockSoundImpl.get("packed_mud");

    // Calls a method
    BlockSoundType HANGING_SIGN = BlockSoundImpl.get("hanging_sign");

    // Calls a method
    BlockSoundType NETHER_WOOD_HANGING_SIGN = BlockSoundImpl.get("nether_wood_hanging_sign");

    // Calls a method
    BlockSoundType BAMBOO_WOOD_HANGING_SIGN = BlockSoundImpl.get("bamboo_wood_hanging_sign");

    // Calls a method
    BlockSoundType BAMBOO_WOOD = BlockSoundImpl.get("bamboo_wood");

    // Calls a method
    BlockSoundType NETHER_WOOD = BlockSoundImpl.get("nether_wood");

    // Calls a method
    BlockSoundType CHERRY_WOOD = BlockSoundImpl.get("cherry_wood");

    // Calls a method
    BlockSoundType CHERRY_SAPLING = BlockSoundImpl.get("cherry_sapling");

    // Calls a method
    BlockSoundType CHERRY_LEAVES = BlockSoundImpl.get("cherry_leaves");

    // Calls a method
    BlockSoundType CHERRY_WOOD_HANGING_SIGN = BlockSoundImpl.get("cherry_wood_hanging_sign");

    // Calls a method
    BlockSoundType CHISELED_BOOKSHELF = BlockSoundImpl.get("chiseled_bookshelf");

    // Calls a method
    BlockSoundType SHELF = BlockSoundImpl.get("shelf");

    // Calls a method
    BlockSoundType SUSPICIOUS_SAND = BlockSoundImpl.get("suspicious_sand");

    // Calls a method
    BlockSoundType SUSPICIOUS_GRAVEL = BlockSoundImpl.get("suspicious_gravel");

    // Calls a method
    BlockSoundType DECORATED_POT = BlockSoundImpl.get("decorated_pot");

    // Calls a method
    BlockSoundType DECORATED_POT_CRACKED = BlockSoundImpl.get("decorated_pot_cracked");

    // Calls a method
    BlockSoundType TRIAL_SPAWNER = BlockSoundImpl.get("trial_spawner");

    // Calls a method
    BlockSoundType SPONGE = BlockSoundImpl.get("sponge");

    // Calls a method
    BlockSoundType WET_SPONGE = BlockSoundImpl.get("wet_sponge");

    // Calls a method
    BlockSoundType VAULT = BlockSoundImpl.get("vault");

    // Calls a method
    BlockSoundType CREAKING_HEART = BlockSoundImpl.get("creaking_heart");

    // Calls a method
    BlockSoundType HEAVY_CORE = BlockSoundImpl.get("heavy_core");

    // Calls a method
    BlockSoundType COBWEB = BlockSoundImpl.get("cobweb");

    // Calls a method
    BlockSoundType SPAWNER = BlockSoundImpl.get("spawner");

    // Calls a method
    BlockSoundType RESIN = BlockSoundImpl.get("resin");

    // Calls a method
    BlockSoundType RESIN_BRICKS = BlockSoundImpl.get("resin_bricks");

    // Calls a method
    BlockSoundType IRON = BlockSoundImpl.get("iron");

    // Calls a method
    BlockSoundType DRIED_GHAST = BlockSoundImpl.get("dried_ghast");
// End of a block/expression
}
