// Déclaration du paquet de ce fichier
package net.minestom.server.instance.block;

/**
 * This class contains all the generated constants for {@link BlockEntityType}
 * <br>
 * Code autogenerated, do not edit!
 */
// Annotation pour l'élément suivant
@SuppressWarnings("unused")
// Déclaration de type (classe/interface/enum/record)
sealed interface BlockEntityTypes permits BlockEntityType {
    // Appelle une méthode
    BlockEntityType FURNACE = BlockEntityTypeImpl.get("furnace");

    // Appelle une méthode
    BlockEntityType CHEST = BlockEntityTypeImpl.get("chest");

    // Appelle une méthode
    BlockEntityType TRAPPED_CHEST = BlockEntityTypeImpl.get("trapped_chest");

    // Appelle une méthode
    BlockEntityType ENDER_CHEST = BlockEntityTypeImpl.get("ender_chest");

    // Appelle une méthode
    BlockEntityType JUKEBOX = BlockEntityTypeImpl.get("jukebox");

    // Appelle une méthode
    BlockEntityType DISPENSER = BlockEntityTypeImpl.get("dispenser");

    // Appelle une méthode
    BlockEntityType DROPPER = BlockEntityTypeImpl.get("dropper");

    // Appelle une méthode
    BlockEntityType SIGN = BlockEntityTypeImpl.get("sign");

    // Appelle une méthode
    BlockEntityType HANGING_SIGN = BlockEntityTypeImpl.get("hanging_sign");

    // Appelle une méthode
    BlockEntityType MOB_SPAWNER = BlockEntityTypeImpl.get("mob_spawner");

    // Appelle une méthode
    BlockEntityType CREAKING_HEART = BlockEntityTypeImpl.get("creaking_heart");

    // Appelle une méthode
    BlockEntityType PISTON = BlockEntityTypeImpl.get("piston");

    // Appelle une méthode
    BlockEntityType BREWING_STAND = BlockEntityTypeImpl.get("brewing_stand");

    // Appelle une méthode
    BlockEntityType ENCHANTING_TABLE = BlockEntityTypeImpl.get("enchanting_table");

    // Appelle une méthode
    BlockEntityType END_PORTAL = BlockEntityTypeImpl.get("end_portal");

    // Appelle une méthode
    BlockEntityType BEACON = BlockEntityTypeImpl.get("beacon");

    // Appelle une méthode
    BlockEntityType SKULL = BlockEntityTypeImpl.get("skull");

    // Appelle une méthode
    BlockEntityType DAYLIGHT_DETECTOR = BlockEntityTypeImpl.get("daylight_detector");

    // Appelle une méthode
    BlockEntityType HOPPER = BlockEntityTypeImpl.get("hopper");

    // Appelle une méthode
    BlockEntityType COMPARATOR = BlockEntityTypeImpl.get("comparator");

    // Appelle une méthode
    BlockEntityType BANNER = BlockEntityTypeImpl.get("banner");

    // Appelle une méthode
    BlockEntityType STRUCTURE_BLOCK = BlockEntityTypeImpl.get("structure_block");

    // Appelle une méthode
    BlockEntityType END_GATEWAY = BlockEntityTypeImpl.get("end_gateway");

    // Appelle une méthode
    BlockEntityType COMMAND_BLOCK = BlockEntityTypeImpl.get("command_block");

    // Appelle une méthode
    BlockEntityType SHULKER_BOX = BlockEntityTypeImpl.get("shulker_box");

    // Appelle une méthode
    BlockEntityType BED = BlockEntityTypeImpl.get("bed");

    // Appelle une méthode
    BlockEntityType CONDUIT = BlockEntityTypeImpl.get("conduit");

    // Appelle une méthode
    BlockEntityType BARREL = BlockEntityTypeImpl.get("barrel");

    // Appelle une méthode
    BlockEntityType SMOKER = BlockEntityTypeImpl.get("smoker");

    // Appelle une méthode
    BlockEntityType BLAST_FURNACE = BlockEntityTypeImpl.get("blast_furnace");

    // Appelle une méthode
    BlockEntityType LECTERN = BlockEntityTypeImpl.get("lectern");

    // Appelle une méthode
    BlockEntityType BELL = BlockEntityTypeImpl.get("bell");

    // Appelle une méthode
    BlockEntityType JIGSAW = BlockEntityTypeImpl.get("jigsaw");

    // Appelle une méthode
    BlockEntityType CAMPFIRE = BlockEntityTypeImpl.get("campfire");

    // Appelle une méthode
    BlockEntityType BEEHIVE = BlockEntityTypeImpl.get("beehive");

    // Appelle une méthode
    BlockEntityType SCULK_SENSOR = BlockEntityTypeImpl.get("sculk_sensor");

    // Appelle une méthode
    BlockEntityType CALIBRATED_SCULK_SENSOR = BlockEntityTypeImpl.get("calibrated_sculk_sensor");

    // Appelle une méthode
    BlockEntityType SCULK_CATALYST = BlockEntityTypeImpl.get("sculk_catalyst");

    // Appelle une méthode
    BlockEntityType SCULK_SHRIEKER = BlockEntityTypeImpl.get("sculk_shrieker");

    // Appelle une méthode
    BlockEntityType CHISELED_BOOKSHELF = BlockEntityTypeImpl.get("chiseled_bookshelf");

    // Appelle une méthode
    BlockEntityType SHELF = BlockEntityTypeImpl.get("shelf");

    // Appelle une méthode
    BlockEntityType BRUSHABLE_BLOCK = BlockEntityTypeImpl.get("brushable_block");

    // Appelle une méthode
    BlockEntityType DECORATED_POT = BlockEntityTypeImpl.get("decorated_pot");

    // Appelle une méthode
    BlockEntityType CRAFTER = BlockEntityTypeImpl.get("crafter");

    // Appelle une méthode
    BlockEntityType TRIAL_SPAWNER = BlockEntityTypeImpl.get("trial_spawner");

    // Appelle une méthode
    BlockEntityType VAULT = BlockEntityTypeImpl.get("vault");

    // Appelle une méthode
    BlockEntityType TEST_BLOCK = BlockEntityTypeImpl.get("test_block");

    // Appelle une méthode
    BlockEntityType TEST_INSTANCE_BLOCK = BlockEntityTypeImpl.get("test_instance_block");

    // Appelle une méthode
    BlockEntityType COPPER_GOLEM_STATUE = BlockEntityTypeImpl.get("copper_golem_statue");
// Fin d'un bloc/d'une expression
}
